### ISSUE TITLE
plex token not written to preferences on first run

### ISSUE THREAD

**Issue by leviwheatcroft** [linuxserver/docker-plex#100]
The basic problem is that the ui running at `32400/web` can't find / connect to the server from this container. But in trying to figure out out there's some other odd things going on.

If I create a fresh container...

```bash
rm -fr /srv/config/plex/* && \
docker create --name=plex \
--net=host \
-e VERSION=latest \
-e PGID=114 -e PUID=110 \
-e TZ=Australia/Perth \
-v /srv/config/plex:/config \
-v /srv/tv:/data/tvshows \
-v /srv/movies:/data/movies \
-v /srv/transcode:/transcode \
linuxserver/plex && \
docker start plex
```

Then as expected I see this in `docker logs plex`:

```
#####################################################
#   Login via the webui at http://<ip>:32400/web    #
#   and restart the docker, because there was no    #
#      plex token found in the preference file      #
#####################################################
```

So log in to the ui at 32400, and it's just endlessly "looking for servers". Per instructions I `docker restart plex`, but I just get the same notification in the logs. Preferences.xml at this point looks like this (I've edited keys):

```xml
<?xml version="1.0" encoding="utf-8"?>
<Preferences OldestPreviousVersion="1.5.5.3634-995f1dead" MachineIdentifier="17d88cc9-6a96-77128fa" ProcessedMachineIdentifier="d98ddc5816a4aab" AnonymousMachineIdentifier="5ba361f7-7e0ba2f" MetricsEpoch="1" GracenoteUser="WEcxA40X63gRoRs4Ix2qWnxyPD8Z49yezVu8Tnf07N0iHl9a+9nUVq39A2E+iDweNyUA9meI0yC4DhtuXTy38YlxprRFrwpmOUdjhEVdE63RZQyBwLQ5ZqtA7gV0GYXuYO9xSxm7CeNw+I/QE3XPjXTR"/>
```

if I execute `ps -aef |grep 'plexmediaserver'` on the server, output includes this:

`abc        272   263  2 14:46 ?        00:00:28 /usr/lib/plexmediaserver/Plex Media Server`

So I don't really understand why the ui at `32400/web` doesn't seem to be able to find / connect to the server backend.

`PlexMediaServer.log` doesn't seem to include any suspicious output. The last 10 or so lines are as follows.

```
Apr 30, 2017 15:09:05.539 [0x7f78a87ff700] DEBUG - Reading 148 bytes in the body, code is 200
Apr 30, 2017 15:09:05.539 [0x7f78a87ff700] DEBUG - [com.plexapp.agents.imdb] Plug-in running on port 57217.
Apr 30, 2017 15:09:05.540 [0x7f78a87ff700] DEBUG - Read configuration for [com.plexapp.agents.imdb], had 0 prefixes
Apr 30, 2017 15:09:05.608 [0x7f78a87ff700] DEBUG - [com.plexapp.agents.imdb] Sending command over HTTP (GET): /:/plugins/com.plexapp.agents.imdb/prefs
Apr 30, 2017 15:09:05.608 [0x7f78a87ff700] DEBUG - HTTP requesting GET http://127.0.0.1:57217/:/plugins/com.plexapp.agents.imdb/prefs
Apr 30, 2017 15:09:05.634 [0x7f78a87ff700] DEBUG - HTTP 200 response from GET http://127.0.0.1:57217/:/plugins/com.plexapp.agents.imdb/prefs
Apr 30, 2017 15:09:05.634 [0x7f78a87ff700] DEBUG - [com.plexapp.agents.imdb] HTTP reply status 200, with 2345 bytes of content.
Apr 30, 2017 15:09:05.634 [0x7f78a87ff700] DEBUG - Caching document http://127.0.0.1:32400/:/plugins/com.plexapp.agents.imdb/prefs as bf1bfc5622b4356c7f44ced8cdf69d934adf09c3
Apr 30, 2017 15:09:05.635 [0x7f78a87ff700] DEBUG - IVA: Downloading trailer lists.
Apr 30, 2017 15:09:07.176 [0x7f78bc3ff700] DEBUG - Device: ubuntu docker x86_64
Apr 30, 2017 15:09:07.177 [0x7f78bc3ff700] DEBUG - HTTP requesting POST http://www.google-analytics.com/collect
Apr 30, 2017 15:09:07.390 [0x7f78bc3ff700] DEBUG - HTTP 200 response from POST http://www.google-analytics.com/collect
Apr 30, 2017 15:09:07.391 [0x7f78bc3ff700] DEBUG - Sent analytics request: 200
Apr 30, 2017 15:09:12.429 [0x7f78b8bff700] DEBUG - MediaGrabber: Discovering and refreshing devices.
Apr 30, 2017 15:09:12.430 [0x7f78b8bff700] DEBUG - MediaGrabber: HDHomerun discovered 0 compatible devices.
Apr 30, 2017 15:09:12.430 [0x7f78b8bff700] DEBUG - MediaGrabber: Mystery discovered 0 compatible devices.
Apr 30, 2017 15:09:12.430 [0x7f78b8bff700] DEBUG - HTTP requesting POST http://127.0.0.1:32600/devices/discover
Apr 30, 2017 15:09:14.844 [0x7f78b8bff700] DEBUG - HTTP 200 response from POST http://127.0.0.1:32600/devices/discover

```
	
Other info:
Running Debian 7 as host OS, no symlinks in the `/srv` mounts listed in the create command.

**Comment by leviwheatcroft** [comment]
Still haven't had any luck. The last few lines of `docker logs --tail 100 plex` are 

```
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for 2a01:4f8:150:4342::2 on eth0.*.
Registering new address record for 166.7.23.75 on eth0.IPv4.
Server startup complete. Host name is rocko.local. Local service cookie is 924789063.
```

I've obfuscated the IP addresses, but the addresses shown there aren't familiar, as in they're not the ip address(es) of the host. Also, `Host name is rocko.local` looks odd to me. I have no idea by I'd have expected it to either, bind to host's external IP, or 0.0.0.0, or localhost.

**Comment by SentientLaboratories** [comment]
Hey leviwheatcroft,
I believe I've encountered the issue you're having before. Try going to the following: `http://<ip>/web/index.html`. For whatever reason plex does not always redirect you.

**Comment by leviwheatcroft** [comment]
thanks will give it a shot.

**Comment by skaramicke** [comment]
I think I had a related issue. I have a plex server running already, and all I could see when going to http://<ip>/web/index.html was the old server interface. I quadruple verified that I was on the new installation IP.

I couldn't get to the setup wizard for the new installation no matter how I tried.

I finally fixed it by grabbing my user token from the old installation and added it to the Preferences.xml file manually. Before I did that, it didn't show up anywhere in the plex UI, no matter which of the two local servers, nor the plex.tv address, I was using.

**Comment by mbabauer** [comment]
Did anyone ever find a solution to this problem?  My plex container is running, but I can't seem to connect via the web ui on port 32400.

**Comment by aptalca** [comment]
That usually happens if you're setting up a fresh server and you're trying to connect to the setup wizard from a different subnet. The wizard only allows connection from the same subnet by default. There may be ways to get around it by modifying the preferences.xml (allowed networks or something like that)

I have that issue when I try to set up a new plex server while connected through a vpn. In that case, I remote desktop into a machine that is on the same subnet and do the wizard from there

**Comment by mbabauer** [comment]
@aptalca Now it seems like it's not even listening on 32400.  I am not sure what changed since yesterday, but now when I try to hit the web ui I get an immediate `ERR_EMPTY_RESPONSE`, both from the server directly and from my laptop.  Yesterday it was acting like it was trying to connect then would time out.

Looking at the logs, I don't see any errors.  In fact, it looks to me like things are up and running.  I just can't access the web ui.

**Comment by aptalca** [comment]
Is your config folder on a mounted drive or a remote location?

Sqlite in docker does not like being on a remote location

**Comment by mbabauer** [comment]
The config folder is mapped to /etc/plex (/private/etc/plex since it's Mac OS).  My media is all on NFS mounted volumes, though.  Does that matter?

**Comment by aptalca** [comment]
Media on mounted volume is fine. It's sqlite that causes issues.

But, you're on mac, docker on mac is a whole different animal that we have no experience with.

All I know is, docker on mac runs in a virtual machine. In bridge mode, single ports are forwarded, but in host mode, ports aren't forwarded to the host. You may have to find the ip address for that docker vm and use that to connect on port 32400

**Comment by leviwheatcroft** [comment]
#60 has more info about the plex token, but I've still never gotten it to work.

**Comment by aptalca** [comment]
@leviwheatcroft interesting that you're getting a weird hostname rocko.local. Plex in my container gets the hostname of the host. I wonder if it is a custom docker network (with a random name) and the ports aren't really exposed on the host

Check `docker inspect plex`

**Comment by leviwheatcroft** [comment]
@aptalca sorry mate, I was playing around with that system a year ago. In the end I just installed plexmediaserver directly on the host. So I can't really test that output anymore.

I just got a new hetzner server the other day which is destined for some docker magic so I'll see whether I run into this again

**Comment by nemchik** [comment]
Any chance we could get an env var like the official Plex image has `PLEX_TOKEN` ?

**Comment by IronicBadger** [comment]
Looks like we already support this...

https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/50-plex-update#L69

Just need to update the docs to reflect it.

**Comment by nemchik** [comment]
@IronicBadger after some re-reading I see https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/60-plex-update#L79 (new location of the link you posted above) shows a variable named `PLEX_TOKEN` like you pointed out. Unfortunately in my last comment I inaccurately referenced `PLEX_TOKEN` when in reality I was thinking of the variable available on the official image `PLEX_CLAIM` which is often referred to as the claim token which is where my mixup came from. It is used by the plex image here https://github.com/plexinc/pms-docker/blob/0ac6c01ef409fef3e18c2d30021a93042acb14ad/root/etc/cont-init.d/40-plex-first-run#L103-L114 (the first and last line) and this is the only place they seem to have it in their repo currently. It is used to get the actual `PLEX_TOKEN` on the first run of the server, thus circumventing the need for putting the container in host mode in order to claim the server on the first run.
