### ISSUE TITLE
Docker PLEX with NAS

### ISSUE THREAD

**Issue by luis4ndre** [linuxserver/docker-plex#101]
Hi,
I would to know if is possible use a NAS with this container?
If yes, how?

Thanks.

**Comment by j0nnymoe** [comment]
Hi,
If it supports docker, then yes.

**Comment by lonix** [comment]
And if it has x86/64 CPU
fre. 5. mai 2017 kl. 17.00 skrev j0nnymoe <notifications@github.com>:
