### ISSUE TITLE
Add support for ALLOWED_NETWORKS and ADVERTISE_IP

### ISSUE THREAD

**Issue by danbo** [linuxserver/docker-plex#102]
From https://github.com/plexinc/pms-docker/blob/master/README.md

ADVERTISE_IP This variable defines the additional IPs on which the server may be be found. For example: http://10.1.1.23:32400. This adds to the list where the server advertises that it can be found. This is only needed in Bridge Networking.

ALLOWED_NETWORKS IP/netmask entries which allow access to the server without requiring authorization. We recommend you set this only if you do not sign in your server. For example 192.168.1.0/24,172.16.0.0/16 will allow access to the entire 192.168.1.x range and the 172.16.x.x range. Note: If you are using Bridge networking, then localhost will appear to plex as coming from the docker networking gateway which is often 172.16.0.1.

--

I tried to do this by pulling the relevant code from https://github.com/plexinc/pms-docker/blob/master/root/etc/cont-init.d/40-plex-first-run but it when adding the pull of the xmlstartlet package into the docker file, I got this 

```
/bin/sh: 1: xmlstarlet: not found
The command '/bin/sh -c apt-get update &&  apt-get install -y   avahi-daemon    dbus    wget &&         xmlstarlet &&  curl -o  /tmp/plexmediaserver.deb -L     "${PLEX_INSTALL}" &&  dpkg -i /tmp/plexmediaserver.deb &&  usermod -d /app abc &&  apt-get clean &&  rm -rf  /etc/default/plexmediaserver    /tmp/*  /var/lib/apt/lists/*    /var/tmp/*' returned a non-zero code: 127
```

.. and wasn't sure why the xmlstartlet package is not available as it is in vanilla xenial: https://packages.ubuntu.com/xenial/xmlstarlet

Perhaps lsiobase/xenial needs to be modified which I'm not sure I can do.

**Comment by aaomidi** [comment]
This is important.

**Comment by IronicBadger** [comment]
So why is this needed? I have always just forwarded port `32400` to my docker host and it just works.

**Comment by nemchik** [comment]
Both of those settings can be defined from inside the settings of plex after connecting and to my knowledge are not required for claiming the server. It would be more of a convenience factor (if anything) to be able to set those using environment variables.

The official Plex image does have those environment variables available which is probably why this request was made.

**Comment by thelamer** [comment]
We as an organization need to decide if we are going to take the plunge into creating config files for Plex. 

Users in this thread need to understand that the official Plex image is a result of their ops and dev team working together to release a functional image. It would be difficult for us to include config generation logic that would stay perfectly in sync. But it does seem like they have settled on something pretty static as it has not changed for years. 

All it really takes to add all of this functionality is copying over their bash init logic that generates their config files by env variables.

**Comment by james-d-elliott** [comment]
I think if you were to do the config file generation and are worried about those factors the best solution is to have them as completely optional and in their own section in the documentation. 

For reference this is where ADVERTISE_IP is set (only on first run): https://github.com/plexinc/pms-docker/blob/master/root/etc/cont-init.d/40-plex-first-run

**Comment by aptalca** [comment]
I'm not in favor of modifying or generating the Plex preferences file for the reasons mentioned above. I agree that the Plex claim token is useful where host networking is not possible for initial claim. However, the advertise ip variable can be set in the gui once accessed. The user can also manually modify the plex preferences file to change that once the container is up.

I'll do some local testing to see if i can come up with a different way

**Comment by nemchik** [comment]
@aptalca since this issue is not specifically about the claim token would it be beneficial to open a separate issue to discuss the merits of having the plex claim token added as an environment variable in the way that pms official has it (or similar)?

It's been lightly discussed in a few previously closed issues ( #164 #100 ) and a few other issues have mentioned the process of claiming the server and using host mode and ssh tunneling, but did not directly discuss adding the variable and the two that did had no conclusion to the discussion.

**Comment by remus-selea** [comment]
> Both of those settings can be defined from inside the settings of plex after connecting and to my knowledge are not required for claiming the server. It would be more of a convenience factor (if anything) to be able to set those using environment variables.
> 
> The official Plex image does have those environment variables available which is probably why this request was made.

Could you please point out where these settings can be found? Thank you

**Comment by remus-selea** [comment]
This setting now requires purchasing Plex Pass.
https://support.plex.tv/articles/200430283-network/
