### ISSUE TITLE
PlexPass version not downloading

### ISSUE THREAD

**Issue by 1activegeek** [linuxserver/docker-plex#105]
Docker container, running on Debian based host (OpenMediaVault)
 
Nothing special, setup via plugin UI

Log Output:
```
-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing...
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing...
Atempting to upgrade to:
https://downloads.plex.tv/plex-media-server/%20/plexmediaserver_%20_amd64.deb:
2017-06-10 14:50:18 ERROR 404: Not Found.



########################################################
# Upgrade attempt failed, this could be because either #
# plex update site is down, local network issues, or   #
# you were trying to get a version that simply doesn't #
# exist, check over the VERSION variable thoroughly &  #
# correct it or try again later.                       #
########################################################


[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
```

It will start, but continues to hit an error trying to get the download of the plexpass version. Not sure if there is an issue with the URL? Taking a look at official PMS version, they are doing plex.tv/downloads/ vs here is downloads.plex.tv/ - just a shot in the dark here as I can't fully pick apart a major issue between their official and yours.

**Comment by 1activegeek** [comment]
Sorry I just realized today now that the PlexPass version is actually pulled from downloads.plex.tv. What it seems is actually causing an error though here, is that it's putting in %20 when it should be identifying a version # to sub in to the naming convention.

**Comment by aptalca** [comment]
What did you set the `VERSION` parameter to? A space?
Either set it to latest, a specific version (~20 digits) or don't set it at all.

**Comment by 1activegeek** [comment]
Version variable is set to latest. I set it manually to the current PP version (1.7.2.3878-8088811b8), and it successfully updates to the latest running version. Set it back to latest, and again receive the same error reported.
Output from the docker inspect:
```
"Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/root",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm",
                "DEBIAN_FRONTEND=noninteractive",
                "PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server",
                "PLEX_INSTALL=https://plex.tv/downloads/latest/1?channel",
                "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support",
                "PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver",
                "PLEX_MEDIA_SERVER_INFO_DEVICE=docker",
                "PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6",
                "PLEX_MEDIA_SERVER_USER=abc",
                "PUID=1001",
                "PGID=100",
                "VERSION=latest"
```
And a screenshot from the configuration inside OMV (though this shouldn't matter as you can see from the inspect, the ENV variable is set correctly.
![screen shot 2017-06-12 at 11 23 23 am](https://user-images.githubusercontent.com/6810720/27041318-a5bcceee-4f61-11e7-8240-6b7bc07af0fd.png)

Please let me know what else can help in isolating this issue.

**Comment by aptalca** [comment]
It seems the issue is one of your parameters is incomplete. Specifically this line: `"PLEX_INSTALL=https://plex.tv/downloads/latest/1?channel",`
It really should be: 
`"PLEX_INSTALL=https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu",`

That address is responsible for retrieving the version number of the latest plex version (combined with the plex token, it retrieves the latest plexpass version). Your address is incomplete and that's why it is not retrieving the correct version.

That variable is normally set within the docker image, so I don't know why it is incomplete for you. Did you perhaps reset that variable in your run command?

How did you create the container? Can you provide a little more info on what settings, paremeter, etc. you used?

**Comment by 1activegeek** [comment]
Interesting. I do see this issue now. So it looks like there may be something wrong with how the OMV plugin is creating the container. I hadn't modified this myself, but if I drop down to CLI and manually enter in a docker run command with the same container, it does in fact have the extended install attribute listed. If I create a new fresh container through the OMV install, it is cutting off the other end.

I will dig into this further then with the OMV plugin developers to see if we can identify why this is happening and get a fix. If nothing else, I'll have to start it via the command line first then control from within the OMV interface.

Thanks @aptalca for pointing me in the right direction. I'll mark this as closed for now, and open an issue on the plugin for OMV instead.
