### ISSUE TITLE
Any chance of incorporating Comskip in the container? 

### ISSUE THREAD

**Issue by 654456** [linuxserver/docker-plex#106]
With the Plex DVR would it be possible for you guys to incorporate Comskip into the docker? 

https://github.com/erikkaashoek/Comskip

**Comment by jamescochran** [comment]
Perhaps incorporating this work: https://github.com/kmcgill88/k-plex

**Comment by philjones88** [comment]
This would be cool, also adding ffmpeg/handbrake for doing converting.

I know Plex do streaming transcoding for the video but the audio is left in weird formats!

**Comment by philjones88** [comment]
I started working on borrowing the logic from `k-plex` see here, it builds https://github.com/philjones88/docker-plex/tree/comskip-work just need to start testing it.

**Comment by lonix** [comment]
I Think this is a bad idea, as it opens up for a lot of bad/hard choices down the line.

I Simply suggest creating your own local version with something like

```
FROM linuxserver/plex
ADD  <point to comskip url>
RUN <actions needed to make it work>
```

**Comment by sparklyballs** [comment]
not something we'd consider
