### ISSUE TITLE
Plex Server not updating on restart

### ISSUE THREAD

**Issue by mickeyoneil** [linuxserver/docker-plex#107]
Tried reloading container with --net and -p options but no changes.  Symlinks allow full control for everything.  

# Host OS
Ubuntu Server 16.04.2

# Command to create container.  Tried with --net=host instead of -p but same issue.
docker run -d --name plex \
-p 32400:32400 \
-p 32400:32400/udp \
-p 32469:32469 \
-p 32469:32469/udp \
-p 5353:5353/udp \
-p 1900:1900/udp \
--restart="always" \
-e VERSION=latest \
-e PUID=1000 -e PGID=1000 \
-v /etc/localtime:/etc/localtime:ro \
-v /docker/containers/plex/config:/config \
-v /docker/containers/plex/transcode:/transcode \
-v /docker/tv:/data/tvshows \
-v /docker/movies:/data/movies \
-v /docker/music:/music \
linuxserver/plex

# Symlink info
/docker/..... is symlinked on the host with PUID 1000 as the owner and chmod 777 permissions.

# Docker log output for issue
2017-06-27 11:01:09 URL:https://downloads.plex.tv/plex-media-server/1.7.4.4017-3886b5c85/plexmediaserver_1.7.4.4017-3886b5c85_amd64.deb [106646442/106646442] -> "/tmp/plexmediaserver_1.7.4.4017-3886b5c85_amd64.deb" [1]
(Reading database ... 11373 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_1.7.4.4017-3886b5c85_amd64.deb ...
/var/lib/dpkg/info/plexmediaserver.prerm: 13: /var/lib/dpkg/info/plexmediaserver.prerm: stop: not found
Unpacking plexmediaserver (1.7.4.4017-3886b5c85) over (1.5.6.3790-4613ce077) ...
Setting up plexmediaserver (1.7.4.4017-3886b5c85) ...
/var/lib/dpkg/info/plexmediaserver.postinst: 96: /var/lib/dpkg/info/plexmediaserver.postinst: udevadm: not found
dpkg: error processing package plexmediaserver (--install):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for systemd (229-4ubuntu17) ...
Errors were encountered while processing:
 plexmediaserver
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
Starting Plex Media Server.
[services.d] done.
Starting Avahi daemon
Found user 'avahi' (UID 106) and group 'avahi' (GID 107).
Successfully dropped root privileges.
avahi-daemon 0.6.32-rc starting up.
No service file found in /etc/avahi/services.

**Comment by aptalca** [comment]
Can you elaborate more?

The log shows that it updated to the latest version 1.7.4

What exactly is the issue?

**Comment by cturra** [comment]
@aptalca looks like the plex deb package is not in fact being installed. here is a snippet of the error...
```
Preparing to unpack .../plexmediaserver_1.7.4.4017-3886b5c85_amd64.deb ...
/var/lib/dpkg/info/plexmediaserver.prerm: 13: /var/lib/dpkg/info/plexmediaserver.prerm: stop: not found
Unpacking plexmediaserver (1.7.4.4017-3886b5c85) over (1.5.6.3790-4613ce077) ...
Setting up plexmediaserver (1.7.4.4017-3886b5c85) ...
/var/lib/dpkg/info/plexmediaserver.postinst: 96: /var/lib/dpkg/info/plexmediaserver.postinst: udevadm: not found
dpkg: error processing package plexmediaserver (--install):
subprocess installed post-installation script returned error exit status 127
```

**Comment by aptalca** [comment]
It's just the post-install script failing (setting up service files for start on boot I assume). But that is not needed in this image anyway, as it is managed by the s6 supervisor.

That error is harmless and is expected. I have the same error in my log, but plex is installed and working fine.

**Comment by aptalca** [comment]
deeper look into the script shows udevadm is used for usb device support?!?

either way, the error is harmless

**Comment by ryanneufeld** [comment]
It's not harmless, it causes a non-exit 0 status, which means any form of automation around updating the package will fail, or require parsing of the error message.

It may not mean it's broken, but it does mean it's not a clean install.
````
if [ -x /sbin/udevadm ]; then
        udevadm control --reload-rules
        udevadm trigger
else
        echo "Unable to find executable 'udevadm'";
fi
````

Adding that to the postinstall script should fix it.

**Comment by aptalca** [comment]
1. There is no automation around updating the package, there is no repo. Image contains a static package (latest public). We run our own script to pull the latest plexpass and install it on top if necessary. Just to test, I installed an older version on top of the latest one that exited non-zero. No problems there.

2. Post install script is included in the plex package and is therefore not under our control

3. Although we are looking into fixing the "harmless" error, this issue is about @mickeyoneil not being able to update his plex version, which has nothing to do with the post install script. If you'd like to argue further, please open a new ticket.

**Comment by mickeyoneil** [comment]
The first attempt to install definitely failed but had the same error message.  Plex reported the same version as before.  Was 1.7.3... at the time so I removed the container and re-added thinking maybe it was something in that.  I guess the initial image contains Plex 1.5.6.  This image did in fact upgrade but it had not in the previous reboot giving the same error messages.  Maybe I didn't need to make an issue ticket regarding this but thought as a sys admin this type of message is confusing and agree that anything other than an exit status of 0 can be misleading however when I upgraded Plex on ubuntu sever in the past, pre-docker, I never received anything but an exit status of 0.  Thank you for taking at look at it though.  Love using your containers!

**Comment by aptalca** [comment]
Keep in mind that plexpass releases are beta. And this post install script contains some new code that is in preparation for new features that are not implemented yet (such as setting /dev/dri permissions for hw transcoding).

Glad to see it is working for you now. Closing this.
