### ISSUE TITLE
90_chown_plex_owned_files.sh

### ISSUE THREAD

**Issue by ljm42** [linuxserver/docker-plex#11]
Recent versions of 90_chown_plex_owned_files.sh have changed from:
>  chown abc:abc

to 
>  chown abc:root

is that correct?  Shouldn't everything be owned by the PGID that is passed in to the docker?

**Comment by lonix** [comment]
No, That is correct, at least untill we learn why plex insist on saveing things as abc:root

**Comment by ljm42** [comment]
Ah, thanks!  I didn't see any comments about it so I thought it might have been a mistake.  Appreciate the info!
