### ISSUE TITLE
RAR support for libraries?

### ISSUE THREAD

**Issue by niXta1** [linuxserver/docker-plex#111]
Hi!

Would it be possible to add rar support though rar2fs or some other way to plex?

**Comment by EugenMayer** [comment]
@niXta1 this is not the support of plex the software, its just and docker image of plex - you should close this issue and open it in the plex forums

**Comment by niXta1** [comment]
@EugenMayer rar2fs isn't developed by Plex, its just a software layer providing rar support for programs or systems without it. 
For example it can be integrated in a docker container (such as this) to provide rar support to programs without native support (such as Plex).
Plex official answer is to use rar2fs.

**Comment by EugenMayer** [comment]
@niXta1 in this case, i would actually discourage linuxserver/plex adding anything else then the core distribution. 

There is no reason to actually make your own image (derived from this one ) or for linuxserver to provide linuxserver/plex-extras adding DVR, rar2fs and so on. I bet, if you create an image and ask them if they want to officially add it, and you be the maintainer, they probably do that. But maintaining a gazzilion 3rd party integrations will just be out of scope for the guys here, i would suppose

**Comment by niXta1** [comment]
Sure, it can be done with a separate container. So can unrar, and other components in this container. It already has packages that’s outside of the “core distrubition”. People seem to like the all in one solution.
