### ISSUE TITLE
Ignoring veth* interfaces

### ISSUE THREAD

**Issue by Dids** [linuxserver/docker-plex#115]
Running this image using host networking causes Plex to pickup all interfaces on the host, including weave/virtual Docker NICs. Is there any way to ignore or blacklist them?

I'm not entirely sure, but I believe this is causing some performance issues for me every now and then, where Plex becomes unresponsive for a few minutes, almost like it's suddenly restarting, but there's nothing in the logs.

**Comment by aptalca** [comment]
Do you have any evidence linking the host networking to plex being unresponsive? 

I've been running it in host net for a long time, have a fairly big library and a bunch of external and internal users streaming and never experienced plex being unresponsive

**Comment by Dids** [comment]
Entirely guessing at this point and only brought it up due to the sheer amount of interfaces being picked up.

If it's not related to this, then it's most likely something with my storage setup. My host is mounting NFS shares, which Docker is mounting as volumes. Additionally the entire host VM is running through iSCSI, so it could be congestion, but I doubt it as I'm utilizing multiple 1Gbps NICs.

**Comment by aptalca** [comment]
It could very well be nfs related. Docker is known to not play that well with mounted shares.

It could also be a plugin on plex server causing issues. Did you check the plex server log as well as the docker log?

I've had issues with btrfs raid 0 having really high disk io during unrar and par repairs. Docker containers would be unresponsive during that time and the server would be semi stalled.

But I doubt it would be interface related. Plex would just be listening on them, but there should be no traffic on the other interfaces.

**Comment by Dids** [comment]
Just checked the logs, but couldn't find anything odd, apart from lines like these:
```
HTTP error requesting GET http://127.0.0.1:32600/devices/compound_device085dvb%23v4l%23%2fsys%2fdevices%2fpci0000%3a00%2f0000%3a00%3a17.0%2f0000%3a13%3a00.0%2fusb1%2f1-2%2f1-2%3a1.0%3a0013908424 (0, No error) (Failed connect to 127.0.0.1:32600; Connection refused)
ERROR - [PlexRelay] kex protocol error: type 7 seq 11
ERROR - JobManager: child process returned: 255 (Unknown error 255)
```

Not using any plugins, and it's only happening occasionally, right when starting playback (or pausing, then trying to play). Might be related to transcoding too, although it's doing that on a local SSD.

**Comment by Dids** [comment]
Okay, just had it happen again, so got the logs from it:
```
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Asked for segment 63 from session.
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - We're in a seek: asked for 63, min/max available was 0/18
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Segment #63 WON.
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Killing job.
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Signalling job ID 2591 with 9
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Job was already killed, not killing again.
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Stopping transcode session cp3hixh4e68ynl9emb7pizcb
Aug 31, 2017 21:46:13.802 [0x7fcea47fa700] DEBUG - Starting a transcode session cp3hixh4e68ynl9emb7pizcb at offset 630.0 (state=3)

...

Aug 31, 2017 21:46:14.323 [0x7fceb23ff700] DEBUG - Play progress on 416 'Sold' - got played 641750 ms by account 1!
Aug 31, 2017 21:46:58.898 [0x7fcea47fa700] WARN - NAT: PMP, got an error: Not Supported by gateway.
Aug 31, 2017 21:47:10.313 [0x7fcea2ff7700] DEBUG - BPQ: onConsiderProcessing: Idle (true)
Aug 31, 2017 21:47:10.314 [0x7fcea2ff7700] DEBUG - BPQ: [Idle] -> [Processing]
Aug 31, 2017 21:47:13.475 [0x7fceb4bfe700] DEBUG - EventSource: Failure in IdleTimeout (0 - Success).
Aug 31, 2017 21:47:13.475 [0x7fceb4bfe700] DEBUG - MyPlex: We appear to have lost Internet connectivity, resetting device URL cache.
Aug 31, 2017 21:47:13.475 [0x7fceb4bfe700] ERROR - EventSource: Retrying in 15 seconds.

...

Aug 31, 2017 21:47:13.476 [0x7fceb4bfe700] DEBUG - Failed to stream media, client probably disconnected: 32 - Broken pipe
```

**Comment by Dids** [comment]
The issue hasn't resurfaced for a few days now, even though nothing's changed, unless Plex updated and fixed it. Closing the issue regardless.
