### ISSUE TITLE
Current laste build seems to be  1.8.1.4139 

### ISSUE THREAD

**Issue by EugenMayer** [linuxserver/docker-plex#116]
Even though downloading from channel=8 manually, 1.8.3 is downloaded, when using the most recent docker image, the version ends up to be 1.8.1.4139 

Are the builds somehow broke?

I see, using docker inspect on th container, that it is the latest 86 build

```
     "Labels": {
                "build_version": "Linuxserver.io version:- 86 Build-date:- September-01-2017-22:21:39-UTC"
            },
```

so i guess we should expect 1.8.3 at least? Please warns be about the outdate version at least

**Comment by sparklyballs** [comment]
that build was made on the 4th september and our latest update to the image was on the 1st

nothing to warn about 
the version in the image is the latest version that was available at the time of build
