### ISSUE TITLE
New Build

### ISSUE THREAD

**Issue by EugenMayer** [linuxserver/docker-plex#118]
Any chance you could trigger a new build or is this image no longer as "latest" build as it has been  ( maybe out of good reasons? )

Should i derive and build my own? I actually would love to stay with you guys, you deserve the credit s all along. Great job!

**Comment by aptalca** [comment]
It is the latest public as of last night. What makes you think it isn't?

**Comment by EugenMayer** [comment]
I updated to the latest image ( today ), still https://ibb.co/fCS4O6 .. right now having **Version 1.9.2.4285**

**Comment by aptalca** [comment]
Last night's build has version 1.9.4.4325-1bf240a65

Make sure you do a docker pull first and then delete and recreate the container. Also make sure you don't have the version parameter set to a certain build number in the docker run / create command

**Comment by EugenMayer** [comment]
Interesting, while repulling on the cli ( to be sure ) did not pull anything ( i tried to pull using the synology gui beforehand - as i usually do )

```
root@nas:~# docker pull linuxserver/plex
Using default tag: latest
latest: Pulling from linuxserver/plex

Digest: sha256:ec56f59b64fd90556ca43bb2a7c00f6e51637049e4c35631e83a4a75860cb201
Status: Image is up to date for linuxserver/plex:latest
```

Still stopping / clearing the container this time was build uppon the new image ( the one you mentioned ).. so either i fked up the container recreation or i am not able to explain it.

I used the same method using the UI, stop+clear ( not cli stop + rm ).. i am actually pretty docker bulletproof, so i cannot really explain it. Anyway, not your job finding that out, the image is great, thanks!

**Comment by aptalca** [comment]
Unfortunately none of the linuxserver team members have a synology box. We asked synology for a demo/test unit so we could provide support, but they weren't really interested.

We don't really know how their interface works when it comes to updating and recreating containers.
