### ISSUE TITLE
VERSION options

### ISSUE THREAD

**Issue by ljm42** [linuxserver/docker-plex#12]
I like that you incorporated the `plexpass` variable into `VERSION`, but now the `latest` option doesn't really make sense, since it refers to the public version of Plex and will often *not* be the latest.

It might make sense to rename the `latest` option to `public`, so the instructions for `-e VERSION` become:

* `-e VERSION` - Set this to a full version number if you want to use a specific version e.g. `0.9.12.4.1192-9a47d21`, or set it to `public` or `plexpass`

**Comment by sparklyballs** [comment]
but it **is** the latest version if you don't have plexpass.

**Comment by ljm42** [comment]
Yeah, I just don't think it is clear right now what you get if you choose the "latest" option.  It would be a little more obvious if the options were public/plexpass or even latest_public/latest_plexpass.

The issue of "how do I get the latest version of Plex" comes up a lot in the unraid forums, not necessarily for this Docker but in general.  I was just thinking that if this could be more clear it might help people understand.

I'm not forcing the issue though, if you don't think a change is needed that is fine.

**Comment by lonix** [comment]
Very often the closed beta group is a version or two ahead of plexpass so they would technically be on the latest version ?
Latest is most commenly used for spesifiying The latest non-beta publicly avalible version. I don't think plexpass version fits that bill.

**Comment by ljm42** [comment]
Sounds good, thanks
