### ISSUE TITLE
Provide access to the plex plugin folder

### ISSUE THREAD

**Issue by RaphaelJenni** [linuxserver/docker-plex#124]
Plex has the option for plugins. For that you have to add a bundle to the plugins folder. Sadly this folder isn't accessible from outside the docker container. Please fix that.

**Comment by sparklyballs** [comment]
"/config/Library/Application Support/Plex Media Server/Plug-ins"

**Comment by RaphaelJenni** [comment]
Sorry was my fault, had an error in the docker command.
