### ISSUE TITLE
Issue running on Synology

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [linuxserver/docker-plex#126]
Hey guys,

Sorry if this is a noob question, but cannot find any answer.

I get an error message when running this container: 
```This XML file does not appear to have any style information associated with it. The document tree is shown below.```

Running on a Synology DSM 6.1. Tried various settings and installs with no luck!

Thanks for letting me know if I'm missing something...

**Comment by sparklyballs** [comment]
looks like you're missing the /web at the end of the address

**Comment by MimbaMonkeyHouse** [comment]
Yup, that was pathetic. Thanks for ringing in...
