### ISSUE TITLE
Add support for hardware transcoding

### ISSUE THREAD

**Issue by wraeuk** [linuxserver/docker-plex#127]
This one should be fairly simple.

The container's plex user needs access to the passed hardware video device (/dev/dri).
Using default settings just jumping into the container with `docker exec`, running `usermod -aG irc abc` and restarting the container makes hardware transcoding function correctly (provided all the other non container stuff is in order.)

This just needs to be done as part of the image - I don't think it deserves its own environment variable and should just be part of the default init scripts.

Edit: Just noticed there's a pull request that does `usermod -G video abc`; which I've not had the best luck with (the passed device ends up in the `irc` group for me since centOS v. bunters) but I digress, the request is the same :P
Anywho given the pull I'll close this out

**Comment by tobbenb** [comment]
As you can see from the other request, the group will change depending on the host OS. In my view this should be handled at the host level.

**Comment by wraeuk** [comment]
How though? By opening up /dev/dri to everyone?
Seems more reasonable to open it up in the docker instead (although doing chmod 777 in there still feels hacky as all get out).

**Comment by groenator** [comment]
I manage to enable HW by set the PUID and PGUID to root and mount the device /dev/dri. I tried to mount the device with different UID and GID, but without any luck. The /dev/dri it is always mounted under root account.

**Comment by wraeuk** [comment]
I've got around this by chowing the device on the host to be the Plex user. It's jank as hell (I'm doing it via a boot cron) but it means I can keep the container ephemeral and I don't run the thing as root. 

I don't like it but hey here we are. 

`@reboot chown plex /dev/dri/*`

**Comment by groenator** [comment]
Yeah, that's a not a bad idea, but then I have to run this every time I run docker-compose. I tried to add a line into the docker compose to run the command inside the container, but I didn't find the correct syntax. Eventually, I run it as root. I agree with you, having everything under root is not a good idea. 

Hopefully, they will implement the shell script that is meant to enable HW for plex. 

Thanks for the tip!

**Comment by josevh** [comment]
I like what emby has done on their docker image, they add another environment variable `GIDLIST` to which I can add the video GID. Can something like that be accomplished for this repo?

https://hub.docker.com/r/emby/embyserver/

**Comment by aptalca** [comment]
Just add whatever user the PUID is set to, to the video group on the host.

`usermod -aG video <PUIDuser>`

**Comment by wraeuk** [comment]
Except that doesn't seem to work, at least with my docker/distro combination (this is why I've gone to the janky cron @reboot that takes user ownership of the devices on the host)

**Comment by aptalca** [comment]
What is your distro? And what are the permissions on /dev/dri?

**Comment by thelamer** [comment]
I branched and PR'd a change for this a while back but it has since been deleted for some reason, here is the config file logic: 
```
#!/usr/bin/with-contenv bash

# Add UID to video group
if [ -z ${VIDEO_GID+x} ]; then
        usermod -a -G video abc
else
        # Check if the GID is taken and swap to 65533
        CURRENT=$(getent group ${VIDEO_GID} | awk -F: '{print $1}')
        if [ -z "${CURRENT}" ] || [ "${CURRENT}" == 'video' ]; then
                groupmod -g ${VIDEO_GID} video
                usermod -a -G video abc
        else
                groupmod -g 65533 ${CURRENT}
                groupmod -g ${VIDEO_GID} video
                usermod -a -G video abc
        fi
fi
```
Requires setting the VIDEO_GID as an env variable if you want to use it

**Comment by sparklyballs** [comment]
changing permissions of things at the device level is not something a docker container should be doing. 

documentation should be added to the README on how to change the permissions on the host, and not being potentially being broken via docker init files. 

on the wider issue, at least with dvb cards, it doesn't work anyway (at least locally to me) as the docker stack comes up before the device.....

**Comment by josevh** [comment]
FWIW, my observation:
In my case, the GID for the `video` group match on the host and container (44) without any changes on my end.
On the host, the uid set for `abc` via `PUID` belongs to the host's `video` group.
In the container, the `plex` user gets added to the `video` group, however, the `abc` user is not.

HW only transcoding works if I add `abc` to the `video` group within the container and restart it.

**Comment by sparklyballs** [comment]
@thelamer i'm not sure swapping out random gid to 65533 , if the group id is already taken, is advisable, or indeed if it will actually work. 

spinning up an alpine base container and entering 
`groupmod -g 65533 abc` 

at exec prompt throws up
 ```groupmod: GID '65533' already exists```

**Comment by aptalca** [comment]
A fix for setting the correct permissions was merged in the last update: https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/50-gid-video

**Comment by thelamer** [comment]
@sparklyballs this is bionic base, you are correct if we ever rebase back to alpine.
I ran this through the ringer though for example if you run something like :
```
chown -R root:33 /dev/dri/*
```
Host level in the container will result in groups like this: 
```
video:x:33:plex,abc
www-data:x:65533:
```

If you have any optimizations to https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/50-gid-video, we could use them. 
A more fool proof way might be to warn the user of the collision on specific GIDs where modifying them might result in the container not functioning.
