### ISSUE TITLE
ummmm multiple servers showing up in devices

### ISSUE THREAD

**Issue by marcus-no** [linuxserver/docker-plex#13]
This issue has emerged 2 times after restarting the container. 

Usually after a "manual" restart. (I do restarts in cron as well)

It seems the container starts up a new instance of plex mediaserver, and both the new and the old shows up in the devices list. The new one is online and accessable, but the old one is shown as offline. All users I have shared libraries with ofc can't reach the libraries, as the original server is offline.

See screenshot: https://www.dropbox.com/s/pomf3wp7oa2e4eq/plexfail.png?dl=0

Workaround for me so far: Delete the original plex server device, and re-share all libraries with users.

Command run to initiate:
docker run --restart=always --name=plex --net=host -e VERSION="plexpass" -e PUID=108 -e PGID=116 -v /etc/docker/linuxserver/plex/config:/config -v /mnt/redstore/video/series:/data/series -v /mnt/rar2fs_video/:/data/norar linuxserver/plex

in nightly cron to allways be updated to latest version (aka I'm super lazy):
m h  dom mon dow   command
0 4 * * * /usr/bin/docker restart plex

**Comment by marcus-no** [comment]
Oh, one more point: I have to enter my plex-pass credentials again as well, so it's clear that it creates a new instance.

**Comment by smdion** [comment]
talked with marcus-no in ir. he is on ubuntu 14.04

**Comment by pecigonzalo** [comment]
@marcus-no when  you say a manual restart, what command do you issue?

**Comment by marcus-no** [comment]
docker restart plex
or
docker stop plex
docker start plex

That said I'm not sure this is the reason it happens.

**Comment by marcus-no** [comment]
One more problem with this is ofc that syncing to mobile devices stops working/updating as well. If I view a synced episode, it won't be updated back to the "new" server, as it was synced from the original. A complete wipe and resync of the device is needed to get that going again.

**Comment by pecigonzalo** [comment]
Can you verify permissions on the /config directory?

**Comment by marcus-no** [comment]
They are drwxr-xr-x 3 plex plex 4.0K Oct  6 12:10 config

That would result in it making a new instance every restart(?) and it would also mean that the libraries on the local instance would not be there when connecting directly to the plex server through IP:32400/web, right? It doesn't create a new instance every time, and the libraries are accessible in the new instance right away.

**Comment by lonix** [comment]
You have a point, Marcus. But i agree with @pecigonzalo on what it looks like. Can you confirm the pressene of this file: linuxserver-chown.lock in /config/Library

IIRC The uniq id of a plex server service, is stored inside the file /config/Library/Application Support/Plex Media Server/Preferences.xml and on my system that single file has diffrent permissions than anything else.


*Crop from ls -lvh*
where rood is uid 0 and nobody is 99
```
drwxrwxrwx 5 nobody root  4.0K Sep  1 09:38 Plug-ins/
drwxrwxrwx 7 nobody root  4.0K May  9  2015 Plug-in\ Support/
-rw------- 1 nobody users 1.1K Nov 12 05:51 Preferences.xml
drwxrwxrwx 2 nobody root  4.0K May  9  2015 Scanners/
```

How does this compare to your system

**Comment by marcus-no** [comment]
drwxr-xr-x 11 plex plex 4.0K Nov 12 16:00 .
drwxr-xr-x  3 plex plex 4.0K Oct  6 12:10 ..
drwxr-xr-x  5 plex plex 4.0K Nov 12 16:51 Cache
drwxr-xr-x  2 plex plex 4.0K Nov 12 04:00 Crash Reports
drwxr-xr-x  3 plex plex 4.0K Nov 12 15:51 Logs
drwxr-xr-x  3 plex plex 4.0K Oct  6 13:03 Media
drwxr-xr-x  4 plex plex 4.0K Oct  6 20:51 Metadata
-rw-r--r--  1 plex plex    2 Nov 12 04:00 plexmediaserver.pid
drwxr-xr-x  3 plex plex 4.0K Oct  6 13:10 Plug-ins
drwxr-xr-x  7 plex plex 4.0K Oct  6 12:10 Plug-in Support
-rw-------  1 plex plex  527 Nov 12 16:00 Preferences.xml
drwxr-xr-x  2 plex plex 4.0K Oct  6 13:03 Scanners
drwxr-xr-x  3 plex plex 4.0K Oct  6 12:10 Thumbnails

**Comment by pecigonzalo** [comment]
@marcus-no permissions look ok. Im trying to replicate your issue but im not being able to do so. Can you check plex logs for any additional information?

**Comment by pecigonzalo** [comment]
No additional information was provided. Closing for now.
