### ISSUE TITLE
Timezone environment variable not reflected.

### ISSUE THREAD

**Issue by brucewillke** [linuxserver/docker-plex#137]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by brucewillke** [comment]
The -e TZ var is set in docker run but will not reflect in the running container. 
I have a PR opened to address this problem.

**Comment by tobbenb** [comment]
Not much info to go on here...

**Comment by aptalca** [comment]
It works just fine over here in edt time zone as well

**Comment by brucewillke** [comment]
Seems it's only my issue. Closing for now
