### ISSUE TITLE
Why avahi?

### ISSUE THREAD

**Issue by dmwyatt** [linuxserver/docker-plex#140]
My Googlin' leads me to believe that Plex does not require avahi as it no longer users mDNS.  I'm not an expert at Plex yet, so I might be wrong and if someone knows for sure feel free to tell me to shut up!  😃 

See, for example, this [ancient thread](https://forums.plex.tv/t/what-is-the-bonjour-service-actually-for/11394/11) where it's explained how they moved away from Bonjour.

AFAICT, Plex gave up on mDNS and moved to their own in-house developed protocol called [GDM](https://github.com/NineWorlds/serenity-android/wiki/Good-Day-Mate).

**Comment by IronicBadger** [comment]
I did not know this. Thanks, I've added it to the list for future releases.

**Comment by aptalca** [comment]
Confirmed with plex that it is no longer needed, and removed in the last update. Thanks for the heads up.
