### ISSUE TITLE
Issue with "PLEX_INSTALL" variable under Plesk Docker extension

### ISSUE THREAD

**Issue by 0xSlyxR** [linuxserver/docker-plex#141]
Host OS: Debian 9.5 + Plesk Onyx 17

Hi, unfortunately I have a problem with the Plex Docker. I'm using it with the Pesk Docker extension, but every time I try to set the variable for "PLEX_INSTALL" Plesk gives me the error "The value of an environment variable cannot contain the '=' (equal) sign." The variable for PLEX_INSTALL should contain the URL "https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu" which he forbids me because of the = sign. Everything else works perfectly.

[Screenshot](https://i.imgur.com/6MufNyC.png)

Hopefully there will be a simple fix or workaround.

Greetings Sly

**Comment by homerr** [comment]
We don't support the use of `PLEX_INSTALL` as an environment variable. If you're after a specific version then use the `VERSION` variable as documented here:

https://github.com/linuxserver/docker-plex

As a side note if you're passing a variable with `=`'s in it then you'll need to escape it by putting it in quotes such as `MY_VARIABLE="moo=nota=sheep"`
