### ISSUE TITLE
Adjust LD_LIBRARY_PATH for future updates of PMS

### ISSUE THREAD

**Issue by tru** [linuxserver/docker-plex#148]
Hello, Tobias from the Plex Media Server team here. Just wanted to give you a heads up on a upcoming change to the Plex Media Server that's going to roll out in version 1.15.0 of PMS. We have relocated the support libraries of PMS into a `lib` subfolder and this needs to be added to the `LD_LIBRARY_PATH` for PMS to start up correctly. We adjusted this in our official docker image here: https://github.com/plexinc/pms-docker/commit/0e81f12e599d83db99b7d2bd1c94b1a29088b2e7

The ETA of 1.15.0 is that it goes into beta before the end of the month - so I encourage you guys to do this change and get it rolled out as soon as possible.

Thanks,
Tobias and the PMS team.

**Comment by tobbenb** [comment]
Hi Tobias. Thanks for the heads up. Appreciate it very much.
