### ISSUE TITLE
Issue while updating to the latest version of plex

### ISSUE THREAD

**Issue by Datapotomus** [linuxserver/docker-plex#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Unraid 6.6.6

```
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing...
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing...
Atempting to upgrade to: 1.15.0.647-67e950f12
https://downloads.plex.tv/plex-media-server/1.15.0.647-67e950f12/plexmediaserver_1.15.0.647-67e950f12_amd64.deb:
2019-02-06 09:57:51 ERROR 404: Not Found.

########################################################
# Upgrade attempt failed, this could be because either #

# plex update site is down, local network issues, or #
# you were trying to get a version that simply doesn't #

# exist, check over the VERSION variable thoroughly & #

# correct it or try again later. #
########################################################


[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
```

Running into an issue when attempting to update. Seems that the 1.15 version doesn't exsist. Which via the link it doesn't, but via the "latest" URL it does. Wondering if it's a better option to use 
[https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu](https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu)
to pull the downloads.

**Comment by udochrist** [comment]
Plex have changed their repo layout. i think you need to change the d/l script.
See https://forums.plex.tv/t/latest-version-from-6-feb-not-found-by-linuxserver-docker/372313

**Comment by Datapotomus** [comment]
Got fixed with the latest pull.

**Comment by j0nnymoe** [comment]
Glad it's working :)
