### ISSUE TITLE
No media being found

### ISSUE THREAD

**Issue by Sivivatu** [linuxserver/docker-plex#158]
I have setup a docker image via Portainer (running RancherOS host on top of FreeNAS)	
asfaik the plex user has ownership of the /mnt/emperor/Docker/Media where the media is stored but I'm unable to further identify a fix (pretty new to docker, freenas and linux so apologies)

Help in diagnosing this would be appreciated (if this is the wrong place to post this issue please point me in the right direction).

![image](https://user-images.githubusercontent.com/7496456/53097870-53a11c00-351a-11e9-93c2-d04b702e34fb.png)

**Comment by aptalca** [comment]
Do `ls -al /mnt/emperor/Docker/Media/Movies` and make sure they are owned by the 1001 user.

In Plex, did you add the movie library path as /data/movies ?

**Comment by Sivivatu** [comment]
ls output below (user 1001= plex, group 1001=plex)
![image](https://user-images.githubusercontent.com/7496456/53101202-37ed4400-3521-11e9-809b-ddbca217fd90.png)

in Plex folder targeted to correct folder:
![image](https://user-images.githubusercontent.com/7496456/53101303-5fdca780-3521-11e9-845e-836b7a6fbbff.png)

**Comment by aptalca** [comment]
GUID should be PGID in plex settings but the PUID seems correct so that shouldn't be the issue.

When you browse to /data/movies in plex, after you enter that folder, does it list the media folders underneath?

or you can try `docker exec -it plex ls -al /data/movies` and see if they are owned by user `abc` inside the container and that they are visible

**Comment by Sivivatu** [comment]
> GUID should be PGID in plex settings but the PUID seems correct so that shouldn't be the issue.
>
what is the PGID? I understood that to be the user group. is that a different user that I should be setting?

> When you browse to /data/movies in plex, after you enter that folder, does it list the media folders underneath?
> 
When browse to the movies folder in the settings page (as in the image) none of the sub folders are seen

> or you can try `docker exec -it plex ls -al /data/movies` and see if they are owned by user `abc` inside the container and that they are visible

If I run the above command nothing seems to appear (see image) not sure if running the command from the correct location tho, ran it from the RancherOS CLI. 

![image](https://user-images.githubusercontent.com/7496456/53102565-dc708580-3523-11e9-90ae-bf6cf799811a.png)

**Comment by aptalca** [comment]
wait you have 3 levels there? freenas, rancheros and docker?

your freenas paths are likely not recognized in rancheros, that's your issue

**Comment by aptalca** [comment]
our image does not recognize `GUID` as a valid environment variable. It expects `PGID`

**Comment by Sivivatu** [comment]
> wait you have 3 levels there? freenas, rancheros and docker?
> 
> your freenas paths are likely not recognized in rancheros, that's your issue
> 
> docker is mapping folders between rancheros and the container

Right I may be doing this in a rather convoluted manner which is part of the problem then.
If this is the case then I need to work out how to map the FreeNAS folders into Rancher so it gets recognised by the docker image.
Will search this and see how to fix that.

Thanks

**Comment by Sivivatu** [comment]
Ok so I have got the rancherOS seeing the media files as expected, however, they are still not appearing in plex (ie the docker container doesnt appear to be seeing the files). it appears that all the files are owned by the `root` user rather than `abc`. How do I go about confirming this and transfering ownership to `abc`

**Comment by aptalca** [comment]
Make sure the files are owned by anything but root, then use that PUID in plex docker run
ie. `chown -R 1001:1001 /datafiles`

**Comment by homerr** [comment]
Closing this, if the issue persists, reopen.
