### ISSUE TITLE
Plex changed URL for downloads

### ISSUE THREAD

**Issue by AevumDecessus** [linuxserver/docker-plex#159]
The newest plex-pass version of plex has a new URL for downloading the .deb file.

https://downloads.plex.tv/plex-media-server-new/1.15.1.707-d893009fb/debian/plexmediaserver_1.15.1.707-d893009fb_amd64.deb

whereas the plex container is trying to download

https://downloads.plex.tv/plex-media-server/1.15.1.707-d893009fb/debian/plexmediaserver_1.15.1.707-d893009fb_amd64.deb

**Comment by tobbenb** [comment]
It looks like you didn't update your container.


`-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
Atempting to upgrade to: 1.15.1.707-d893009fb
2019-02-23 17:25:54 URL:https://downloads.plex.tv/plex-media-server-new/1.15.1.707-d893009fb/debian/plexmediaserver_1.15.1.707-d893009fb_amd64.deb [81258864/81258864] -> "/tmp/plexmediaserver_1.15.1.707-d893009fb_amd64.deb" [1]
(Reading database ... 10486 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_1.15.1.707-d893009fb_amd64.deb ...
Unpacking plexmediaserver (1.15.1.707-d893009fb) over (1.14.1.5488-cc260c476) ...
Unpacking plexmediaserver (1.15.1.707-d893009fb) over (1.14.1.5488-cc260c476) ...
Setting up plexmediaserver (1.15.1.707-d893009fb) ...
Installing new version of config file /etc/init/plexmediaserver.conf ...

Processing triggers for libc-bin (2.27-3ubuntu1) ...
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.`
