### ISSUE TITLE
Curl command to find plex version fails on reboot

### ISSUE THREAD

**Issue by dmp1ce** [linuxserver/docker-plex#16]
When I have restart always set and I reboot the server, on restart, the container cannot find the  downloads.plex.tv server. It says this in my logs over and over again.

If I do a `docker restart` then it downloads fine. If I `docker exec` into the container, I can ping downloads.plex.tv just fine.

``` bash
--2015-12-25 07:14:29--  https://downloads.plex.tv/plex-media-server//plexmediaserver__amd64.deb
Resolving downloads.plex.tv (downloads.plex.tv)... 2400:cb00:2048:1::6814:609, 2400:cb00:2048:1::6814:709, 104.20.6.9, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|2400:cb00:2048:1::6814:609|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-25 07:14:29 ERROR 404: Not Found.
--2015-12-25 07:14:29--  https://downloads.plex.tv/plex-media-server//plexmediaserver__amd64.deb
Resolving downloads.plex.tv (downloads.plex.tv)... 2400:cb00:2048:1::6814:709, 2400:cb00:2048:1::6814:609, 104.20.7.9, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|2400:cb00:2048:1::6814:709|:443... connected.
```

**Comment by dmp1ce** [comment]
I'm thinking that curl is failing on line 10 of 30_update_plex.sh. Maybe my networking isn't full booted when it tries to use curl. Is there an easy way I can delay the update process a couple of seconds?

**Comment by dmp1ce** [comment]
A workaround for me was to add this to my `docker-compose.yml` file: `command: "bash -c 'sleep 5 && /sbin/my_init'"`. Other people might be having this problem too. It might be worth checking to see if curl succeeds before moving on in the script.

**Comment by lonix** [comment]
I Submitted a fix here. Should be confirmed and added.

**Comment by Rafkat** [comment]
Unfortunately, the fix doesn't fix it for me. Can you advise if there is something else needs to be done?

Thanks.

**Comment by dmp1ce** [comment]
It seemed to work for me. I'll update the issue if I have problems.
