### ISSUE TITLE
Hangs while executing 10-adduser.sh

### ISSUE THREAD

**Issue by Artiume** [linuxserver/docker-plex#160]
made a change to the add user script universally that **_hopefully_** may resolve this issue.

going to close this, if issue is still present then suggest users open new issue.

_Originally posted by @sparklyballs in https://github.com/linuxserver/docker-plex/issues/45#issuecomment-261774304_

Opening a new issue since I am having this issue. 

usermod command hangs and I have to console into the container and kill the process to allow the container to continue its startup process. 

I'm having this issue happen to me on an odroid hc-2 running Ubuntu 18.04.2 LTS (4.14.94-155 armv7l) with the build lsioarmhf/plex:latest, it should be build 144, not sure how to check.

Docker version 18.09.2 (swarm mode)

docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:50 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:01:13 2019
  OS/Arch:          linux/arm
  Experimental:     false

docker logs:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,

It will hang on this script which lead me to the original ticket.
removing env var - PUID: 1000 allows the container to successfully build (or consoling in and killing the usermod process works.)

**Comment by homerr** [comment]
Recreate the container from linuxserver/plex - we have gone multiarch on these builds now and lsioarmhf/plex is no longer maintained (as it's available under linuxserver/plex)

See how you get on with a fresh build before we go any further.

**Comment by Artiume** [comment]
Hi Homer,

I have updated to the proper image. This specific issue is no longer a a problem so we can close this ticket. I am having issues with the new image but it is properly due to my setup so I need to troubleshoot it first.

Can you make a note that lsiomarmhf/plex's github page and the image itself do not say that it is deprecated. I had already moved most of my images to the main linuxserver except for plex because I had assumed the main image still didn't support arm yet. 

Thanks again for your time :)
