### ISSUE TITLE
Can't update to 1.15 with -e LD_LIBRARY_PATH=/usr/lib/plexmediaserver

### ISSUE THREAD

**Issue by ceptonit** [linuxserver/docker-plex#163]
To be able to access Plex Media Scanner with `docker exec plex /usr/lib/plexmediaserver/Plex\ Media\ Scanner --scan`, I've added `-e LD_LIBRARY_PATH=/usr/lib/plexmediaserver` to docker create:
```
docker create \
 --name=plex \
 --restart unless-stopped \
 --net=host \
 -e VERSION=latest \
 -e PUID=1000 \
 -e PGID=1000 \
 -e TZ=MST \
 -e LD_LIBRARY_PATH=/usr/lib/plexmediaserver \
 -v /mnt/data_ssd/docker_data/plex:/config \
 -v /mnt/data_ssd/mounts/union/tv:/data/tvshows \
 -v /mnt/data_ssd/mounts/union/movies:/data/movies \
 linuxserver/plex
```
But now, Plex won't update itself to 1.15:
```
[cont-init.d] 60-plex-update: executing... 
curl: /usr/lib/plexmediaserver/libcurl.so.4: no version information available (required by curl)
curl: relocation error: curl: symbol curl_mime_headers version CURL_OPENSSL_4 not defined in file libcurl.so.4 with link time reference
Atempting to upgrade to: 
https://downloads.plex.tv/plex-media-server//plexmediaserver__amd64.deb:
2019-03-08 14:19:57 ERROR 404: Not Found.
```

Removing `-e LD_LIBRARY_PATH=/usr/lib/plexmediaserver` fixes the updating problem but now Plex Media Scanner becomes unavailable (aka gives me no lib found error).

Is there a way to have Plex update to 1.15 while retaining `-e LD_LIBRARY_PATH=/usr/lib/plexmediaserver` ?

**Comment by thelamer** [comment]
You need to pull the latest image, we define the new path and the legacy path when we run the application: 

https://github.com/linuxserver/docker-plex/blob/master/root/etc/services.d/plex/run#L8

**Comment by aptalca** [comment]
@ceptonit please don't create multiple issues for the same thing. I already provided you with an answer in the other issue. Not only I clarified that we do not support users manually running executables inside the container, I also pointed you in the right direction to get you to run it (define the ld library path in your command like we do in our service file).

**Comment by ceptonit** [comment]
@thelamer Thanks for the pointer
@aptalca Sorry about that, I didn't fully understand your reply. But with thelamer's response, your explanation now fully makes sense to me.

I guess a reply with the correct command would have shut me up straight away because I initially thought my docker exec command was right. But most of the time is best to give clues/pointers instead of providing the straight answer to the problem.
But anyways, thanks for helping me out figuring out the correct command:
`docker exec plex /bin/bash -c 'LD_LIBRARY_PATH=/usr/lib/plexmediaserver:/usr/lib/plexmediaserver/lib /usr/lib/plexmediaserver/Plex\ Media\ Scanner --help'`
