### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by mmakaresz** [linuxserver/docker-plex#167]
Hi All!

update is not working from the latest version of the plex media server amd64 debian build.
URL should be: https://downloads.plex.tv/plex-media-server-new/1.15.1.791-8bec0f76c/debian/plexmediaserver_1.15.1.791-8bec0f76c_amd64.deb
instead of 
https://downloads.plex.tv/plex-media-server/1.15.1.791-8bec0f76c/plexmediaserver_1.15.1.791-8bec0f76c_amd64.deb

log from the unsuccessful update:

```
[cont-init.d] 50-plex-update: executing...
Atempting to upgrade to: 1.15.1.791-8bec0f76c
https://downloads.plex.tv/plex-media-server/1.15.1.791-8bec0f76c/plexmediaserver_1.15.1.791-8bec0f76c_amd64.deb:
2019-03-20 07:51:16 ERROR 404: Not Found.



########################################################
# Upgrade attempt failed, this could be because either #
# plex update site is down, local network issues, or   #
# you were trying to get a version that simply doesn't #
# exist, check over the VERSION variable thoroughly &  #
# correct it or try again later.                       #
########################################################


[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services

```

thanks in advance.

**Comment by j0nnymoe** [comment]
Are you running the latest version of our container?

**Comment by mmakaresz** [comment]
oh you are right, i have updated the container and now it runs fine :) thanks. issue can be closed
