### ISSUE TITLE
streaming only works in web player...

### ISSUE THREAD

**Issue by masavini** [linuxserver/docker-plex#173]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

hi,
i used to run an old version of plex media server (1.10.1.4602) installed from the deb package with no issues.

this morning i switched to your docker image (great job, by the way): streaming perfectly works with the web player, but it stops after a few seconds on the lg tv app with this error:

there was a problem playing this item.
the video did not start in time.

this is the command i used to run the container:
```
$ docker run \
>   --restart always \
>   --name=plex \
>   --net=host \
>   --device=/dev/dri:/dev/dri \
>   -e PUID=1000 \
>   -e PGID=1000 \
>   -e VERSION=docker \
>   -v /home/teo/config/plex:/config \
>   -v /home/teo/media/videos/bimbe:/data/bimbe \
>   -v /home/teo/media/videos/transcode:/transcode \
>   linuxserver/plex
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
Docker is used for verisoning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
```

any suggestions..?
thanks!

**Comment by aptalca** [comment]
That really sounds like a plex issue rather than a docker issue. You should ask on their forums.

**Comment by thelamer** [comment]
Our container is bleeding edge for PMS version. Your LG TV is likely many major versions behind. 

I would highly recommend a if it ain't broke don't fix it approach, or investing in a modern TV stick or device and skipping the baked in Smart TV app.

**Comment by masavini** [comment]
update...

following your advice i reinstalled the old plex version.
it took me some time to find the proper deb package (plex website does not have a 'previous versions' sections..) and reinstall it, just to find out the issue was still there.

i was quite desperate and it took some more time just to figure out the actual configuration was identical to the old one (i had a backup, luckily)...

guess what? plex 1.15.2.793 and your docker container run perfectly with lg tv app...
the issue was caused by the brand new usb3-sata adapter that a friend of mine gave me to replace the one he borrowed and lost...
