### ISSUE TITLE
Plex server in startup loop

### ISSUE THREAD

**Issue by charliwest** [linuxserver/docker-plex#174]
So on starting the container, I just get a loop of starting plex media server over and over again, nothing loads, cannot access the webui. I tried destroying and recreating, tried setting the loglevel to debug and I get no extra info. Totally stuck :(

 Hypriot

docker run -d --name=plex --net=host -e PUID=1010 -e PGID=1010 -v /storage/tv:/data/tv -v /storage/movies:/data/movies -v /storage/plex:/config -v /storage/audio/Library:/data/music  -e VERSION=docker linuxserver/plex

`Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.

Starting Plex Media Server.`

**Comment by j0nnymoe** [comment]
Is the `/storage` mount a remote file system?

**Comment by charliwest** [comment]
No, local, its a usb drive plugged into the pi

**Comment by j0nnymoe** [comment]
Try putting that mount on the SD card first, it could be a mounting issue.

**Comment by charliwest** [comment]
I can try that, although it was working fine before a restart earlier for many many months

**Comment by charliwest** [comment]
D'oh, I think I know the issue. While looking at moving the dir I noticed the storage partition is full. Its almost certainly that that is the issue. Will resolve and report back.

**Comment by j0nnymoe** [comment]
Ah ok, I had assumed this was a fresh image. Still worth a try with a fresh `/config` folder as your current one could have corrupted

**Comment by charliwest** [comment]
Does a fresh config dir mean I won't have all my watch history etc?

**Comment by j0nnymoe** [comment]
Yep

**Comment by charliwest** [comment]
Couldn't get it working so just starting from scratch :(

**Comment by ElanHasson** [comment]
It was permissions on the config directory after I transferred my library from another machine.

**Comment by bmcgair** [comment]
garbage. Why not log something fucking useful?

**Comment by bmcgair** [comment]
I've been trying to get this working for about a month. Same COMPLETELY USELESS ERROR out of the container. It just loops with:
Starting Plex Media Server.
F*CK YOU GUYS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bmcgair** [comment]
Is there any way to get some actual debug out of this POS container? All I get is the god damn loop I have no idea what's wrong.

 Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.
Starting Plex Media Server.

**Comment by tobbenb** [comment]
@bmcgair Good to see you fell right into our trap. We made the container to not work as to piss off people.
