### ISSUE TITLE
Hostname conflict error on start

### ISSUE THREAD

**Issue by mattstorey001** [linuxserver/docker-plex#181]
Hostname conflict error on start.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
I currently have this on repeat, until it identifies a hostname which does not conflict. e.g. 'linuxserver-plex1-31' is a hostname which was used many months ago, and it appears in am on something like plex1-70+ now..

Host name conflict, retrying with linuxserver-plex1-31                                                                                     
Registering new address record for fe80::841d:28ff:fe9b:ff2b on docker8059a62.*.                                                           
Registering new address record for fe80::ccde:9eff:fee8:9858 on docker99918d4.*.                                                           
Registering new address record for fe80::d:46ff:fe29:ff61 on dockerf1cf92e.*.                                                              
Registering new address record for fe80::7490:f8ff:fee2:d472 on docker9ab01d9.*.                                                           
Registering new address record for fe80::42:feff:fe1d:e5e on docker0.*.                                                                    
Registering new address record for 172.17.0.1 on docker0.IPv4.                                                                             
Registering new address record for 169.254.59.246 on eth3.IPv4.                                                                            
Registering new address record for 169.254.159.234 on eth2.IPv4.                                                                           
Registering new address record for 169.254.97.175 on eth1.IPv4.                                                                            
Registering new address record for fdaa:bbcc:ddee:0:211:32ff:fe1c:d10b on eth0.*.                                                          
Registering new address record for 2a00:23c4:fe9c:b600:211:32ff:fe1c:d10b on eth0.*.                                                       
Registering new address record for 192.168.1.98 on eth0.IPv4.  

Most recent Synology version. Most recent docker version. Most recent Linux plex version. 

using host networking.

**Comment by j0nnymoe** [comment]
This to me sounds like a host issue than an issue with our container. Unfortunately  no one within the team uses Synology so we have no way of testing this.

**Comment by CHBMB** [comment]
Closing, no other reports.
