### ISSUE TITLE
PLEX_DOWNLOAD : can't find versions prior to 15.x

### ISSUE THREAD

**Issue by Altheran88** [linuxserver/docker-plex#182]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

- Host OS : UNRAID
- No commandline
- Docker log output : Atempting to upgrade to: 1.14.1.5488-cc260c476
https://downloads.plex.tv/plex-media-server/1.14.1.5488-cc260c476/debian/plexmediaserver_1.14.1.5488-cc260c476_amd64.deb:
2019-05-27 06:37:52 ERROR 404: Not Found.
- No symlink

The link to dowanload the 14.1.x version I want is the following :+1: 
https://downloads.plex.tv/plex-media-server/1.14.1.5488-cc260c476/plexmediaserver_1.14.1.5488-cc260c476_amd64.deb

There seems to be an extra /debian/ that is not to be.

**Comment by tobbenb** [comment]
Plex have changed the location of the deb packages from 1.15. That means it is not possible to install a specific version before 1.15.

**Comment by thelamer** [comment]
Have you tried overiding the download URL env variable ?`PLEX_DOWNLOAD="https://downloads.plex.tv/plex-media-server" `
If you sift through our tags you should also be able to use one of the old 1.14 version images with the old update logic and download locations.

**Comment by tobbenb** [comment]
The download url is hard-coded to add the debian part as far as I can see in the dockerfile, as far as I can see @thelamer 
So then its only the tag left.

**Comment by thelamer** [comment]
Yeah good point I did not test changing the var.
