### ISSUE TITLE
downloads.plex.tv -> plex.tv/downloads

### ISSUE THREAD

**Issue by 0xc0re** [linuxserver/docker-plex#184]
The update url (downloads.plex.tv) now redirects to plex.tv/downloads. This update causes the auto-update script to fail.

**Comment by thelamer** [comment]
Well get on this right away

**Comment by thelamer** [comment]
Hmm are you running the latest container??
I tested loacally and without plex pass I am pointed towards : 
https://downloads.plex.tv/plex-media-server-new/1.15.8.1198-eadbcbb45/debian/plexmediaserver_1.15.8.1198-eadbcbb45_amd64.deb

Which we have proper pathing for : 

https://github.com/linuxserver/docker-plex/blob/master/Dockerfile#L15

**Comment by 0xc0re** [comment]
My bad. I am running adnanklink/plex-norelay-hwdecoding which pulls in this image. I guess the issue is downstream.
