### ISSUE TITLE
No welcome/setup page

### ISSUE THREAD

**Issue by RichardMore** [linuxserver/docker-plex#185]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host: Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux -- Raspbian Lite
Docker version: 18.09.0, build 4d60db4
Container version: latest

The issue is that after starting the container when I visit the <IP>:32400 page, it normally redirects to <IP>:32400/web/index.html but no welcome page is shown, only searching for the other server connected to the account.
The folder mounted for the /config is empty and is populated normally after container start.
Am I missing something?

Docker run command used: `docker run -d -p 32400:32400 -p 32400:32400/udp -p 32469:32469 -p 32469:32469/udp -p 5353:5353/udp -p 1900:1900/udp --restart always -v /etc/localtime:/etc/localtime:ro -v /mnt/media/movies:/data/movies -v /mnt/configs_docker/plex/config:/config -e PUID=1000 -e PGID=1000 -e VERSION=docker -e TZ=Europe/Budapest --name plex linuxserver/plex`

Also tried adding the following parameters: hostname, PLEX_UID, PLEX_GID, PLEX_CLAIM

Docker logs output:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 40-chown-files: executing...
> Change in ownership detected, please be patient while we chown existing files
> This could take some time
> [cont-init.d] 40-chown-files: exited 0.
> [cont-init.d] 50-gid-video: executing...
> [cont-init.d] 50-gid-video: exited 0.
> [cont-init.d] 60-plex-update: executing...
> Docker is used for verisoning skip update check
> [cont-init.d] 60-plex-update: exited 0.
> [cont-init.d] 99-custom-scripts: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-scripts: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Starting Plex Media Server.

**Comment by tobbenb** [comment]
Is your config folder a remote share?

**Comment by RichardMore** [comment]
No, it is an NTFS drive (ntfs-3g)

**Comment by j0nnymoe** [comment]
That'll be the issue, fuse will be an extra application layer. Format the drive to ext4.

**Comment by RichardMore** [comment]
Done, but still nothing, no welcome page, just the existing server.

**Comment by j0nnymoe** [comment]
Not sure what you mean by existing server (I'm not a Plex user). Tried host networking?

**Comment by RichardMore** [comment]
- There is an other server associated with the account I am logged in with -
Aaaand it works now.
Can it be that there are ports the container/service wants to use but is not included in the ports mentioned in the instructions? ( these are the ones in the instructions -p 32400:32400 -p 32400:32400/udp -p 32469:32469 -p 32469:32469/udp -p 5353:5353/udp -p 1900:1900/udp)

**Comment by RichardMore** [comment]
With docker inspect the ports should be correct:

> "ExposedPorts": {
>                 "1900/udp": {},
>                 "32400/tcp": {},
>                 "32400/udp": {},
>                 "32469/tcp": {},
>                 "32469/udp": {},
>                 "5353/udp": {}
>             },

**Comment by thelamer** [comment]
For support use discord or our forums:
https://discord.gg/YWrKVTn
https://discourse.linuxserver.io/
