### ISSUE TITLE
Plex hangs on Starting Plex Media Server

### ISSUE THREAD

**Issue by JensPfeifle** [linuxserver/docker-plex#186]
Running UnRaid 6.7.0, had the following issue after upgrading the Plex container today via the Unraid WebUI. Tried to remove and reinstall the container and still cannot access the Plex Webui on 32400.

The browser error reads "Unable to connect"
Curl responds:
```
jensp@manjaro ~/o/OpenVPN_Server_jens> curl 10.0.1.7:32400
curl: (7) Failed to connect to 10.0.1.7 port 32400: Connection refused
```
The log repeats the line `Starting Plex Media Server.` indefinitely.

```
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
Docker is used for verisoning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Starting Plex Media Server.
Starting Plex Media Server. 
# repeats indefinitely #
```

I didn't make any changes to the App config other than setting the paths for movies, tv, and music. (Can't upload a screenshot due to an error.)

**Comment by tobbenb** [comment]
That is usually caused by a corrupt database or you are using /mnt/user/ for the plex config mount.

**Comment by JensPfeifle** [comment]
I'm using `/mnt/user/appdata/plex` for the config. Why would that cause a problem?

What are my options in case of a corrupt database? Probably easiest to remove the config folder and just reimport the library into a fresh plex config, right?

**Comment by sayak-brm** [comment]
Hey guys, I'm facing exactly this same problem.

### Setup:

Raspberry Pi running OpenMediaVault with the Docker-WebUI plugin pulling the latest `armv7hf ` image from `linuxserver/plex` (as of June 27). `/config` is set to a directory on a mounted USB HDD.

### Config options:

![image](https://user-images.githubusercontent.com/5992716/60300569-e3355c00-994c-11e9-924a-8c5757a80592.png) 
![image](https://user-images.githubusercontent.com/5992716/60300607-f811ef80-994c-11e9-9d88-31cc687cb8b0.png) 
![image](https://user-images.githubusercontent.com/5992716/60300645-0c55ec80-994d-11e9-917a-c8d65fee8519.png)

### PMS Log File:

```
Jun 27, 2019 20:49:19.965 [0x7324a450] INFO - Plex Media Server v1.16.0.1226-7eb2c8f6f - Docker Docker Container (LinuxServer.io) armv7l - build: linux-armv7hf_neon unknown - GMT 00:00
Jun 27, 2019 20:49:19.966 [0x7324a450] INFO - Linux version: 4.19.42-v7+, language: en-US
Jun 27, 2019 20:49:19.966 [0x7324a450] INFO - Processor Arm
Jun 27, 2019 20:49:19.967 [0x7324a450] INFO - /usr/lib/plexmediaserver/Plex Media Server
Jun 27, 2019 20:49:19.963 [0x73bf1400] DEBUG - BPQ: [Idle] -> [Starting]
Jun 27, 2019 20:49:19.968 [0x73bf1400] DEBUG - Opening 20 database sessions to library (com.plexapp.plugins.library), SQLite 3.26.0, threadsafe=1
Jun 27, 2019 20:49:20.013 [0x73bf1400] DEBUG - Running migrations. (EPG 0)
Jun 27, 2019 20:49:20.014 [0x73bf1400] ERROR - SQLITE3:0x7ed7b4f0, 1, no such table: schema_migrations in "select version from schema_migrations order by version"
Jun 27, 2019 20:49:20.015 [0x73bf1400] ERROR - Database corruption: sqlite3_statement_backend::prepare: no such table: schema_migrations for SQL: select version from schema_migrations order by version
Jun 27, 2019 20:49:20.016 [0x73bf1400] ERROR - Error: Unable to set up server: sqlite3_statement_backend::prepare: no such table: schema_migrations for SQL: select version from schema_migrations order by version (N4soci10soci_errorE)
```

### Other:

 - Connection refused to Plex WebUI on Port 32400.
 - The exact same log file as @JensPfeifle, except for my UID & GID.

**Comment by tobbenb** [comment]
@JensPfeifle 
The reason is that sqlite don't like fuse file systems. Using the direct disk share, either /mnt/cache/ if you have a cache disk or /mnt/diskX if not, will fix the issue.
You should have posted this in the plex support thread on the unraid forum.

@sayak-brm 
It's most likely caused by using the USB disk for the /config mount. Which files system is on it? 
Is the /config mount using the slave option? 
Are the PUID and PGID correct for the /config mount?

**Comment by thelamer** [comment]
@tobbenb is correct, github is not the place for support. These issues ping all of our developers. 

I do not believe that any of the reports in this thread constitute an actual bug report. 

For support use discord or our forums: 
https://discord.gg/YWrKVTn
https://discourse.linuxserver.io/

For unraid use the support thread: 
https://forums.unraid.net/topic/40463-support-linuxserverio-plex-media-server/
