### ISSUE TITLE
Crashes most nights

### ISSUE THREAD

**Issue by Chris230291** [linuxserver/docker-plex#190]
Hello. I am running Ubuntu. This docker container has started crashing most nights. I fall asleep to something on Plex, usually watching on Apple TV, then wake up the next day to a Plex container that needs restarting. Not sure if its the container, Ubuntu, Docker, etc... Only started recently.

The Plex Startup logs mention that it fails to update. I have no version set, so using the default.

```
Atempting to upgrade to: 


wget: unable to resolve host address ‘downloads.plex.tv’








########################################################


# Upgrade attempt failed, this could be because either #


# plex update site is down, local network issues, or   #


# you were trying to get a version that simply doesn't #


# exist, check over the VERSION variable thoroughly &  #


# correct it or try again later.                       #


########################################################






[cont-init.d] 60-plex-update: exited 0.
```

Any ideas?
Chris

**Comment by aptalca** [comment]
Either you have network issues (ufw?) or you're using a really old image.

Pull the latest image and recreate the container

**Comment by jakubsarosiek** [comment]
Hi, have simmilar issue, using network macvlan.

Found workaround for that by  'chmod 644 /etc/resolv.conf'

Error issuing curl_easy_perform(handle): 6
HTTP error requesting GET https://plex.tv/media/providers?X-Plex-Token=xxxxxxxxxxxxxxxxxxxxd not resolve host: plex.tv)

User that is mapped by PUID/PGID is not permitted to acces /etc/resolv.conf so basically DNS its not working on that.

IDK how was that on older version, anyone can look on that?

BR,
Jimmy

**Comment by aptalca** [comment]
Are you referring to /etc/resolv.conf on the host?

**Comment by jakubsarosiek** [comment]
On docker image. But weird. I’ve tried run image dozens of times. And every time permissions wasn’t correct. And change was needed. But yours are ok.

**Comment by cybercorey** [comment]
Similar issue, however it seems to have no nameservers in resolv.conf
(I run two PMS of one docker host, one does have DNS one doesnt....)

**Comment by thelamer** [comment]
I do not think this issue specifically is a bug report or anything we can change on our end to ensure functionality. 
What I can recommend to anyone having this issue is to:
1. use the latest container
2. use docker-ce installed from docker's repo https://docs.docker.com/install/linux/docker-ce/ubuntu/
3. reach out on Discord or our forums for support 

https://discord.gg/YWrKVTn
https://discourse.linuxserver.io/
