### ISSUE TITLE
Live TV Not Working No DVR Found

### ISSUE THREAD

**Issue by quwip10** [linuxserver/docker-plex#193]
Confirmed with multiple users that Live TV is not working. 

<img width="704" alt="image" src="https://user-images.githubusercontent.com/26572979/60934286-ac880b80-a293-11e9-9edf-1b297a625d39.png">

![image](https://user-images.githubusercontent.com/26572979/60934296-b3af1980-a293-11e9-8296-a2a0b5e881f4.png)

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 UNRAID

 
<img width="889" alt="image" src="https://user-images.githubusercontent.com/26572979/60933997-a47b9c00-a292-11e9-992c-e30116d4341c.png">

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/26572979/60934231-7480c880-a293-11e9-99a9-36dcdf69d7c3.png">

 N/A

Rollback? I'll be testing previous tags to see if I can get it to work.

**Comment by quwip10** [comment]
Rolled back to 1.16.0.1226-7eb2c8f6f-ls30 and both iPhone and Nvidia Shield now work.

**Comment by quwip10** [comment]
https://forums.plex.tv/t/plextv-server-can-no-longer-see-hdhomerun-tuner/425461/9

**Comment by tobbenb** [comment]
This is not an issue with this container, so closing this.
