### ISSUE TITLE
Creates a new Server after every restart

### ISSUE THREAD

**Issue by dunklesToast** [linuxserver/docker-plex#195]
Nearly everytime I restart the PleX Docker Container it creates a new Server which has to be set up again with all libraries and all that stuff. Also, the PlexOnlineToken in the Preference File changes after every restart. I tried replacing it with the old one and I am also using the ENV-Var for setting the Token but it doesn't work and will still create a new Server. I am using portainer for deployment and all configuration files are stored on local Harddrives. The Server is a DELL R710 with Linux.

Current Preferences.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<Preferences OldestPreviousVersion="1.15.5.994-4610c6e8d" MachineIdentifier="xxxxxxx-7c90-4c6f-b7be-97ec14aba683" ProcessedMachineIdentifier="x" AnonymousMachineIdentifier="55926100-xxxx-4b14-a9cb-d298150369bd" MetricsEpoch="1" AcceptedEULA="1" PlexOnlineToken="xxxxxxxxxxxxxx" PlexOnlineUsername="dunklesToast" PlexOnlineMail="xxxxxxx@icloud.com" CertificateVersion="2" LanguageInCloud="1" PubSubServer="172.104.152.89" PubSubServerRegion="fra" PubSubServerPing="51"/>
```
_replaced some values with "x"._

How can I get the "old" Server back? I think I just need it's PlexOnlineToken but where can I find it, since the ones I used before won't work anymore.

**Comment by aptalca** [comment]
Post the command you use to create the container

**Comment by james-d-elliott** [comment]
Sounds like you're not mapping the /config path, if you don't it will automatically create a docker volume for the config each time you recreate (not restart) the container. Try adding something like "-v plex_config:/config" to your docker create/run, or if you're creating it via portainer just map the container path (/config) to a new volume, or bind it to a path if you prefer.

"Nearly everytime" is the key point. I'm betting it's only when you delete and recreate it.

**Comment by dunklesToast** [comment]
Hi! The Config path is mapped correctly and I verified this by stopping the container, moved all files out of it and then on the next restart it created all the files again. I think the only problem is that I need to get the old server database back. Is there any way to get this?

**Comment by j0nnymoe** [comment]
Only if you have a backup

**Comment by dunklesToast** [comment]
Damn. I don't think I have one. So I will recreate the server and then create some kind of cron job to backup the config directory. That should be enough, right?

**Comment by j0nnymoe** [comment]
I'd be more concerned to see why your docker container isn't using the persistent data otherwise if you're trying to restore a backup, how is it going to read it if it already creates a new server every reboot?

**Comment by dunklesToast** [comment]
Hmmm. That's my portainer config so far: https://i.imgur.com/0UPjkjr.png

**Comment by dunklesToast** [comment]
ooookaaaay. i think i found the problem. the Harddrive containing all the configuration got unmounted / has a failure and thatswhy the config no longer "exists". PleX created a new config on the main system drive. So not a Docker Container fault, just me being to incompetent to check my server. Sorry

**Comment by j0nnymoe** [comment]
Food for thought aswell, keep you appdata away from the rest of your data:
![image](https://user-images.githubusercontent.com/10374553/61123601-b2047200-a49c-11e9-8cab-d9e1a6880884.png)
I would put any appdata for your container's in their own folder like `/home/user/appdata/plex` .

**Comment by dunklesToast** [comment]
Ok! Thanks for that. If I have the old config back i can simply copy it to the new direction as long as the container isn't running, right? Then changing the Binds and recreate the container and everything should work?

**Comment by Datapotomus** [comment]
Yeah if you copy the data into a new location, and attach it to that config folder. Everything should work. 

I'm with everyone else in getting  it out of the same structure as your files. You could always use something like /mnt/data/plex_config or something like that. 

I would not advise using anything off of the root partition, because all depending on what options you select for thumbnail generation, and how much media you load into plex. That directory can get quite large. I'm currently sitting at 119GB.
