### ISSUE TITLE
Starting the container fails

### ISSUE THREAD

**Issue by joconcepts** [linuxserver/docker-plex#197]
If I start the container I always get this error in the log:

```
Starting Plex Media Server.
/usr/lib/plexmediaserver/Plex Media Server: error while loading shared libraries: libgnsdk_dsp.so.3.10.1: cannot enable executable stack as shared object requires: Permission denied
```

Command used to start the container:
`docker run  --name=plex   --net=host   -e PUID=1000   -e PGID=1000   -e VERSION=docker   -v /srv/plex/config:/config   -v /srv/smb/Jonas/Videos/:/data/videos   -v /srv/plex/transcode:/transcode   --restart unless-stopped -d  linuxserver/plex:latest`

Anybody else the same issue?

**Comment by thelamer** [comment]
`/usr/lib/plexmediaserver/lib/libgnsdk_dsp.so.3.10.1` is a lib included in the Plex Deb. 

No I do not get this on my systems and we do not see this in CI. 
https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/plex/latest/index.html

If your container is functional I would simply ignore it .

**Comment by joconcepts** [comment]
So the issue is that it will not work with this error, the server does not start.

**Comment by thelamer** [comment]
base OS and method you installed docker with?

**Comment by joconcepts** [comment]
Base OS is alpine linux wiht the packaged docker

**Comment by thelamer** [comment]
playing on hard mode huh. 
Never had that setup to test honestly, I have used muslc docker bins to interact with the API but never to run our containers. 

Do other GlibC containers work in this setup? (basically anything ubuntu based)

**Comment by joconcepts** [comment]
I've fixed it by running the following on the container:

```
docker exec -ti plex bash -c 'apt update ; apt install -y execstack ; execstack -c usr/lib/plexmediaserver/lib/libgnsdk_dsp.so.3.10.1'
```

**Comment by thelamer** [comment]
If that is the case these Libs come from upstream, we should not be patching their Lib flags manually. 
Please report this upstream.

**Comment by j0nnymoe** [comment]
Closing this issue as it needs to be fixed upstream, not at container level.
