### ISSUE TITLE
Cant upgrade Plex

### ISSUE THREAD

**Issue by Sanitys** [linuxserver/docker-plex#199]
[cont-init.d] 60-plex-update: executing... 
Atempting to upgrade to: 1.16.4.1469-6d5612c2f
########################################################
# Upgrade attempt failed, this could be because either #
# plex update site is down, local network issues, or   #
# you were trying to get a version that simply doesn't #
# exist, check over the VERSION variable thoroughly &  #
# correct it or try again later.                       #
########################################################
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.

Current version is Version 1.15.5.994, Any idea why its stuck? btw, your discord invite is dead, can you put a new one up?

**Comment by tobbenb** [comment]
I just restarted my plex container and had no issues updating it.
Please provide more info. Full container log from startup and run command. Do you have plex pass?

**Comment by aptalca** [comment]
You're probably on an old image. Plex changed their path for downloads, which was fixed in newer images.
You need to pull the new image, and recreate your container.

Where did you come across a dead discord link?

**Comment by Sanitys** [comment]
Dead Discord link is on this page: https://hub.docker.com/r/linuxserver/plex/

Logs looped for a while.

[root@localhost ~]# docker start mattflix
mattflix
[root@localhost ~]# docker logs mattflix
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
Critical: libusb_init failed
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
Atempting to upgrade to: 1.16.4.1469-6d5612c2f
########################################################
# Upgrade attempt failed, this could be because either #
# plex update site is down, local network issues, or   #
# you were trying to get a version that simply doesn't #
# exist, check over the VERSION variable thoroughly &  #
# correct it or try again later.                       #
########################################################
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Critical: libusb_init failed
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------

Yes I have Plex pass, I would have to rebuilt to remove the latest flag and change to public.

**Comment by tobbenb** [comment]
Post you run command/compose.
As @aptalca says, make sure you have updated the container.

**Comment by j0nnymoe** [comment]
Closing due to no response.
