### ISSUE TITLE
Plexpass Error Downloading

### ISSUE THREAD

**Issue by kkniffin** [linuxserver/docker-plex#20]
I am getting an error when using your image with Plexpass downloading. I am guessing the URL is incorrect as I can't download it even when trying manually.

--2016-01-11 14:27:03--  https://downloads.plex.tv/plex-media-server/%22plexpass%22/plexmediaserver_%22plexpass%22_amd64.deb
plex                 | Resolving downloads.plex.tv (downloads.plex.tv)... 104.20.7.9, 104.20.6.9, 2400:cb00:2048:1::6814:609, ...
plex                 | Connecting to downloads.plex.tv (downloads.plex.tv)|104.20.7.9|:443... connected.
plex                 | HTTP request sent, awaiting response... 404 Not Found
plex                 | 2016-01-11 14:27:03 ERROR 404: Not Found.

According to the site the path for the latest release is: https://downloads.plex.tv/plex-media-server/0.9.15.0.1621-344f193/plexmediaserver_0.9.15.0.1621-344f193_amd64.deb

**Comment by sparklyballs** [comment]
sparklyballs@Jenkins-Server:/tmp$ VERSION=$(curl -s https://tools.linuxserver.io/latest-plexpass.json | grep "version" | cut -d '"' -f 4) && wget -P /tmp "https://downloads.plex.tv/plex-media-server/$VERSION/plexmediaserver_${VERSION}_amd64.deb"
--2016-01-11 14:35:14--  https://downloads.plex.tv/plex-media-server/0.9.15.0.1621-344f193/plexmediaserver_0.9.15.0.1621-344f193_amd64.deb
Resolving downloads.plex.tv (downloads.plex.tv)... 104.20.7.9, 104.20.6.9, 2400:cb00:2048:1::6814:609, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|104.20.7.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 128037122 (122M) [application/octet-stream]
Saving to: ‘/tmp/plexmediaserver_0.9.15.0.1621-344f193_amd64.deb’

100%[====================================================================>] 128,037,122 8.83MB/s   in 14s

2016-01-11 14:35:28 (8.83 MB/s) - ‘/tmp/plexmediaserver_0.9.15.0.1621-344f193_amd64.deb’ saved [128037122/128037122]

**Comment by sparklyballs** [comment]
did you leave the quotes in around plexpass ?

**Comment by kkniffin** [comment]
Yes, should they be removed?

**Comment by kkniffin** [comment]
I removed them, I think that was the trick... Thanks for the tip.
