### ISSUE TITLE
Plex not starting

### ISSUE THREAD

**Issue by viruz82** [linuxserver/docker-plex#206]
I have just startet a new container with a complete new config and get the following error.
My host OS is Ubuntu 18.04.3 LTS.

This is my startscript:
```
docker run -d \
--name=plex \
--restart=always \
--net=host \
-e VERSION=docker \
-e PUID=1111 \
-e PGID=1111 \
-v /media/docker/plex/config:/config \
-v /media/pictures:/data/pictures \
-v /media/series:/data/series \
-v /media/movies:/data/movies \
-v /media/music:/data/music \
linuxserver/plex
```

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1111
User gid:    1111
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...

#####################################################
#   Login via the webui at http://<ip>:32400/web    #
#   and restart the docker, because there was no    #
#   preference file found, possibly first startup.  #
#####################################################

[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --platformVersion arg Platform version string
  --vendor arg          Vendor string
  --device arg          Device string
  --model arg           Device model string
  --sentryUrl arg       Sentry URL to upload to
  --sentryKey arg       Sentry Key for the project
  --version arg         Version of the product
free(): corrupted unsorted chunks
free(): corrupted unsorted chunks
Exception AttributeError: "'ZipArchive' object has no attribute '_zip'" in <bound method ZipArchive.__del__ of <Framework.components.data.ZipArchive object at 0x7fc0c855d650>> ignored`

**Comment by j0nnymoe** [comment]
Github is reserved for bugs/issues - not general support - please you our [discord](https://discord.gg/YWrKVTn) or [forum](https://discourse.linuxserver.io/)

**Comment by viruz82** [comment]
Really, and this is not a bug/issue?

```
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
--directory arg Directory to scan for crash reports
--serverUuid arg UUID of the server that crashed
--userId arg User that owns this product
--platform arg Platform string
--platformVersion arg Platform version string
--vendor arg Vendor string
--device arg Device string
--model arg Device model string
--sentryUrl arg Sentry URL to upload to
--sentryKey arg Sentry Key for the project
--version arg Version of the product
free(): corrupted unsorted chunks
free(): corrupted unsorted chunks
Exception AttributeError: "'ZipArchive' object has no attribute '_zip'" in <bound method ZipArchive.del of <Framework.components.data.ZipArchive object at 0x7fc0c855d650>> ignored`
```

This happens after starting a new container wirh your image and your scripts!

**Comment by j0nnymoe** [comment]
Actually the image is fine- https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/plex/latest/index.html - we test our images after every build and produce this report.

I've seen this error before and it's likely to be an issue with the host.
Move `-v /media/docker/plex/config:/config \` I suspect this could be the issues relating to permissions - move it to `-v /home/someuser/plex/config:/config \` and see if you have the same issue.

**Comment by sparklyballs** [comment]
In support of what @j0nnymoe has already said, spinning up a fresh container with your run command (modified to suit local paths to me) , gives....

https://pastebin.com/g0BpFiQj

and the run command 

```
docker run -d \
--name=plex \
--restart=always \
--net=host \
-e VERSION=docker \
-e PUID=1000 \
-e PGID=1000 \
-v /home/sparklyballs/config:/config \
-v /home/sparklyballs/pictures:/data/pictures \
-v /home/sparklyballs/series:/data/series \
-v /home/sparklyballs/movies:/data/movies \
-v /home/sparklyballs/music:/data/music \
linuxserver/plex
```

**Comment by viruz82** [comment]
Okay, thank you gus. I will check.
Cheers.
