### ISSUE TITLE
Cant stop container

### ISSUE THREAD

**Issue by wuast94** [linuxserver/docker-plex#212]
I have installed this container over User Application plugin in Unraid. 

Sometimes when i transcode media and scroll in timeline my plex gets unresponsive. 
The problem is that i even cant stop the container. I tried "docker kill plex" too but nothing there. 

I need to stop the whole docker service (sometimes even that dont work) or need to restart the hole server.

**Comment by aptalca** [comment]
It's likely an unraid related issue. When the io gets too high on unraid or the cpu is pegged, docker service starts lagging and can appear stuck, during which time you can't start/stop containers.

What kind of hardware are you running this on?

Next time it happens, ssh in and do `htop`

**Comment by wuast94** [comment]
my cpu is by ca 20% utillization and i dont have high disk io or low on memory. I checked this. and its not a problem that goes away after a bit of time. my server is in this state at the moment i cant stop the plex container. it stayes in this state until i restart docker service or unraid

**Comment by wuast94** [comment]
ok i invastigate a bit. 

Plex container is at 100% cpu (from 800%) so one core is maxed out. 
i cant go in terminal in plex container: 
`
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "process_linux.go:91: executing setns process caused \"exit status 21\"": unknown
`

**Comment by wuast94** [comment]
at the peak i was scrobbling at timeline of an 4k file than it gets unresponsive and stayes at this state
![image](https://user-images.githubusercontent.com/16965460/69480311-c53e2b80-0e06-11ea-9fb7-2458a4b2bccb.png)

**Comment by wuast94** [comment]
btw i now tried to kill the process over PID and the Parent and the parent of the parent and even that don´t work ( i used kill -9) dont know why. 

but it seems that the transcoder caused the problem. i looked in logs too but didn´t find anything

**Comment by aptalca** [comment]
If you're software transcoding a 4k file, that explains why. It is extremely cpu intensive even on the latest gen beefy processors. It is likely tying up your cpu so the docker system can't function properly. The thing about unraid is that, usually core 0 is dedicated for the OS related tasks. If that core is saturated, unraid will halt. For cpu intensive containers that do things like software transcoding, or large file extractions, limit them to use the other cpu cores and not core 0.

**Comment by thelamer** [comment]
I do not believe there are any changes we can make to our software init or container as a whole to prevent this behavior. 
We as an organization will never assume hard kills and will let S6 and Docker cleanup pids. 

I will be closing this issue, if you require further support please try our Discord: 

https://discordapp.com/invite/YWrKVTn
