### ISSUE TITLE
Unable to delete files from within plex

### ISSUE THREAD

**Issue by JoshuaMulliken** [linuxserver/docker-plex#213]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

When I select `Get Info` on a piece of media and say `Delete Files` it should delete the file.

## Current Behavior

Currently when I select `Delete Files` it says: `There was a problem deleting this item.`

## Steps to Reproduce

1. Click the three-dot menu item on a title
2. Select `Get Info`
3. Choose a file to delete and select `Delete Files`
4. It will provide: `There was a problem deleting this item.`

## Environment
**OS:** Ubuntu 18.04.3
**CPU architecture:** x86_64
**How docker service was installed:** sudo apt-get install docker docker-compose -y

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose.yml` run with `sudo docker-compose up -d`
```.yml
plex:
    container_name: plex
    image: linuxserver/plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - './plex-config/:/config/'
      - '/media/Multimedia/TV:/tv/'
      - '/media/Multimedia/Movies:/movies/'
      - './plex-transcode/:/transcode/'
    restart: unless-stopped
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
Docker is used for verisoning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
```

**Comment by aptalca** [comment]
Check the permissions on the media files you're trying to delete

**Comment by JoshuaMulliken** [comment]
`-rwxr-xr-x 1 root root` are the permissions right now. What should it be?

**Comment by aptalca** [comment]
Plex is running as pid 1000 on your host, which is not root. And non root users do not have write permissions on your media, that's your issue.

The proper way to fix it would be to make sure your media is owned by pid `1000`

**Comment by JoshuaMulliken** [comment]
@aptalca I was able to fix it! Thanks for the help. The folder that I am using is mounted via fstab.
fstab Entry:
```
//192.168.0.10/Multimedia /media/Multimedia cifs credentials=/home/joshua/.smbcredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,uid=joshua,gid=joshua,nofail 0 0
```
I am sharing that with the plex container. I needed to fix the fstab entry to get the permissions right. Previously they were mounted with root as the owner which obviously did not work.

**Comment by isaacrlevin** [comment]
I am getting this same issue, the process is running as the same user that owns the directories yet on all my players, I am unable to delete media

**Comment by cerickso88** [comment]
I'm having a similar issue.  When I delete an item, it does delete but leaves the metadata on the library.   So the TV Show or Movie are actually off the disk but the Plex Interface shows the media still there.  After a time, Plex will show it 'unavailable' but the metadata is still showing.   I tried to 'delete' the metadata from the library by select "Empty Trash" from the Library.   Any ideas?

**Comment by OmskInfo** [comment]
I have the same issue as cerickso88, above: I can delete the media from my drive, either directly from the Finder or via the "Delete files" option in Plex, but the item remains shown in my media library with the status "Unavailable".

**Comment by quilmore** [comment]
> I have the same issue as cerickso88, above: I can delete the media from my drive, either directly from the Finder or via the "Delete files" option in Plex, but the item remains shown in my media library with the status "Unavailable".

if you enable to scan folders when a change is detected that will go away (Scan my library automatically)

**Comment by OmskInfo** [comment]
And to be clear, this is happening with only one movie in my collection. Other movies and shows I delete get removed from the library without issue. It's like the record of this particular movie is corrupted in some way not allowing it to be removed from the library.

**Comment by johnrm** [comment]
I had the same issue but this was with all files.
I am running OMV (OpenMediaVault NAS) and Plex Server on Raspberry Pi
In my case it was permissions.
I updated permissions from Read/Execute to Read/Write.
Quite possibly there is a permission issue on your media file.

**Comment by regeter** [comment]
pretty sure mine was fixed when I updated the PGID=1000, to PGID=999.
999 is the group id of my administrator group.
