### ISSUE TITLE
transcode folder not working as expected

### ISSUE THREAD

**Issue by umbynos** [linuxserver/docker-plex#215]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Transcode directory should be used to store data by the transcoder.
## Current Behavior

I have a 8 TB drive onto which i mapped my transcode folder, and an emmc card (16gb) onto which I placed my /config. The problem is that the transcoder tries to use the emmc card to store the data and fails..
From Plex logs:
```Low disk space: 36.87GB source file, 13.77GB capacity, 4GB available on "/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sync+/34503157/f0"```
Obviously I've set the **Transcoder temporary directory** under Settings-> Transcoder but it seems to get ignored.

## Environment
**OS:**      Ubuntu 19.10
**CPU architecture:** x86_64     
**How docker service was installed:**      from the official docker repo (https://download.docker.com/linux/ubuntu)

## Command used to create docker container (run/create/compose/screenshot)

```docker create --name=plex --net=host -e PUID=1000 -e PGID=1000 -e VERSION=docker --device=/dev/dri/card0:/dev/dri/card0 --device /dev/dri/renderD128:/dev/dri/renderD128 -v /media/umbynos/mmc/.config/plex/:/config -v /media/umbynos/NAS-8TB/tv/:/tvshows -v /media/umbynos/NAS-8TB/movies/:/movies -v /media/umbynos/NAS-8TB/transcode/:/transcode --restart unless-stopped linuxserver/plex```
## Docker logs

no strange behavior from docker logs

**Comment by aptalca** [comment]
That volume mapping was necessary a long time ago before plex made it a gui setting. We just hadn't gotten around to removing it. It is now handled in plex gui, and defaults to a location under `/config`.

That mapping suggestion will be removed in the next update to remove any confusion: https://github.com/linuxserver/docker-plex/pull/214

PS. You can still map a volume for it if you like, but make sure you select that container location in the plex gui settings.

**Comment by umbynos** [comment]
Thank you for the fast answer and for the tip! Now it's working!
For reference: I've mapped a volume with `-v /transcode/:/transcode` when I created the container (the transcode folder is on my nas), started the container, got a shell inside the container (`docker exec -it plex /bin/bash`), navigated to `/config/Library/Application Support/Plex Media Server/Cache/Transcode` and then created a soft link to the transcode folder (which is mapped to my nas) using `ln -s /transcode/Sync+/ Sync+`
