### ISSUE TITLE
plex server timezone could not set

### ISSUE THREAD

**Issue by fireinice** [linuxserver/docker-plex#216]
[linuxserverurl]: https://linuxserver.io

[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

after set TZ environment or other methods could change the container timezone 

## Current Behavior

set TZ environments, also bind /etc/localtime and /etc/timezone. but in the container the `date` command and plex log still use UTC timezone. 

## Steps to Reproduce

1. use docker-composer as configured below:
2. recreate a new container and check the `date` command in container still return UTC timezone time.

> $ sudo docker exec -it plex /bin/date
> Mon Dec 30 08:38:35  2019
> $ date
> Mon 30 Dec 2019 04:38:36 PM CST

## Environment
**OS: Debian 5.3.15-1 (2019-12-07)**      
**CPU architecture:** x86_64
**How docker service was installed: docker compose from hub.docker.com**      

## Command used to create docker container (run/create/compose/screenshot)

>   plex:
>     image: linuxserver/plex
>     # image: plexinc/pms-docker:latest
>     container_name: plex
>     restart: always
>     network_mode: host
>     volumes:
>       - /mnt/data2/docker/config/plex:/config
>       - /mnt/data2/docker/data/acme:/config/ssl
>       - /mnt/data2/docker/data/plex/temp:/transcode
>       - "/etc/timezone:/etc/timezone:ro"
>       - "/etc/localtime:/etc/localtime:ro"
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - VERSION=docker
>       - TZ="Asia/Shanghai"

## Docker logs

> Attaching to plex
> plex             | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> plex             | [s6-init] ensuring user provided files have correct perms...exited 0.
> plex             | [fix-attrs.d] applying ownership & permissions fixes...
> plex             | [fix-attrs.d] done.
> plex             | [cont-init.d] executing container initialization scripts...
> plex             | [cont-init.d] 01-envfile: executing... 
> plex             | [cont-init.d] 01-envfile: exited 0.
> plex             | [cont-init.d] 10-adduser: executing... 
> plex             | 
> plex             | -------------------------------------
> plex             |           _         ()
> plex             |          | |  ___   _    __
> plex             |          | | / __| | |  /  \ 
> plex             |          | | \__ \ | | | () |
> plex             |          |_| |___/ |_|  \__/
> plex             | 
> plex             | 
> plex             | Brought to you by linuxserver.io
> plex             | We gratefully accept donations at:
> plex             | https://www.linuxserver.io/donate/
> plex             | -------------------------------------
> plex             | GID/UID
> plex             | -------------------------------------
> plex             | 
> plex             | User uid:    1000
> plex             | User gid:    1000
> plex             | -------------------------------------
> plex             | 
> plex             | [cont-init.d] 10-adduser: exited 0.
> plex             | [cont-init.d] 40-chown-files: executing... 
> plex             | [cont-init.d] 40-chown-files: exited 0.
> plex             | [cont-init.d] 45-plex-claim: executing... 
> plex             | [cont-init.d] 45-plex-claim: exited 0.
> plex             | [cont-init.d] 50-gid-video: executing... 
> plex             | [cont-init.d] 50-gid-video: exited 0.
> plex             | [cont-init.d] 60-plex-update: executing... 
> plex             | Docker is used for versioning skip update check
> plex             | [cont-init.d] 60-plex-update: exited 0.
> plex             | [cont-init.d] 99-custom-scripts: executing... 
> plex             | [custom-init] no custom files found exiting...
> plex             | [cont-init.d] 99-custom-scripts: exited 0.
> plex             | [cont-init.d] done.
> plex             | [services.d] starting services
> plex             | Starting Plex Media Server.
> plex             | [services.d] done.

**Comment by homerr** [comment]
Remove the redundant lines mapping `/etc/timezone` and `/etc/localtime` to the container, leave environment variable set but remove the quotations so your compose file looks something like the following

`version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=id
      - PGID=id
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
      - TZ=Europe/London
    volumes:
      -  ./config:/config
      - ./tv:/tv
      - ./movies:/movies
    restart: unless-stopped`

I set the timezone to Paris and it worked;

`root@docker-desktop:/# date
Mon Dec 30 10:26:37 CET 2019
root@docker-desktop:/# cat /etc/timezone
Etc/UTC
root@docker-desktop:/# date +'%:z %Z'
+01:00 CET`

It'll honour what is set as the TZ variable and ignore the timezone file. 

If you have any further issues please join us in Discord.
