### ISSUE TITLE
Feature request: disable Plex relay

### ISSUE THREAD

**Issue by burkasaurusrex** [linuxserver/docker-plex#218]
Thanks for the hard work on this! I really like this container.

I think it would be a useful feature to have an environment variable to disable Plex relay. I think there are a a variety of ways to do this:

- `rm /usr/lib/plexmediaserver/Plex Relay`
- `chmod 0000 /usr/lib/plexmediaserver/Plex Relay` 
- `> config /plex/Library/Application Support/Plex Media Server/Cache/relayHostKey.txt && chmod 0000 /plex/Library/Application Support/Plex Media Server/Cache/relayHostKey.txt`
- I think you could also block whatever port Plex relay uses

Whatever method would probably have to be done at every update unfortunately...

**Comment by aptalca** [comment]
It should be a request for the upstream so you can do it within the Plex gui. For us to do such a thing would be very hacky.

In the meantime, see here for how to make sure it's done automatically at every container start: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by burkasaurusrex** [comment]
oh nice! I didn't realize lsio containers had this functionality. Do you happen to know if `custom-cont-init.d` scripts would run before or after updating Plex?

**Comment by aptalca** [comment]
After. Those are the last to run

**Comment by burkasaurusrex** [comment]
Great. For posterity, I ended up dropped this script into `/config/custom-cont-init.d`:

```
#!/usr/bin/env bash
chmod 600 "/usr/lib/plexmediaserver/Plex Relay"
```

I felt like it was the least disruptive while also accomplishing the goal. May or may not need to restart Plex after `chmod` - I'll investigate.

**Comment by aptalca** [comment]
Plex starts after the init file, so you shouldn't need to

**Comment by 19wolf** [comment]
This is now upstream, and can be done in the Plex gui
