### ISSUE TITLE
30_update_plex.sh hangs on ping loop

### ISSUE THREAD

**Issue by ags131** [linuxserver/docker-plex#22]
I apologize in advance if I'm missing something simple, I've not messed with docker much until this setup. On my system, (Fresh stock Ubuntu 15.10 install), 30_update_plex.sh gets stuck in the ping loop indefinitely and hogs CPU. After running the commands below, the script runs fine.

$ docker exec plex ping -c1 tools.linuxserver.io
ping: unknown host tools.linuxserver.io
$  docker exec plex /bin/bash -c "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf"
$ docker exec plex ping -c1 tools.linuxserver.io
PING tools.linuxserver.io (104.18.61.43) 56(84) bytes of data.
64 bytes from 104.18.61.43: icmp_seq=1 ttl=53 time=19.3 ms

--- tools.linuxserver.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 19.389/19.389/19.389/0.000 ms

**Comment by jflo** [comment]
Had the same issue due to ICMP filtering on local network. Had to allow ICMP now to run plex.

**Comment by ags131** [comment]
How did you do that? Plex itself runs fine, its just the update script that hangs

**Comment by IronicBadger** [comment]
Can you confirm whether this is an issue with the container or your network setup please.

**Comment by jflo** [comment]
It was with my network. I'd argue that this shouldn't require ICMP, perhaps use an HTTP HEAD to determine connectivity?

**Comment by ags131** [comment]
@IronicBadger I'm pretty sure its not with my network, ICMP seems to go through just fine, however, the container doesn't seem to be resolving DNS, I'm able to fix that by injecting a nameserver into /etc/resolv.conf after which the script works fine until a container reboot.
This is a fresh Ubuntu 15.10 64bit Server install with the only thing installed being docker. No extra network config was done, its all DHCP

**Comment by caccamo** [comment]
@IronicBadger I have the very same problem. I am on ubuntu 16.04 and I get this upon reboot

```
docker exec plex ping -c1 tools.linuxserver.io
ping: unknown host tools.linuxserver.io
```

**Comment by albertograzi** [comment]
Turns out that the problem is actually with the OS itself. If your network is configured with DHCP, it might come up later than the docker service. In that case networking in dockers won't work in host mode.

The only way to get this to work is to restart the docker service once you have an IP address. For the latest ubuntu (16.04) it was enough to do

`sudo systemctl restart docker`

This is not really a bug of this docker&script, but more of an OS thing.
