### ISSUE TITLE
Container not buildable anymore with PLEX version "1.18.5.2309"

### ISSUE THREAD

**Issue by SR-G** [linuxserver/docker-plex#220]
------------------------------

## Expected Behavior

Container should be buildable without any errors while using the `docker build` example provided in the README.md

## Current Behavior

An error is thrown at some point, see below :

```
reparing to unpack /tmp/plexmediaserver.deb ...
PlexMediaServer install: Pre-installation Validation.
PlexMediaServer install: Docker detected. Preinstallation validation not required.
Unpacking plexmediaserver (1.18.5.2309-f5213a238) ...
Setting up plexmediaserver (1.18.5.2309-f5213a238) ...
PlexMediaServer install: Error:  Plex installation configuration file could not be imported.  Please seek additional help in our Support Forums
dpkg: error processing package plexmediaserver (--install):
 installed plexmediaserver package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 plexmediaserver
The command '/bin/sh -c echo "**** install runtime packages ****" &&  apt-get update &&  apt-get install -y 	udev 	unrar 	wget 	jq &&  echo "**** Udevadm hack ****" &&  mv /sbin/udevadm /sbin/udevadm.bak &&  echo "exit0" > /sbin/udevadm &&  chmod +x /sbin/udevadm &&  echo "**** install plex ****" &&  if [ -z ${PLEX_RELEASE+x} ]; then  	PLEX_RELEASE=$(curl -sX GET 'https://plex.tv/api/downloads/5.json' 	| jq -r '.computer.Linux.version');  fi &&  curl -o 	/tmp/plexmediaserver.deb -L 	"${PLEX_DOWNLOAD}/${PLEX_RELEASE}/debian/plexmediaserver_${PLEX_RELEASE}_${PLEX_ARCH}.deb" &&  dpkg -i /tmp/plexmediaserver.deb &&  mv /sbin/udevadm.bak /sbin/udevadm &&echo "**** ensure abc user's home folder is /app ****" &&  usermod -d /app abc &&  echo "**** cleanup ****" &&  apt-get clean &&  rm -rf 	/etc/default/plexmediaserver 	/tmp/* 	/var/lib/apt/lists/* 	/var/tmp/*' returned a non-zero code: 1
```

## Steps to Reproduce

Just follow content of the README.me and you will get the error.

```
git clone https://github.com/linuxserver/docker-plex.git
cd docker-plex
docker build \
  --no-cache \
  --pull \
  -t linuxserver/plex:latest .
```

## Environment
**OS:**      not relevant as the problem is happening *during the execution of the build (Dockerfile commands)*, but Arch Linux up-to-date, docker version 19.03.5-ce
**CPU architecture:** x86_64
**How docker service was installed:**  arch package, notrhing special

## Command used to create docker container (run/create/compose/screenshot)

@see "how to reproduce" section

## Docker logs

No logs outside build results.

**Comment by james-d-elliott** [comment]
Might be due to upstream changes: https://forums.plex.tv/t/plex-media-server-linux-installation-packaging-update-issues/529917/60

**Comment by aptalca** [comment]
We're working with them and a solution to the issue has been found. The next version should build fine

**Comment by james-d-elliott** [comment]
@SR-G  also as per the change logs, 1.18.5.2260-056ab4be9 is the latest version with changes that should impact users. If you want to build this specifically for some reason (it's available from the docker.io/linuxserver/plex:latest image already) you can do this I believe:

docker build \
  --build-arg PLEX_RELEASE=1.18.5.2260-056ab4be9 \
  --no-cache \
  --pull \
  -t linuxserver/plex:latest .

**Comment by SR-G** [comment]
Not sure it is working for now, on my side with `build-arg PLEX_RELEASE=1.18.5.2260-056ab4be9` i get the other error referenced earlier in the linked thread, like :

```
PlexMediaServer install: Pre-installation Validation.
PlexMediaServer install: ERROR:  Plex Media Server can only be installed on 'init' or 'systemd' based systems.
PlexMediaServer install:         Your system has sh but minimally required files are missing.
```

But no problem, i'll wait for next PLEX version with the installation behavior inside docker being fixed.

**Comment by aptalca** [comment]
Why are you trying build it locally? You can just just pull linuxserver/plex and it will get you that version

**Comment by SR-G** [comment]
... i'm of course just willing to get the very latest version, not available inside the docker image at this time, hence the local compilation (which is giving the error currently discussed here), that's all (i'm not willing to use the previous one, it was just a try after @james-d-elliott suggestion).

**Comment by aptalca** [comment]
The reason the latest is not on docker hub is because it is not building (not because we haven't gotten to it). Our ci checks for new releases hourly and pushes to the hub as soon as it builds.

If you have Plex pass, pull the latest image from the hub, and let it update to the latest Plex version during container start.

**Comment by cutzenfriend** [comment]
Hi, there is already a new Version 1.18.6.... from 04. Feb.
When will the new latest build cover that version?

**Comment by cutzenfriend** [comment]
> 
> 
> The reason the latest is not on docker hub is because it is not building (not because we haven't gotten to it). Our ci checks for new releases hourly and pushes to the hub as soon as it builds.
> 
> If you have Plex pass, pull the latest image from the hub, and let it update to the latest Plex version during container start.

And how can I do that?

**Comment by aptalca** [comment]
Latest public release is still 18.5

> And how can I do that?
You can read the readme, it's all in there

**Comment by nemchik** [comment]
This should be resolved now. The latest public release is now https://github.com/linuxserver/docker-plex/releases/tag/1.18.9.2578-513b381af-ls87
