### ISSUE TITLE
Specifying advanced hidden settings

### ISSUE THREAD

**Issue by rcdailey** [linuxserver/docker-plex#223]
There is a page that documents hidden server settings for Plex [here](https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/). One in particular I'm interested in is `PLEX_MEDIA_SERVER_USE_SYSLOG`.

How does one specify this setting using the LSIO docker container? I did some grepping inside the container directory structure and found this file which has it commented out:

    /usr/lib/plexmediaserver/lib/plexmediaserver.default

Does the Docker image need to support specifying these in some special way? Or can I simply define it as an environment variable when creating the container?

**Comment by rcdailey** [comment]
As another test, I created a local file named `plexmediaserver.conf` with the following in it:

    export PLEX_MEDIA_SERVER_USE_SYSLOG=true

And mapped it to the container like this (relevant entry in my `docker_compose.yml` file):

    - ./plexmediaserver.conf:/etc/default/plexmediaserver:ro

However I did not observe any additional logs in the `docker log -f` output for the plex container.

**Comment by aptalca** [comment]
`Preferences.xml` is in your config folder

**Comment by rcdailey** [comment]
@aptalca `Preferences.xml` doesn't have an option to redirect Plex logs to syslog. It also doesn't seem to be related to the "hidden settings" I pointed to in my OP. Can you add some more detail explaining how this solves the problem?

**Comment by james-d-elliott** [comment]
@rcdailey if setting the environment didn't work you may want to try a custom script:
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/#custom-scripts

In the script it would just need the following:
```
#!/usr/bin/with-contenv bash
export PLEX_MEDIA_SERVER_USE_SYSLOG=true
```

However keep in mind this is in the context of a container.. you will have to configure the container in such a way that it has access to the hosts syslog: https://docs.docker.com/config/containers/logging/syslog/

**Comment by rcdailey** [comment]
@james-d-elliott I am actually using a logging driver right now but the problem is, Plex logs do not show up when I do `docker log`. If we can get that working, then the logging driver will work perfectly. Is there an easier way to get the plex LOG files redirected to stdout so that the logging driver can pick them up?

**Comment by james-d-elliott** [comment]
Create a custom script like below using the plex log file locations:

/config/custom-cont-init.d/plex-logs-stdout.sh
```
#!/bin/bash
echo "Setting up PMS logs to write to stdout"
ln -sf /dev/stdout /path/to/log/file1.log
ln -sf /dev/stdout /path/to/log/file2.log
```

Delete all the logs if they live on persistent volumes, and voila. They will write to stdout instead of the log files. Keep in mind if you run anything that uses plex logs (i.e. tautulli), it will no longer work.
