### ISSUE TITLE
Unhealthy container status due to missing healthcheck

### ISSUE THREAD

**Issue by bumjrah** [linuxserver/docker-plex#229]
Please add healthcheck script on startup. Even though effect is mostly cosmetic and container still runs without issues. Unhealthy status on docker dashboards sounds unnecessary alarm & is rather an eye-sore.

**Comment by aptalca** [comment]
We have no plans for it.

See here on how to customize your container: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by bumjrah** [comment]
Container modification is not a feasible alternative. The problem is with the setup.

Plex in the container (for some reason) starts up with healthcheck command. Not anyone's fault really. But the same issued health check looks for a healthcheck.sh script that should be located on the root path. But missing on a fresh start on the container. 

This is the inconsistency that am pointing out here. And I do not think any container mods are required for the missing healthcheck.sh file.

**Comment by tobbenb** [comment]
As aptalca said, we don't have any plans to add it. We don't add health check in our containers.

**Comment by aptalca** [comment]
I don't know what you mean by `Plex in the container (for some reason) starts up with healthcheck command`

You need to provide more context. What docker dashboard are you referring to? Errors where?

You can customize all aspects of the containers with the link I provided

**Comment by bumjrah** [comment]
> I don't know what you mean by `Plex in the container (for some reason) starts up with healthcheck command`
> 
> You need to provide more context. What docker dashboard are you referring to? Errors where?
> 
> You can customize all aspects of the containers with the link I provided

![Screenshot_2020-05-19-14-19-19-962_com android chrome](https://user-images.githubusercontent.com/26869897/82320396-dcd42680-99db-11ea-9eea-3a0c71622da7.jpg)

**Comment by bumjrah** [comment]
Further reference

https://github.com/docker-library/cassandra/pull/76#issuecomment-426816911

**Comment by NetVN** [comment]
add your compose.yaml

`    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s
`
