### ISSUE TITLE
Metadata won't load Plex docker

### ISSUE THREAD

**Issue by vianney78** [linuxserver/docker-plex#231]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Hello, i don't have the informations about series/films on plex, any idea,
## Current Behavior

no informations on the serie
## Steps to Reproduce

1.
![image](https://user-images.githubusercontent.com/33661575/83205709-9905bd80-a14f-11ea-9a6b-02a21764979a.png)

2.
3.
4.

## Environment
**OS:**       Openmediavault docker
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

https://www.youtube.com/watch?v=BNfk7ji4oh4

**Comment by aptalca** [comment]
that looks like a plex issue and should be reported to them on their forums

**Comment by vianney78** [comment]
It only do me that with this docker repo

**Comment by aptalca** [comment]
you didn't really fill out the template so I don't know what to tell you
