### ISSUE TITLE
Not an issue, more of a documentation thing

### ISSUE THREAD

**Issue by bigdant** [linuxserver/docker-plex#233]
most people are storing their plex metadata on a seperate SSD as per instructions from bytemybits and space invader one.

However your docker will only run plex transcoding correctly if the "Unassigned devices" SSD is formated in XFS and nothing else, BTFS for example.

I think you might want to log this somewhere as you provide the ability to host the plex meta data elsewhere as a variable in your docker, it would be great to highlight this issue.

..... GREAT work by the way.

Cheers

D.

**Comment by IronicBadger** [comment]
@bigdant what do you mean by 'unassigned devices' ssd?

**Comment by KillahB33** [comment]
> @bigdant what do you mean by 'unassigned devices' ssd?

I am going to reply cause he isn't, this is an unraid specific thing. Personally this should be documented on that side as this doesn't affect most container users.
