### ISSUE TITLE
"No soup for you!" authentication error

### ISSUE THREAD

**Issue by DoubleHub** [linuxserver/docker-plex#234]
The container itself works fine and builds without any error, but when I try to access it via Chrome and login with my own Plex account (created separately on the official Plex website with email/password) the page responds with the following message:

> No soup for you!
> 
> The server you're trying to access doesn't want to let you in. Make sure you're signed in as a user with access to this server.

Is this a configuration problem? I don't see anything regarding username/password auth inside the docs... am I missing something? Thank you for the image btw it's very very good!

**Comment by drizuid** [comment]
Did you obtain the plex claim token using the same account you're trying to login with? This is most definitely a plex issue and not a container issue though.

**Comment by DoubleHub** [comment]
> Did you obtain the plex claim token using the same account you're trying to login with? This is most definitely a plex issue and not a container issue though.

Yep, I solved it this way. I got a lot of help from the official Discord server, so props to them!
