### ISSUE TITLE
Fresh install does not start Plex Media Server

### ISSUE THREAD

**Issue by svloosbroek** [linuxserver/docker-plex#237]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Plex Media Server should launch but doesn't

## Current Behavior
The Plex frontend is available and you're able to create an account but there's no Media Server running

## Steps to Reproduce
1. Start a new docker-compose stack using the template provided with a new persistent volume for the /config

## Environment
**OS:**      Ubuntu 18.04 LTS
**CPU architecture:** arm32
**How docker service was installed:**      
Through APT

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - plex_config:/config
      - nas-vol:/mnt/video
    restart: unless-stopped

volumes:
  nas-vol:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas.fritz.box,rw,noatime,rsize=32768,wsize=32768,tcp,timeo=14"
      device: ":/volume1/video"

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing...
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
Docker is used for versioning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --platformVersion arg Platform version string
  --vendor arg          Vendor string
  --device arg          Device string
  --model arg           Device model string
  --sentryUrl arg       Sentry URL to upload to
  --sentryKey arg       Sentry Key for the project
  --version arg         Version of the product
  --allowRetries arg    Whether we will allow retries

**Comment by aptalca** [comment]
It looks like it started fine

**Comment by svloosbroek** [comment]
Thanks for checking. Is there any way I can see why the Media Server is failing?

**Comment by aptalca** [comment]
It's not failing. Let's eliminate the xy problem and just tell us what you expect to happen and what you observe

**Comment by svloosbroek** [comment]
I got it running by adding a claim so apparently that's not optional. I also needed to mount my video files to another directory than /mnt/video or /media. Now it's working, thank you for your time.

**Comment by aptalca** [comment]
It is optional with host networking but you need to connect from the same subnet
