### ISSUE TITLE
HW encode not working in version-1.20.2.3402-0fec14d92

### ISSUE THREAD

**Issue by Heliem** [linuxserver/docker-plex#238]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Both decode and encode should use GPU like this:
![Screenshot 2020-10-09 at 11 34 52](https://user-images.githubusercontent.com/6516525/95574799-794ba380-0a25-11eb-94e8-7d47954671af.png)

## Current Behavior

Only decode is working like this:
![Screenshot 2020-10-09 at 11 35 49](https://user-images.githubusercontent.com/6516525/95574839-8cf70a00-0a25-11eb-8c52-10052551a96e.png)

## Steps to Reproduce

1. Run container version-1.20.2.3402-0fec14d92 with --gpus all
2. Check tautulli or plex dashboard

## Environment
**OS:** Debian GNU/Linux 10 (buster) - Kernel: Linux 5.4.65-1-pve
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by mhbates** [comment]
Just noticed the same issue on my end, although I'm using the official Plex docker. Have you figured it out?

**Comment by mhbates** [comment]
I spoke too soon. It looks like the latest versions of Plex now require newer Nvidia drivers, version 450.66. On Buster, you would need to use the backports repo to get it.

Unfortunately for me, Stretch isn't getting that version. Guess it's time to upgrade.

More info:
https://www.reddit.com/r/PleX/comments/j426ha/help_request_hardware_encoding_on_debian_9/
https://www.reddit.com/r/unRAID/comments/j3272i/warning_to_those_using_nvidia_plugin_for_plex/
