### ISSUE TITLE
Trouble getting HDR tone mapping working on intel IGP

### ISSUE THREAD

**Issue by joemiller** [linuxserver/docker-plex#244]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Expecting HW tonemapping via intel GPU on latest plex 1.2. Instead, I get this error/warning from Plex when transcoding HDR content and cpu usage is high - 400-450% on Intel i5-9400

```
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
```

## Current Behavior

Plex (and other OpenCL related utils) are unable to see the intel GPU and OpenCL is not available

## Steps to Reproduce

This might be related to versions of packages between ubuntu 18.04 which this image currently uses and 20.04. I am able to get a successful `clinfo` response on 20.04 but not 18.04.

```console
$ docker run --rm -it  --device /dev/dri:/dev/dri ubuntu:18.04 /bin/bash -c 'apt update && apt-get -qy install clinfo beignet-opencl-icd && clinfo -l'

beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
Platform #0: Intel Gen OCL Driver
```

```console
$ docker run --rm -it  --device /dev/dri:/dev/dri ubuntu:20.04 /bin/bash -c 'apt update && apt-get -qy install clinfo beignet-opencl-icd && clinfo -l'

Platform #0: Intel Gen OCL Driver
 `-- Device #0: Intel(R) UHD Graphics Coffee Lake Desktop GT2
```

## Environment
**OS:** ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** from docker's apt repo

**Comment by joemiller** [comment]
I am able to get HW supported tone-mapping working correctly by forking this repo and switching the base image to ubuntu 20.04 (focal). I think there's something different in some package in 18.04 vs 20.04 but I can't see what it might be.

```diff
-FROM ghcr.io/linuxserver/baseimage-ubuntu:bionic
+FROM ghcr.io/linuxserver/baseimage-ubuntu:focal
```

I understand simply switching to 20.04 may be problematic for the reasons in #236 however.

**Comment by Roxedus** [comment]
We are aware of this, and have done some internal discussion regarding the linked issue. You would be happy to see #245

**Comment by dolohow** [comment]
I have the very same problem now, but it used to work fine.

Inside docker container:
```
clinfo -l
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
Platform #0: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) UHD Graphics 630 [0x9bc5]
Platform #1: Intel Gen OCL Driver
```

**Comment by dolohow** [comment]
I think it started to work for me two months ago or something.  Error message is still there, but HDR tone mapping is in fact hardware accelerated.  Perhaps you are using some old version of this container?

**Comment by Presjar** [comment]
I believe this bug needs to be open again. I have the same issue but with UHD Graphics 750 when tone mapping is enabled. I also get corrupted visual output on the transcode.

![Screenshot_20210724-113155_Plex thumb jpg 1d18a88ea7d6b97452fbcefbd4c0c895](https://user-images.githubusercontent.com/18156203/127130999-4fd025ef-6838-4785-9343-42f6cbca4adf.jpg)

`beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)`
