### ISSUE TITLE
New build on nvidia docker doesn't work, OCI error

### ISSUE THREAD

**Issue by MingyaoLiu** [linuxserver/docker-plex#249]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If possible please provide some clarity on what's changed, and why updating from the linuxserver/plex from 6 days ago to the new one that is 3 days ago, causing my container to not be able to use nvidia runtime.
Thank you.

------------------------------

## Expected Behavior
Expect server to still function after upgrading from version-1.20.5.3600-47c0d9038 to version-1.21.0.3616-d87012962

## Current Behavior
OCI error when use nvidia runtime.

Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 127\\\\n\\\"\"": unknown
Error: failed to start containers: ff1d04969078

## Steps to Reproduce
OS is Debian 20.10 x64
I'm using a Nvidia Quadro P620, with the latest nvidia container service driver installed.
I think the new plex version switched runtime from cuda-10.x to cuda-11.0 ? If there is any insight on why OCI is failing that would be great.
I have tested on nvidia's official 10.2 cuda container, seems to work fine, however when I test nvidia's offical 11.1 cuda container, it is showing the same error when I want to invoke nvidia-smi.

## Environment
**OS: Debian 20.10 x64
**CPU architecture: x86_64
**How docker service was installed: offical dockerhub repo

## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=plexmothership \
  --net=host \
  -e PUID=1001 \
  -e PGID=1003 \
  -e TZ="US/Eastern" \
  -e VERSION=docker \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -v /mnt/nvme/plex_config:/config \
  -v /mnt/nvme/plex_transcoder:/transcode \
  -v /mnt/hdd/plex/TV\ Show:/data/TVShow \
  --runtime=nvidia \
  --restart unless-stopped \
linuxserver/plex 

## Docker logs

No log when I run this command. only the console error I have listed in behavior.

**Comment by j0nnymoe** [comment]
`I have tested on nvidia's official 10.2 cuda container, seems to work fine, however when I test nvidia's offical 11.1 cuda container, it is showing the same error when I want to invoke nvidia-smi." I would say this is an issue with the nvidia container rather than our plex container if nvidia-smi is broken.

**Comment by jhlockha** [comment]
I had the same problem. I switched from linuxserver/plex:latest to linuxserver/plex:bionic and the container was able to start.

**Comment by MingyaoLiu** [comment]
thanks for the info, i will test it out this week.
