### ISSUE TITLE
Download not available 

### ISSUE THREAD

**Issue by openam** [linuxserver/docker-plex#25]
I restarted my plex container and now I'm seeing this error in the docker logs. 

```--2016-03-05 03:55:14--  https://downloads.plex.tv/plex-media-server//plexmediaserver__amd64.deb
Resolving downloads.plex.tv (downloads.plex.tv)... 104.20.6.9, 104.20.7.9, 2400:cb00:2048:1::6814:709, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|104.20.6.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-05 03:55:14 ERROR 404: Not Found.```

**Comment by openam** [comment]
It looks like it's because I'm using the plexpass option and it's using this URL https://tools.linuxserver.io/latest-plexpass.json. Here is the current response. 

```
{
    "last_checked": 1457150681,
    "version": ""
}
```

**Comment by ninpucho** [comment]
I submitted a pull request for a work around to skip the update if the version number comes back blank.
