### ISSUE TITLE
Plex server do not work on raspberypi 4 NAS

### ISSUE THREAD

**Issue by Imantsg** [linuxserver/docker-plex#252]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I can run plex media server in docker container

## Current Behavior
It is not working and I can't claim it. I tried to follow this guide
https://forums.plex.tv/t/unable-to-claim-server/213196
It allowed me to claim server but claim failed

## Steps to Reproduce
1. docker pull ghcr.io/linuxserver/plex
2. docker run -d \
  --name=plex \
  -e PUID=$(id -u pi) \
  -e PGID=$(id -g pi) \
  -e VERSION=docker \
  -e UMASK_SET=022 `#optional` \
  -e PLEX_CLAIM= `#optional` \
  -v /srv/dev-disk-by-label-Media/config/plex:/config \
  -v /srv/dev-disk-by-label-Media/plex:/library \
  -p 32400:32400 \
  --restart unless-stopped \
  ghcr.io/linuxserver/plex
3. try to acess http://<nas server ip address>:32400 and server is not even detected
4. create ssh tunel ssh -L 8888:127.0.0.1:32400 <nas server ip address>
5. Sees new server but failes to create it

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** arm32
**How docker service was installed:** sudo apt-get install docker.io

## Command used to create docker container (run/create/compose/screenshot)
docker run -d \
  --name=plex \
  -e PUID=$(id -u pi) \
  -e PGID=$(id -g pi) \
  -e VERSION=docker \
  -e UMASK_SET=022 `#optional` \
  -e PLEX_CLAIM= `#optional` \
  -v /srv/dev-disk-by-label-Media/config/plex:/config \
  -v /srv/dev-disk-by-label-Media/plex:/library \
  -p 32400:32400 \
  --restart unless-stopped \
  ghcr.io/linuxserver/plex

## Docker logs
[logs.tar.gz](https://github.com/linuxserver/docker-plex/files/5649448/logs.tar.gz)

**Comment by Roxedus** [comment]
Dupe of #247

**Comment by Imantsg** [comment]
using bionic tag and this workround 
https://forums.plex.tv/t/unable-to-claim-server/213196
helped me to claim server
