### ISSUE TITLE
Error starting critical core addon.

### ISSUE THREAD

**Issue by commanderpyle** [linuxserver/docker-plex#253]
plex    |           _         ()
plex    |          | |  ___   _    __
plex    |          | | / __| | |  /  \
plex    |          | | \__ \ | | | () |
plex    |          |_| |___/ |_|  \__/
plex    |
plex    |
plex    | Brought to you by linuxserver.io
plex    | -------------------------------------
plex    |
plex    | To support LSIO projects visit:
plex    | https://www.linuxserver.io/donate/
plex    | -------------------------------------
plex    | GID/UID
plex    | -------------------------------------
plex    |
plex    | User uid:    1000
plex    | User gid:    1000
plex    | -------------------------------------
plex    |
plex    | [cont-init.d] 10-adduser: exited 0.
plex    | [cont-init.d] 40-chown-files: executing...
plex    | [cont-init.d] 40-chown-files: exited 0.
plex    | [cont-init.d] 45-plex-claim: executing...
plex    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
plex    |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--   10737d --:--:--     0
plex    | Unable to claim Plex server. Either manually claim by connecting to http://serverip:32400/web from the same network subnet, or recreate container with a new claim token.
plex    | [cont-init.d] 45-plex-claim: exited 0.
plex    | [cont-init.d] 50-gid-video: executing...
plex    | [cont-init.d] 50-gid-video: exited 0.
plex    | [cont-init.d] 60-plex-update: executing...
plex    | Docker is used for versioning skip update check
plex    | [cont-init.d] 60-plex-update: exited 0.
plex    | [cont-init.d] 99-custom-scripts: executing...
plex    | [custom-init] no custom files found exiting...
plex    | [cont-init.d] 99-custom-scripts: exited 0.
plex    | [cont-init.d] done.
plex    | [services.d] starting services
plex    | [services.d] done.
plex    | Starting Plex Media Server.
plex    | Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-b509cc236/OpenSubtitles.bundle.
plex    | Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-b509cc236/LyricFind.bundle.
plex    | Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-b509cc236/PlexMusic.bundle.

**Comment by aptalca** [comment]
Duplicate #247
