### ISSUE TITLE
Plex CPU ist exploding with the last Branch

### ISSUE THREAD

**Issue by kostak79** [linuxserver/docker-plex#254]
With the last update is my Docker Image above 400 % of CPU Power. It does 'nt go down anymore. The Last Image have'nt this Issues.

Can you help me?
I user an RPB4 with OMV 5.x
thx

**Comment by yllekz** [comment]
It's not OMV causing this. Refer to these two links:

https://github.com/linuxserver/docker-plex/issues/248
https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal


TL;DR: switch to the "bionic" tag for a quick fix.

**Comment by kostak79** [comment]
> It's not OMV causing this. Refer to these two links:
> 
> #248
> https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal
> 
> TL;DR: switch to the "bionic" tag for a quick fix.

Thx!! That was the trick. With the Bionic Tag everything is working fine.

**Comment by j0nnymoe** [comment]
@kostak79 bare in mind, if you don't do the fix, more images we move over to focal, the more you'll have this issue with. We don't plan to add bionic tags for every container we switch to focal.

**Comment by kostak79** [comment]
> @kostak79 bare in mind, if you don't do the fix, more images we move over to focal, the more you'll have this issue with. We don't plan to add bionic tags for every container we switch to focal.

Thanks for the hint. its done in this second. i've have the actual Image of Buster installed. I've put the backports Repository in and upgrade the installation. Thank you.
