### ISSUE TITLE
Add Intel NEO driver

### ISSUE THREAD

**Issue by jyggen** [linuxserver/docker-plex#255]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Add Intel NEO driver similar to https://github.com/plexinc/pms-docker/pull/62.

------------------------------

## Desired Behavior
Utilize the support for the Intel Compute Runtime OpenCL driver versions 20.36 and later added in PMS 1.21.1.3766.

## Current Behavior
HDR->SDR tone mapping is not utilizing HW transcoding on newer integrated GPU models.

**Comment by tobbenb** [comment]
We already created a new branch for it, the opencl branch, and awaiting test results from the tester.

**Comment by aptalca** [comment]
@jyggen can you test this image and confirm it works? We created that branch a while back but couldn't find any testers with latest gen igpu?
`lspipepr/plex:amd64-1.21.1.3830-6c22540d5-pkg-646b1751-pr-256`
Just replace `linuxserver/plex` with that and recreate the container

Thanks

**Comment by jyggen** [comment]
@aptalca: I've tested it now and it seems to work just fine.

With current `latest` tag, CPU is at ~80% and Plex don't mention hw:
![image](https://user-images.githubusercontent.com/264300/102665312-f82b2e00-4184-11eb-92fe-360bc388f9ba.png)

With the image and tag in your comment, CPU is at ~10% and Plex says it's hw:
![image](https://user-images.githubusercontent.com/264300/102665192-aedade80-4184-11eb-9286-8bf9eee695c0.png)
