### ISSUE TITLE
Portainer Container unhealthy - "/bin/sh: 1: /healthcheck.sh: not found"

### ISSUE THREAD

**Issue by TheBR** [linuxserver/docker-plex#257]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container should start in a healthy state

## Current Behavior

Container starts unhealthily, reports that healthcheck.sh is not found

## Steps to Reproduce

1. Launch Container with ghcr.io/linuxserver/plex:latest
2. Wait
3. Container starts but reports as unhealthy
4. Click on Container - look at Container Health - shows Unhealthy and reports 

Last output | /bin/sh: 1: /healthcheck.sh: not found

## Environment
**QNAP QTS NAS:**
**CPU architecture:** https://ark.intel.com/content/www/us/en/ark/products/197305/intel-celeron-processor-j4125-4m-cache-up-to-2-70-ghz.html
**How docker service was installed:**
Part of NAS software.

## Command used to create docker container (run/create/compose/screenshot)

Not sure how to provide the command used to run from portainer.

## Docker logs

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing...
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
No update required
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.

**Comment by tobbenb** [comment]
We don't support healthcheck. See here https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863
