### ISSUE TITLE
Crypto Malware like behaviour

### ISSUE THREAD

**Issue by DavidSpek** [linuxserver/docker-plex#258]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

With the latest image, the Plex Media Server is spawning a huge number of transcode streams even though nothing is being played. I noticed this as my P2000 was handling 30 "streams" and my CPU usage went up to 100% (dual Xeon E5-2650v2). Restarting the container first helped, but then did not anymore. When I tested with the previous version, I also noticed there was an issue with using the actual GPU. Manually making it transcode would start a transcode stream on the GPU, changing the quality or starting a new stream would fail to bind to the GPU it seems. This is an image of nvidia-smi after the container just started and there are no active streams. 

 ![image](https://user-images.githubusercontent.com/28541758/104134977-62eb1600-538d-11eb-969a-f07a5676913f.png)
------------------------------

## Expected Behavior
Only active transcoding streams should be using the GPU for transcoding. 

![image](https://user-images.githubusercontent.com/28541758/104134977-62eb1600-538d-11eb-969a-f07a5676913f.png)

## Environment
**OS:** Unraid
**CPU architecture:** x86_64/arm32/arm64, NVIDIA P2000
**How docker service was installed:**
The template. Container version:- 1.21.1.3876-3c3adfcb4-ls15

**Comment by Roxedus** [comment]
We are still waiting on a properly filled issue.

**Comment by DavidSpek** [comment]
I haven't experienced the problem any more and I could not find anything in the logs so I will close the issue.
