### ISSUE TITLE
libicudataplex.so.67: cannot open shared object file

### ISSUE THREAD

**Issue by rhinot** [linuxserver/docker-plex#264]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

"libicudataplex.so.67: cannot open shared object file"

Also reported in wild:
https://www.reddit.com/r/PleX/comments/m6kpg3/new_beta_pms_version_available_12214200c073686f2/

Just wanted to make sure the issue was tracked.

------------------------------

## Expected Behavior
Media Server starts

## Current Behavior
Error in logs when trying to run latest server:
> Starting Plex Media Server.,
> /usr/lib/plexmediaserver/Plex Media Server: error while loading shared libraries: libicudataplex.so.67: cannot open shared object file: No such file or directory,

## Steps to Reproduce
1. Docker run Plex armhf image version:- 1.22.0.4163-d8c4875dd-ls33 Build-date:- 2021-03-16T04:04:24+00:00
sha256:59b44364851aaee3efa155b997079f77f1044f433e14eefc1dfca1b088f5ff0b
Run with environment variable "VERSION = latest"

## Environment
**OS:** Raspbian 10 Buster
**CPU architecture:** armhf
**How docker service was installed:**
Official docker repo for armhf, as outlined here: https://docs.docker.com/engine/install/debian/#install-using-the-repository

## Command used to create docker container (run/create/compose/screenshot)
Used plex template via portainer from this template list:
https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json

Changed PGID to 1000 and shifted config directory to a custom local bind.
Key point: VERSION=latest

## Docker logs
> Starting Plex Media Server.,
> /usr/lib/plexmediaserver/Plex Media Server: error while loading shared libraries: libicudataplex.so.67: cannot open shared object file: No such file or directory,
on repeat...

## Workaround
Until plexpass image is fixed, set environmental variable "VERSION=public"

**Comment by EVOTk** [comment]
Hello,
plex fixed this in the version 1.22.2.4264

https://forums.plex.tv/t/linux-pms-error-loading-libicudataplex-so-67-ver-1-22-1-4200-c073686f2/701481/44

**Comment by rhinot** [comment]
@EVOTk thanks for the heads up!
[Docker hub](https://hub.docker.com/r/linuxserver/plex/tags?page=1&ordering=last_updated) not updated to that version yet. Will verify once it is.
