### ISSUE TITLE
Container does not use GPU for hardware transcoding and i dont know why!

### ISSUE THREAD

**Issue by YonHj** [linuxserver/docker-plex#265]
This is my docker run comman 
`docker run -d \
  --name=Plex \
  --net=host \
  -e PUID=997 \
  -e PGID=100 \
  -e VERSION=latest \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e PLEX_CLAIM= `#optional` \
  -v /srv/dev-disk-by-label-RAIDVolume/Config/Plex:/config \
  -v /srv/dev-disk-by-label-RAIDVolume/Media/TV:/tv \
  -v /srv/dev-disk-by-label-RAIDVolume/Media/Movies:/movies \
  --restart unless-stopped \
  --device=/dev/dri:/dev/dri \
    --device=/dev/dri/card0:/dev/dri/card0 \
   --device=/dev/dri/renderD128:/dev/dri/renderD128 \
  --runtime=nvidia \
  ghcr.io/linuxserver/plex `

Everything works fine except the hardware transcoding. In the dashboard I dont see the (hw), which probably means that there is no hardware transcoding at all.

I can run the command below and it seems to give me the correct result 
`docker run --gpus all nvidia/cuda:10.0-base nvidia-smi `

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   44C    P5    20W / 198W |      0MiB /  8118MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

If there's anything else needed i will provide it. Im a beginner with this

**Comment by tobbenb** [comment]
Please fill in the issue template.
