### ISSUE TITLE
Cannot get hardware transcoding to work

### ISSUE THREAD

**Issue by YonHj** [linuxserver/docker-plex#266]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I can't seem to get hardware accelerated transcoding to work inside the plex container. I dont see the (hw) in the Plex dashboard with the video stream information. I'm quite the beginner when it comes to this and would appreciate all the help i can get.
------------------------------

## Expected Behavior
Hardware accelerated transcoding should be enabled, both for the CPU and GPU. I have enabled the settings for hardware acceleration in the Plex GUI settings. It should be using the GPU to transcode video but both `nvidia-smi` and nvtop shows no GPU usage. nvidia-smi says no running processes as well.

## Current Behavior
It only uses software transcoding, i dont see the (hw) on the Plexdashboard. Inside the container in /dev/dri exists card0 and renderD128. 
`sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`
This command is supposed to test the install of nvidia-docker, and it seems to be working fine. 

## Steps to Reproduce

1. https://wiki.debian.org/NvidiaGraphicsDrivers#Version_460.39_.28via_buster-backports.29 was used to install the nvidia drivers. 
2. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker then this link to install nvidia-docker.
3.
4.

## Environment
**OS:**
Debian GNU/Linux 10 (buster)
**CPU architecture:** x86_64
**How docker service was installed:**
Docker was installed using the OMV-extras repo in OpenMediaVault. 

## Command used to create docker container (run/create/compose/screenshot)
`docker run -d \
  --name=Plex \
  --net=host \
  -e PUID=997 \
  -e PGID=100 \
  -e VERSION=docker \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e PLEX_CLAIM= `#optional` \
  -v /srv/dev-disk-by-label-RAIDVolume/Config/Plex:/config \
  -v /srv/dev-disk-by-label-RAIDVolume/Media/TV:/tv \
  -v /srv/dev-disk-by-label-RAIDVolume/Media/Movies:/movies \
  --restart unless-stopped \
  --device=/dev/dri:/dev/dri \
    --device=/dev/dri/card0:/dev/dri/card0 \
   --device=/dev/dri/renderD128:/dev/dri/renderD128 \
  --runtime=nvidia \
  ghcr.io/linuxserver/plex `

## Docker logs
`
Critical: libusb_init failed

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

usermod: no changes

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    997

User gid:    100

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 40-chown-files: executing... 

[cont-init.d] 40-chown-files: exited 0.

[cont-init.d] 45-plex-claim: executing... 

[cont-init.d] 45-plex-claim: exited 0.

[cont-init.d] 50-gid-video: executing... 

[cont-init.d] 50-gid-video: exited 0.

[cont-init.d] 60-plex-update: executing... 

Docker is used for versioning skip update check

[cont-init.d] 60-plex-update: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Starting Plex Media Server.`

Here are logs from Plex:
https://pastebin.com/wy5P3hP5

**Comment by aptalca** [comment]
Don't map those devices. Nvidia runtime injects the necessary devices

Make sure you have opted pass

**Comment by YonHj** [comment]
> Don't map those devices. Nvidia runtime injects the necessary devices
> 
> Make sure you have plex pass
> 
> Make sure you have transcoding turned on in plex gui settings

Alright, i took out the two devices from the docker run command. I have plex pass and i have enabled hardware transcoding in the gui settings. But it still does not work

**Comment by james-d-elliott** [comment]
As a suggestion you may want to elaborate on what "does not work" means, as well as share plex logs if there was a plex error.

**Comment by YonHj** [comment]
> As a suggestion you may want to elaborate on what "does not work" means, as well as share plex logs if there was a plex error.

Sure, my bad! I edited the post to try to make it clearer and also included logs from plex.
Plex logs: https://pastebin.com/wy5P3hP5
