### ISSUE TITLE
Unable to reach Docker Plex server

### ISSUE THREAD

**Issue by Finn0001** [linuxserver/docker-plex#274]
Hey! I'm trying to get a plex server running through docker and I can't seem to connect to it?
Here's the Docker-compose file I'm using:

version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=###
    volumes:
      - ./data/config:/config
      - ./data/tv:/tv
      - ./data/movies:/movies
    restart: unless-stopped

the container is hosted on 192.168.1.146
I try navigating to 192.168.1.146:32400/web and it says page not found? However, on my docker account "DOCKER-DESKTOP" shows up on my list?

**Comment by azazelpy** [comment]
i have the same issue

**Comment by oliver-la** [comment]
Yeah me too, turns out the issue was iptables. Somehow the rules got screwed up in my case.
Simple fix is to install "ufw", and execute "ufw allow 32400".

**Comment by ecatanzani** [comment]
I have the same issue...

`❯ docker-compose up
Creating plex ... done
Attaching to plex
plex    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
plex    | [s6-init] ensuring user provided files have correct perms...exited 0.
plex    | [fix-attrs.d] applying ownership & permissions fixes...
plex    | [fix-attrs.d] done.
plex    | [cont-init.d] executing container initialization scripts...
plex    | [cont-init.d] 01-envfile: executing... 
plex    | [cont-init.d] 01-envfile: exited 0.
plex    | [cont-init.d] 10-adduser: executing... 
plex    | 
plex    | -------------------------------------
plex    |           _         ()
plex    |          | |  ___   _    __
plex    |          | | / __| | |  /  \
plex    |          | | \__ \ | | | () |
plex    |          |_| |___/ |_|  \__/
plex    | 
plex    | 
plex    | Brought to you by linuxserver.io
plex    | -------------------------------------
plex    | 
plex    | To support LSIO projects visit:
plex    | https://www.linuxserver.io/donate/
plex    | -------------------------------------
plex    | GID/UID
plex    | -------------------------------------
plex    | 
plex    | User uid:    1000
plex    | User gid:    1000
plex    | -------------------------------------
plex    | 
plex    | [cont-init.d] 10-adduser: exited 0.
plex    | [cont-init.d] 40-chown-files: executing... 
plex    | [cont-init.d] 40-chown-files: exited 0.
plex    | [cont-init.d] 45-plex-claim: executing... 
plex    | [cont-init.d] 45-plex-claim: exited 0.
plex    | [cont-init.d] 50-gid-video: executing... 
plex    | [cont-init.d] 50-gid-video: exited 0.
plex    | [cont-init.d] 60-plex-update: executing... 
plex    | Docker is used for versioning skip update check
plex    | [cont-init.d] 60-plex-update: exited 0.
plex    | [cont-init.d] 90-custom-folders: executing... 
plex    | [cont-init.d] 90-custom-folders: exited 0.
plex    | [cont-init.d] 99-custom-scripts: executing... 
plex    | [custom-init] no custom files found exiting...
plex    | [cont-init.d] 99-custom-scripts: exited 0.
plex    | [cont-init.d] done.
plex    | [services.d] starting services
plex    | Starting Plex Media Server.
plex    | [services.d] done.
plex    | Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
plex    | Crash Uploader options (all are required):
plex    |   --directory arg       Directory to scan for crash reports
plex    |   --serverUuid arg      UUID of the server that crashed
plex    |   --userId arg          User that owns this product
plex    |   --platform arg        Platform string
plex    |   --platformVersion arg Platform version string
plex    |   --vendor arg          Vendor string
plex    |   --device arg          Device string
plex    |   --model arg           Device model string
plex    |   --sentryUrl arg       Sentry URL to upload to
plex    |   --sentryKey arg       Sentry Key for the project
plex    |   --version arg         Version of the product
plex    |   --allowRetries arg    Whether we will allow retries

plex    | Critical: libusb_init failed`

**Comment by filipenas** [comment]
for those how have the same issue, just go to: localhost:32400/web 
please try with ip instead of localhost and http or https!

**Comment by drizuid** [comment]
OP did not fill out template completely and none of the "me too" provided any helpful info.
