### ISSUE TITLE
Phone web browser keeps refreshing (Firefox, Google Chrome, Safari, Built in browser android)

### ISSUE THREAD

**Issue by AMunkyCoder** [linuxserver/docker-plex#277]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
All browser keeps refreshing when playing a video, i'm hosting it on my server locally.
on my safari it says "A problem repeatedly occured on 'https://myserver:port....' " 

## Steps to Reproduce
I've used the docker-compose template on hub.docker.com and only changed the volume and removed - PLEX_CLAIM= #optional as it is optional.

Hosting it on a Linux machine.

Tried it on multiple phones and OS iOS and Android same result.
But it works fine on my PC's browser both Firefox and Chrome.

## Environment
**OS:Linux Mint**
**CPU architecture:** x86_64
**How docker service was installed:**

From official linuxserver repo, version 1.23.4.4805
## Command used to create docker container (run/create/compose/screenshot)

---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ....: /config
      - ....: /tv
      - ....: /movies

## Docker logs

Not sure if this matters but it's on the logs.

Critical: libusb_init failed

**Comment by j0nnymoe** [comment]
I don't see how this is a container issue. Report it directly to Plex.
