### ISSUE TITLE
 PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server

### ISSUE THREAD

**Issue by nuttijay** [linuxserver/docker-plex#280]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
should be chowned to PUID/PGID

## Current Behavior
as title states

## Environment
**Linux/Docker:**
**Linux knecht 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux** 
**How docker service was installed:**
docker compose

services:

  infra_plex:
    image: "ghcr.io/linuxserver/plex"
    container_name: "infra_plex"
    networks:
      - "dck2021_infra"
    restart: unless-stopped
    environment:
      - VERSION=docker
      - PUID=17731
      - PGID=773
    volumes:
      - /srv/data/dck2021Infra/plex:/config:rw
   
## Command used to create docker container (run/create/compose/screenshot)
docker-compose \
  --project-name dck2021Infra \
  --file docker-compose.plex.yaml \
  up

## Docker logs
Pulling infra_plex (ghcr.io/linuxserver/plex:)...
latest: Pulling from linuxserver/plex
5bb135ea581c: Pull complete
8b9d11287742: Pull complete
80d56ce7dc3f: Pull complete
8090c45e6ce0: Pull complete
be7d9ab6dc4c: Pull complete
83f65ccd7888: Pull complete
25b4e1fe3bb7: Pull complete
8e4c25536f9b: Pull complete
5c5ae5cc39b9: Pull complete
Digest: sha256:6bb7c9d8f51d5e30835efc172c42a4fd05e8e40e175ac7ec202ab769536bc021
Status: Downloaded newer image for ghcr.io/linuxserver/plex:latest
Creating infra_plex ... done
Attaching to infra_plex
infra_plex    | [mod-init] Attempting to run Docker Modification Logic
infra_plex    | [mod-init] Applying linuxserver/mods:plex-absolute-hama files to container
infra_plex    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
infra_plex    | [s6-init] ensuring user provided files have correct perms...exited 0.
infra_plex    | [fix-attrs.d] applying ownership & permissions fixes...
infra_plex    | [fix-attrs.d] done.
infra_plex    | [cont-init.d] executing container initialization scripts...
infra_plex    | [cont-init.d] 01-envfile: executing... 
infra_plex    | [cont-init.d] 01-envfile: exited 0.
infra_plex    | [cont-init.d] 10-adduser: executing... 
infra_plex    | 
infra_plex    | -------------------------------------
infra_plex    |           _         ()
infra_plex    |          | |  ___   _    __
infra_plex    |          | | / __| | |  /  \
infra_plex    |          | | \__ \ | | | () |
infra_plex    |          |_| |___/ |_|  \__/
infra_plex    | 
infra_plex    | 
infra_plex    | Brought to you by linuxserver.io
infra_plex    | -------------------------------------
infra_plex    | 
infra_plex    | To support LSIO projects visit:
infra_plex    | https://www.linuxserver.io/donate/
infra_plex    | -------------------------------------
infra_plex    | GID/UID
infra_plex    | -------------------------------------
infra_plex    | 
infra_plex    | User uid:    17731
infra_plex    | User gid:    773
infra_plex    | -------------------------------------
infra_plex    | 
infra_plex    | [cont-init.d] 10-adduser: exited 0.
infra_plex    | [cont-init.d] 40-chown-files: executing... 
infra_plex    | [cont-init.d] 40-chown-files: exited 0.
infra_plex    | [cont-init.d] 45-plex-claim: executing... 
infra_plex    | [cont-init.d] 45-plex-claim: exited 0.
infra_plex    | [cont-init.d] 50-gid-video: executing... 
infra_plex    | [cont-init.d] 50-gid-video: exited 0.
infra_plex    | [cont-init.d] 60-plex-update: executing... 
infra_plex    | Docker is used for versioning skip update check
infra_plex    | [cont-init.d] 60-plex-update: exited 0.
infra_plex    | [cont-init.d] 90-custom-folders: executing... 
infra_plex    | [cont-init.d] 90-custom-folders: exited 0.
infra_plex    | [cont-init.d] 98-absolute-hama: executing... 
infra_plex    | **** installing git ****
infra_plex    | Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
infra_plex    | Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
infra_plex    | Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
infra_plex    | Get:4 http://archive.ubuntu.com/ubuntu focal/multiverse Sources [208 kB]
infra_plex    | Get:5 http://archive.ubuntu.com/ubuntu focal/restricted Sources [7,198 B]
infra_plex    | Get:6 http://archive.ubuntu.com/ubuntu focal/universe Sources [12.3 MB]
infra_plex    | Get:7 http://archive.ubuntu.com/ubuntu focal/main Sources [1,079 kB]
infra_plex    | Get:8 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
infra_plex    | Get:9 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,275 kB]
infra_plex    | Get:10 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
infra_plex    | Get:11 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
infra_plex    | Get:12 http://archive.ubuntu.com/ubuntu focal-updates/universe Sources [230 kB]
infra_plex    | Get:13 http://archive.ubuntu.com/ubuntu focal-updates/main Sources [535 kB]
infra_plex    | Get:14 http://archive.ubuntu.com/ubuntu focal-updates/restricted Sources [30.3 kB]
infra_plex    | Get:15 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Sources [20.7 kB]
infra_plex    | Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,058 kB]
infra_plex    | Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,463 kB]
infra_plex    | Get:18 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.8 kB]
infra_plex    | Get:19 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [522 kB]
infra_plex    | Get:20 http://archive.ubuntu.com/ubuntu focal-security/universe Sources [84.8 kB]
infra_plex    | Get:21 http://archive.ubuntu.com/ubuntu focal-security/main Sources [213 kB]
infra_plex    | Get:22 http://archive.ubuntu.com/ubuntu focal-security/multiverse Sources [8,644 B]
infra_plex    | Get:23 http://archive.ubuntu.com/ubuntu focal-security/restricted Sources [30.3 kB]
infra_plex    | Get:24 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [788 kB]
infra_plex    | Get:25 http://archive.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [472 kB]
infra_plex    | Get:26 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,024 kB]
infra_plex    | Get:27 http://archive.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.6 kB]
infra_plex    | Fetched 33.5 MB in 6s (5,342 kB/s)
infra_plex    | Reading package lists...
infra_plex    | Reading package lists...
infra_plex    | Building dependency tree...
infra_plex    | Reading state information...
infra_plex    | The following additional packages will be installed:
infra_plex    |   git-man libcurl3-gnutls liberror-perl libexpat1 libgdbm-compat4 libgdbm6
infra_plex    |   libperl5.30 perl perl-modules-5.30
infra_plex    | Suggested packages:
infra_plex    |   gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
infra_plex    |   git-gui gitk gitweb git-cvs git-mediawiki git-svn gdbm-l10n perl-doc
infra_plex    |   libterm-readline-gnu-perl | libterm-readline-perl-perl make libb-debug-perl
infra_plex    |   liblocale-codes-perl
infra_plex    | Recommended packages:
infra_plex    |   patch less ssh-client netbase
infra_plex    | The following NEW packages will be installed:
infra_plex    |   git git-man libcurl3-gnutls liberror-perl libexpat1 libgdbm-compat4 libgdbm6
infra_plex    |   libperl5.30 perl perl-modules-5.30
infra_plex    | 0 upgraded, 10 newly installed, 0 to remove and 2 not upgraded.
infra_plex    | Need to get 12.7 MB of archives.
infra_plex    | After this operation, 85.8 MB of additional disk space will be used.
infra_plex    | Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 perl-modules-5.30 all 5.30.0-9ubuntu0.2 [2,738 kB]
infra_plex    | Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libgdbm6 amd64 1.18.1-5 [27.4 kB]
infra_plex    | Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libgdbm-compat4 amd64 1.18.1-5 [6,244 B]
infra_plex    | Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libperl5.30 amd64 5.30.0-9ubuntu0.2 [3,952 kB]
infra_plex    | Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 perl amd64 5.30.0-9ubuntu0.2 [224 kB]
infra_plex    | Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libexpat1 amd64 2.2.9-1build1 [73.3 kB]
infra_plex    | Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl3-gnutls amd64 7.68.0-1ubuntu2.6 [231 kB]
infra_plex    | Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 liberror-perl all 0.17029-1 [26.5 kB]
infra_plex    | Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 git-man all 1:2.25.1-1ubuntu3.1 [884 kB]
infra_plex    | Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 git amd64 1:2.25.1-1ubuntu3.1 [4,557 kB]
infra_plex    | Fetched 12.7 MB in 2s (5,645 kB/s)
infra_plex    | Selecting previously unselected package perl-modules-5.30.
(Reading database ... 10541 files and directories currently installed.)
infra_plex    | Preparing to unpack .../0-perl-modules-5.30_5.30.0-9ubuntu0.2_all.deb ...
infra_plex    | Unpacking perl-modules-5.30 (5.30.0-9ubuntu0.2) ...
infra_plex    | Selecting previously unselected package libgdbm6:amd64.
infra_plex    | Preparing to unpack .../1-libgdbm6_1.18.1-5_amd64.deb ...
infra_plex    | Unpacking libgdbm6:amd64 (1.18.1-5) ...
infra_plex    | Selecting previously unselected package libgdbm-compat4:amd64.
infra_plex    | Preparing to unpack .../2-libgdbm-compat4_1.18.1-5_amd64.deb ...
infra_plex    | Unpacking libgdbm-compat4:amd64 (1.18.1-5) ...
infra_plex    | Selecting previously unselected package libperl5.30:amd64.
infra_plex    | Preparing to unpack .../3-libperl5.30_5.30.0-9ubuntu0.2_amd64.deb ...
infra_plex    | Unpacking libperl5.30:amd64 (5.30.0-9ubuntu0.2) ...
infra_plex    | Selecting previously unselected package perl.
infra_plex    | Preparing to unpack .../4-perl_5.30.0-9ubuntu0.2_amd64.deb ...
infra_plex    | Unpacking perl (5.30.0-9ubuntu0.2) ...
infra_plex    | Selecting previously unselected package libexpat1:amd64.
infra_plex    | Preparing to unpack .../5-libexpat1_2.2.9-1build1_amd64.deb ...
infra_plex    | Unpacking libexpat1:amd64 (2.2.9-1build1) ...
infra_plex    | Selecting previously unselected package libcurl3-gnutls:amd64.
infra_plex    | Preparing to unpack .../6-libcurl3-gnutls_7.68.0-1ubuntu2.6_amd64.deb ...
infra_plex    | Unpacking libcurl3-gnutls:amd64 (7.68.0-1ubuntu2.6) ...
infra_plex    | Selecting previously unselected package liberror-perl.
infra_plex    | Preparing to unpack .../7-liberror-perl_0.17029-1_all.deb ...
infra_plex    | Unpacking liberror-perl (0.17029-1) ...
infra_plex    | Selecting previously unselected package git-man.
infra_plex    | Preparing to unpack .../8-git-man_1%3a2.25.1-1ubuntu3.1_all.deb ...
infra_plex    | Unpacking git-man (1:2.25.1-1ubuntu3.1) ...
infra_plex    | Selecting previously unselected package git.
infra_plex    | Preparing to unpack .../9-git_1%3a2.25.1-1ubuntu3.1_amd64.deb ...
infra_plex    | Unpacking git (1:2.25.1-1ubuntu3.1) ...
infra_plex    | Setting up libexpat1:amd64 (2.2.9-1build1) ...
infra_plex    | Setting up perl-modules-5.30 (5.30.0-9ubuntu0.2) ...
infra_plex    | Setting up libcurl3-gnutls:amd64 (7.68.0-1ubuntu2.6) ...
infra_plex    | Setting up git-man (1:2.25.1-1ubuntu3.1) ...
infra_plex    | Setting up libgdbm6:amd64 (1.18.1-5) ...
infra_plex    | Setting up libgdbm-compat4:amd64 (1.18.1-5) ...
infra_plex    | Setting up libperl5.30:amd64 (5.30.0-9ubuntu0.2) ...
infra_plex    | Setting up perl (5.30.0-9ubuntu0.2) ...
infra_plex    | Setting up liberror-perl (0.17029-1) ...
infra_plex    | Setting up git (1:2.25.1-1ubuntu3.1) ...
infra_plex    | Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
infra_plex    | **** no scanner repo found, cloning. ****
infra_plex    | Cloning into '/config/absolute'...
infra_plex    | **** no scanner found. copying from repo ****
infra_plex    | **** no agent found, cloning ****
infra_plex    | Cloning into '/config/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle'...
infra_plex    | [cont-init.d] 98-absolute-hama: exited 0.
infra_plex    | [cont-init.d] 99-custom-scripts: executing... 
infra_plex    | [custom-init] no custom files found exiting...
infra_plex    | [cont-init.d] 99-custom-scripts: exited 0.
infra_plex    | [cont-init.d] done.
infra_plex    | [services.d] starting services
infra_plex    | [services.d] done.
infra_plex    | Starting Plex Media Server.
infra_plex    | PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server
infra_plex    | Starting Plex Media Server.
infra_plex    | PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server
infra_plex    | Starting Plex Media Server.
infra_plex    | PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server
infra_plex    | Starting Plex Media Server.

## Steps to Reproduce

rm -rf /srv.../plex

Starting infra_plex ... done
Attaching to infra_plex
infra_plex    | [mod-init] Attempting to run Docker Modification Logic
infra_plex    | [mod-init] Applying linuxserver/mods:plex-absolute-hama files to container
infra_plex    | [mod-init] linuxserver/mods:plex-absolute-hama at sha256:8f80ff9dd05f0dcd840ae9322938aba8250a040fb224088cddad79b2a8e6b55d has been previously applied skipping
infra_plex    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
infra_plex    | [s6-init] ensuring user provided files have correct perms...exited 0.
infra_plex    | [fix-attrs.d] applying ownership & permissions fixes...
infra_plex    | [fix-attrs.d] done.
infra_plex    | [cont-init.d] executing container initialization scripts...
infra_plex    | [cont-init.d] 01-envfile: executing... 
infra_plex    | [cont-init.d] 01-envfile: exited 0.
infra_plex    | [cont-init.d] 10-adduser: executing... 
infra_plex    | usermod: no changes
infra_plex    | 
infra_plex    | -------------------------------------
infra_plex    |           _         ()
infra_plex    |          | |  ___   _    __
infra_plex    |          | | / __| | |  /  \
infra_plex    |          | | \__ \ | | | () |
infra_plex    |          |_| |___/ |_|  \__/
infra_plex    | 
infra_plex    | 
infra_plex    | Brought to you by linuxserver.io
infra_plex    | -------------------------------------
infra_plex    | 
infra_plex    | To support LSIO projects visit:
infra_plex    | https://www.linuxserver.io/donate/
infra_plex    | -------------------------------------
infra_plex    | GID/UID
infra_plex    | -------------------------------------
infra_plex    | 
infra_plex    | User uid:    17731
infra_plex    | User gid:    773
infra_plex    | -------------------------------------
infra_plex    | 
infra_plex    | [cont-init.d] 10-adduser: exited 0.
infra_plex    | [cont-init.d] 40-chown-files: executing... 
infra_plex    | [cont-init.d] 40-chown-files: exited 0.
infra_plex    | [cont-init.d] 45-plex-claim: executing... 
infra_plex    | [cont-init.d] 45-plex-claim: exited 0.
infra_plex    | [cont-init.d] 50-gid-video: executing... 
infra_plex    | [cont-init.d] 50-gid-video: exited 0.
infra_plex    | [cont-init.d] 60-plex-update: executing... 
infra_plex    | Docker is used for versioning skip update check
infra_plex    | [cont-init.d] 60-plex-update: exited 0.
infra_plex    | [cont-init.d] 90-custom-folders: executing... 
infra_plex    | [cont-init.d] 90-custom-folders: exited 0.
infra_plex    | [cont-init.d] 98-absolute-hama: executing... 
infra_plex    | **** no scanner repo found, cloning. ****
infra_plex    | Cloning into '/config/absolute'...
infra_plex    | **** no scanner found. copying from repo ****
infra_plex    | **** no agent found, cloning ****
infra_plex    | Cloning into '/config/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle'...
infra_plex    | [cont-init.d] 98-absolute-hama: exited 0.
infra_plex    | [cont-init.d] 99-custom-scripts: executing... 
infra_plex    | [custom-init] no custom files found exiting...
infra_plex    | [cont-init.d] 99-custom-scripts: exited 0.
infra_plex    | [cont-init.d] done.
infra_plex    | [services.d] starting services
infra_plex    | [services.d] done.
infra_plex    | Starting Plex Media Server.
infra_plex    | PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server
infra_plex    | Starting Plex Media Server.
infra_plex    | PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server

root@knecht:/srv/data/dck2021Infra# ls -al plex/
ls: Zugriff auf 'plex/' nicht möglich: Datei oder Verzeichnis nicht gefunden
root@knecht:/srv/data/dck2021Infra# ls -al plex/
insgesamt 32
drwxr-xr-x  8 sysmaint nfssystem 4096 Aug 17 20:46 .
drwxr-xr-x 10 sysmaint nfssystem 4096 Aug 17 20:46 ..
drwxr-xr-x  5 root     root      4096 Aug 17 20:46 absolute
drwxr-xr-x  2 root     root      4096 Aug 17 20:46 custom-cont-init.d
drwxr-xr-x  2 root     root      4096 Aug 17 20:46 custom-services.d
drwxr-xr-x  3 sysmaint nfssystem 4096 Aug 17 20:46 Library
drwxr-xr-x  2 sysmaint nfssystem 4096 Aug 17 20:46 passwordfile
drwxr-xr-x  2 sysmaint nfssystem 4096 Aug 17 20:46 userfile
root@knecht:/srv/data/dck2021Infra# ls -al plex/Library/Application\ Support/Plex\ Media\ Server/
insgesamt 16
drwxr-xr-x 4 root     root      4096 Aug 17 20:46 .
drwxr-xr-x 3 sysmaint nfssystem 4096 Aug 17 20:46 ..
drwxr-xr-x 3 root     root      4096 Aug 17 20:46 Plug-ins
drwxr-xr-x 3 root     root      4096 Aug 17 20:46 Scanners

**Comment by tobbenb** [comment]
You are not showing us the complete compose as you have added a mod. So what else are you not showing?

Which user/groups are those  id's mapped to?
Is it a remote filesystem, as in NFS? If so, that will not work.
