### ISSUE TITLE
Document how to re-claim a server when not in the same subnet

### ISSUE THREAD

**Issue by ugomeda** [linuxserver/docker-plex#282]
## Expected Behavior

Have an easy way to re-claim my server.

## Current Behavior

No documentation available when `localhost:32400` is not accessible.

## Steps to Reproduce

1. Go to you account settings
2. Change your password
3. Check "Disconnect all my devices"
4. You can't access your server anymore

In my case, it was difficult to access the server directly through the port, I had to find another way.
This could be added to the documentation for future reference :

----

### How to (re-)claim your server ?

If your server is disconnected from the Plex App, you can access the webapp on `<your_ip>:32400/web` to claim it. 

Alternatively, if you can't access the port from the same subnet, you can follow this procedure :

- Stop your plex container (`docker stop plex`)
- Open your preference file with an editor (at `/path/to/library/Application Support/Plex Media Server/Preferences.xml`)
- Remove the section `PlexOnlineToken="<token>"` and save the file
- Go to https://www.plex.tv/claim/ to fetch a new token
- Restart your container with the new token in the environment variable `PLEX_CLAIM`

**Comment by aptalca** [comment]
Plex claim variable is documented in the readme. There is no difference between initial claiming or re-claiming. It's just claiming an unclaimed server.

**Comment by ugomeda** [comment]
No, the script that claims the server ([45-plex-claim](https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/45-plex-claim)) first checks if `PlexOnlineToken` is present in `Preferences.xml` ([line 3](https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/45-plex-claim#L3)). In my case, the value seemed to have been emptied by Plex, but still present (ie, `PlexOnlineToken=""`).

**Comment by Roxedus** [comment]
You cannot use a claim code to re-claim a server, it will be a new, separate, unique instance

**Comment by TimQuelch** [comment]
I ran into this exact same issue. I was able to solve it by manually removing `PlexOnlineToken=""` from Preferences.xml.

I'd suggest a smarter check in the line below to check if `PlexOnlineToken` is empty, rather than just if it is present.

https://github.com/linuxserver/docker-plex/blob/7baf705b9cfeb63e1e4bb3134c9550d209822721/root/etc/cont-init.d/45-plex-claim#L3
