### ISSUE TITLE
Provide a way to name a new PMS programmatically through environment variable 

### ISSUE THREAD

**Issue by nexxai** [linuxserver/docker-plex#283]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
When issuing the `docker run` command, being able to pass an `-e` flag like `SERVER_NAME=homemovies01` would register the server within the Plex environment as "homemovies01"

## Current Behavior
*such behaviour does not exist*

## Alternatives Considered
There aren't really any "alternatives" to speak of, other than just manually configuring it on first claim

**Comment by aptalca** [comment]
Not 100% sure, but I believe plex defaults on the hostname of the server. You can easily set a hostname for your container by passing the `-h` or `--hostname` flag

**Comment by nexxai** [comment]
Sorry to clarify, I don't want to set the hostname of the container, I want to set the name of the server that the Plex service identifies it by in the portal.

**Comment by Roxedus** [comment]
It would need us to probably change the value of `FriendlyName` in the xml file.

**Comment by aptalca** [comment]
> Sorry to clarify, I don't want to set the hostname of the container, I want to set the name of the server that the Plex service identifies it by in the portal.

I understand that. I'm telling you that the default name plex uses for the plex server is the hostname of the container.
