### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by DFlexy** [linuxserver/docker-plex#290]
I have a problem with the server.
All other apps have the correct time
I am using correct timezone as per settings below.
Time displays incorrect on LG and Samsung tv

```
docker run -d \
  --name=plex \
  --hostname plex \
  --dns=10.10.10.254 \
  --privileged=true \
  --network=lan \
  --ip=172.20.0.5 \
  --restart unless-stopped \
  -p 32400:32400 \
  -p 1900:1900/udp \
  -p 3005:3005 \
  -p 8324:8324 \
  -p 32410:32410/udp \
  -p 32412:32412/udp \
  -p 32413:32413/udp \
  -p 32414:32414/udp \
  -p 32469:32469 \
  -e TZ=America/Sao_Paulo \
  -e PLEX_CLAIM="<claimToken>" \
  -e PUID=1000 \
  -e PGID=1000 \
  -e VERSION=docker \
  -v plex:/config \
  -v plex:/transcode \
  -v /media/:/media \
linuxserver/plex
```

**Comment by j0nnymoe** [comment]
To my knowledge, Clients don't get their time from the server but from the device itself.

**Comment by james-d-elliott** [comment]
An easy way to eliminate plex as an issue is to use the `date` command from inside the container. If it shows the expected result it's nearly certainly not the plex servers time that is wrong.

**Comment by DFlexy** [comment]
Problem is timezone tv

**Comment by DFlexy** [comment]
.

**Comment by mostafamossaad** [comment]
Hi,
Sorry, not sure how things work on Github especially that this shows as "Closed", and/or "Done". @DFlexy said it's related to the TV's "Timezone", but that doesn't solve the problem for me.
I've also followed other instructions on Reddit about checking the time on my router, and that also didn't fix the problem for me.
Help?

**Comment by j0nnymoe** [comment]
Please open a new issue

**Comment by mostafamossaad** [comment]
> Please open a new issue

Hi,
I've tried creating a new bug report. But it's asking me for Docker data and I don't have that. I'm not even sure I'm in the right forum?

**Comment by aptalca** [comment]
If you're not using our docker container for plex, this is not where you should be reporting an issue.
