### ISSUE TITLE
Server wont let me get access

### ISSUE THREAD

**Issue by Adbeel065** [linuxserver/docker-plex#292]
Server starts but wont let me access into the web interface, getting this error.

`
Starting Plex Media Server.

libc++abi: terminating with uncaught exception of type std::__2::system_error: clock_gettime(CLOCK_MONOTONIC) failed: Operation not permitted

libc++abi: terminating with uncaught exception of type std::__2::system_error: clock_gettime(CLOCK_MONOTONIC) failed: Operation not permitted

****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.23.1.4602-280ab6053/PLEX MEDIA SERVER/42bc2e14-5fc0-4e65-535bb59c-0a445395.dmp

Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign

Crash Uploader options (all are required):

  --directory arg       Directory to scan for crash reports

  --serverUuid arg      UUID of the server that crashed

  --userId arg          User that owns this product

  --platform arg        Platform string

  --platformVersion arg Platform version string

  --vendor arg          Vendor string

  --device arg          Device string

  --model arg           Device model string

  --sentryUrl arg       Sentry URL to upload to

  --sentryKey arg       Sentry Key for the project

  --version arg         Version of the product

  --allowRetries arg    Whether we will allow retries`

**Comment by Roxedus** [comment]
Please follow the issue template. we are missing deployment info, full container logs, and environment information
