### ISSUE TITLE
404: Not Found when trying to install PMS 1.25.0.5173

### ISSUE THREAD

**Issue by minorsecond** [linuxserver/docker-plex#296]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The docker-compose script should download PMS version 1.25.0.5173

## Current Behavior

Docker returns a 404 error:

`https://downloads.plex.tv/plex-media-server-new/1.25.0.5173/debian/plexmediaserver_1.25.0.5173_amd64.deb:
plex          | 2021-12-18 07:39:38 ERROR 404: Not Found.`

## Steps to Reproduce

1. Change `VERSION` to `1.25.0.5173`
2. Run `docker-compose up`
3. See error message

## Environment
**OS:** Debian Linux
**CPU architecture:** x86_64/arm32/arm64 x86_64
**How docker service was installed:**

Official repo

I'm guessing Plex may have changed the download URL as the URL to the current Debian installer is `https://downloads.plex.tv/plex-media-server-new/1.25.2.5319-c43dc0277/debian/plexmediaserver_1.25.2.5319-c43dc0277_amd64.deb`, which doesn't match the format docker is using.

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d` to run it in "production mode." `docker-compose up` for testing.

## Docker logs

[plex_log.txt](https://github.com/linuxserver/docker-plex/files/7739321/plex_log.txt)

**Comment by aptalca** [comment]
For the version parameter you need the full Plex version which has a bunch more digits at the end (likely git hash).
That's different than the tags we use.

**Comment by minorsecond** [comment]
Ah, that makes sense then. Do you have any idea where I'd get the full version number?

**Comment by aptalca** [comment]
For plexpass versions, you get them from Plex (their forums)

If you're trying to install an older public version, then you should just set the version var to docker and pull an older tag
