### ISSUE TITLE
Thumbnail creation fails, works when plex setup without docker

### ISSUE THREAD

**Issue by shreyaspg** [linuxserver/docker-plex#299]
https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Thumbnails for the media files get generated when added
Manually doing the 'analyze' option generates too
## Current Behavior
Thumbnails don't get generated at all
## Steps to Reproduce
1.  Adding media files to the folder
2.  Creating library on UI
## Environment
**OS: ` cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`**

**CPU architecture:** armv7l
**How docker service was installed:**
Official docker repo

## Command used to create docker container (run/create/compose/screenshot)
![Capture](https://user-images.githubusercontent.com/21060721/147404912-63d83121-5190-42da-842e-a84228a8b21f.PNG) 
## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
Change in ownership detected, please be patient while we chown existing files
This could take some time
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing...
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing...
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing...
Docker is used for versioning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.
Critical: libusb_init failed

**Comment by shreyaspg** [comment]
```
Dec 26, 2021 09:43:12.356 [0xb3e64d50] INFO - Plex Media Scanner v1.25.2.5319-c43dc0277 - Docker Docker Container (LinuxServer.io) armv7l - build: linux-armv7neon - GMT 00:00
Dec 26, 2021 09:43:12.357 [0xb3e64d50] INFO - Linux version: 5.10.63-v7l+, language: en-US
Dec 26, 2021 09:43:12.358 [0xb3e64d50] INFO - Processor Arm
Dec 26, 2021 09:43:12.358 [0xb3e64d50] INFO - /usr/lib/plexmediaserver/Plex Media Scanner --analyze --manual --item 3 --log-file-suffix  Analysis
Dec 26, 2021 09:43:12.355 [0xb6ce2dcc] WARN - [FFMPEG] - Error loading external lib: Error loading shared library /config/Library/Application Support/Plex Media Server/Codecs/fb9eae3-4185-linux-armv7neon/libh264_decoder.so: Operation not permitted
Dec 26, 2021 09:43:12.356 [0xb6ce2dcc] WARN - [FFMPEG] - Error loading external lib: Error loading shared library /config/Library/Application Support/Plex Media Server/Codecs/fb9eae3-4185-linux-armv7neon/libhevc_decoder.so: Operation not permitted
```

`ERROR - [MI] Unsupported codec 'hevc' for file <all_files>`

![Capture2](https://user-images.githubusercontent.com/21060721/147404995-c8f2cc5c-9492-427b-b0f8-86233fde777e.PNG)

**Comment by aptalca** [comment]
It looks like plex can't access the codecs, maybe a permissions issue? Your log does show the perm script running, and is reporting a change in ownership, which shouldn't happen unless you manually change something. Your config folder is on a mounted drive, perhaps there is an issue with the mount settings.
