### ISSUE TITLE
Why i use the unraid dashboard to open the plex in webui, I need add the /web after the website.

### ISSUE THREAD

**Issue by zhuzhehao1999** [linuxserver/docker-plex#307]
![image](https://user-images.githubusercontent.com/68537574/158535183-6eb8e9e7-ae50-4744-a66d-5608635ce608.png)

when i press the web ui, i will go this page, how to change the open in web ui auto add /web after the website

**Comment by tobbenb** [comment]
You ignored the issue template.
The issue is something you have to ask Plex about.
