### ISSUE TITLE
Server is recognized as remote after using frp

### ISSUE THREAD

**Issue by reov** [linuxserver/docker-plex#308]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Servers show nearby

## Current Behavior
server shows remote

## Steps to Reproduce

1.update plex docker 
2.Use frp to penetrate localhost:32400

## Environment
**OS：unraid**
**CPU architecture:** x86_64
**How docker service was installed:plex**

## Command used to create docker container (run/create/compose/screenshot)
Command:
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='plex' --net='host' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="plex" -e 'VERSION'='docker' -e 'NVIDIA_VISIBLE_DEVICES'='' -e 'TCP_PORT_32400'='32400' -e 'TCP_PORT_3005'='3005' -e 'TCP_PORT_8324'='8324' -e 'TCP_PORT_32469'='32469' -e 'UDP_PORT_1900'='1900' -e 'UDP_PORT_32410'='32410' -e 'UDP_PORT_32412'='32412' -e 'UDP_PORT_32413'='32413' -e 'UDP_PORT_32414'='32414' -e 'PUID'='0' -e 'PGID'='0' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:32400]/web' -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/plex-icon.png' -v '':'/movies':'rw' -v '':'/tv':'rw' -v '':'/music':'rw' -v '':'/transcode':'rw' -v '/mnt/user/':'/Tower':'rw' -v '':'/etc':'rw' -v '/mnt/user/appdata/plex':'/config':'rw' --device='/dev/dri' 'linuxserver/plex'
a0710f051b931167d867796307c01076372060064319d9f63e89efbcae967f97

**Comment by Roxedus** [comment]
I have read this twice, and still have no idea what Frp is.

**Comment by reov** [comment]
https://github.com/fatedier/frp
The configuration file inside has some confidential information

Roxedus ***@***.***> 于 2022年3月21日周一 23:03写道：

**Comment by Roxedus** [comment]
So it's a reverse proxy/plex issue. Not a container issue

**Comment by reov** [comment]
No, it changed after the update, the official docker of plex does not have
this problem

Roxedus ***@***.***> 于 2022年3月21日周一 23:09写道：

**Comment by reov** [comment]
Yes, I am also very suspicious,If you use proxy, it should also display
localhost instead of vps ip，It was normal two months ago

Roxedus ***@***.***> 于 2022年3月21日周一 23:28写道：
