### ISSUE TITLE
Use More Recent Intel Compute Runtime to Support Alder Lake Transcoding

### ISSUE THREAD

**Issue by cryptoluks** [linuxserver/docker-plex#309]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Hardware Transcoding should work on Alder Lake CPU gen.

## Current Behavior

Plex Server crashes if any of Hardware Transcoding options enabled.

## Workaround

Replace installed Intel Compute Runtime 21.49 with latest Git Version. See [here](https://github.com/intel/compute-runtime/releases).

Or in `linuxserver.io`-way, drop `intel-compute-runtime.sh` in `custom-cont-init.d`:

```bash
#!/bin/bash

echo "**** install more recent intel compute runtime ****"
cd /tmp
wget https://github.com/intel/compute-runtime/releases/download/22.12.22749/intel-gmmlib_22.0.2_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.10713/intel-igc-core_1.0.10713_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.10713/intel-igc-opencl_1.0.10713_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/22.12.22749/intel-opencl-icd_22.12.22749_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/22.12.22749/intel-level-zero-gpu_1.3.22749_amd64.deb
dpkg -i /tmp/*deb
rm -f /tmp/*deb
```

It works pretty well with Alder Lake i5-12500. Also, HDR tone mapping seems to work.

**Comment by cryptoluks** [comment]
Just a quick follow up:

The use of the latest runtimes was not very successful in the end. At one point, transcoding crashes and only a complete host reboot seems to reenable transcoding until the next crash. I was not able to pinpoint it to a specific video codec, but generating an optimized version was a quick way to force a crash of transcoding.

I also tried to install the "remaining" packages [referenced by intel](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html) docs for GPU-based transcoding without success.

So for the time I will stick to regular software transcoding.

**Comment by aptalca** [comment]
see issue #312 
plex supports/recommends an older version but it's only mentioned in their forum posts

**Comment by Ge082** [comment]
> see issue #312 plex supports/recommends an older version but it's only mentioned in their forum posts

There also seems that Linux 5.15 have issues with HW acceleration
Kernel 5.16 have the fix apparently
https://gitlab.freedesktop.org/drm/intel/-/issues/4067

So it's mostly a Linux issue at this point

**Comment by jimmy-ungerman** [comment]
Currently running kernel version 5.17.8 and still seeing this issue. Will attempt the workaround described above.

**Comment by jimmy-ungerman** [comment]
It ended up breaking just like @cryptoluks said. Crashes until full system reboot again.

**Comment by cryptoluks** [comment]
> It ended up breaking just like @cryptoluks said. Crashes until full system reboot again.

I switched to Jellyfin because of this and [other breaking issues](https://forums.plex.tv/t/plex-web-stops-buffering-after-2-mins-causing-playback-to-stop) I have currently with Plex. With Jellyfin (linuxserver.io image), hardware-accelerated transcoding **seems** to fine on Alder Lake. Not really a fix for the issue, but maybe it works for you too until Plex works again.
