### ISSUE TITLE
Define a default transcode tmp directory

### ISSUE THREAD

**Issue by ljm42** [linuxserver/docker-plex#31]
I like how this docker offers a /transcode volume, it is very powerful.  But if the user doesn't define that, will transcoding still happen within docker.img?   

Would it be possible for you to detect when /transcode isn't defined and have the docker create and use /config/transcode (or /config/tmp) instead?  That would ensure the LS.IO docker never contributes to the docker.img filling up unnecessarily.

The Binhex version of Plex already does this, and I'm opening a similar request with Limetech.

Thanks for considering it!

**Comment by ljm42** [comment]
Also, after reviewing the Plex documentation:
  https://support.plex.tv/hc/en-us/articles/200273978-Linux-User-and-Storage-configuration
and Binhex's implementation:
  https://github.com/binhex/arch-plex/blob/master/setup/nobody/start.sh

it looks like this docker needs to define an environment variable for TMPDIR in addition to PLEX_MEDIA_SERVER_TMPDIR. They should both be set to the same thing.

**Comment by lonix** [comment]
I will look into this, right away.

**Comment by sparklyballs** [comment]
seeing as the docker.img problem is fairly unique to unraid, putting the /transcode volume in the template xml would solve this anyways.

also it should be noted that docker by default caches volumes anyways, so i'm not sure how much space would be saved in docker.img.

**Comment by ljm42** [comment]
Check out this discussion:
  https://github.com/limetech/dockerapp-plex/issues/2#issuecomment-204398862
it seems that recent versions of Plex no longer transcode to the /tmp directory by default, so perhaps no changes are needed after all.

**Comment by lonix** [comment]
Closed by #32
