### ISSUE TITLE
Critical: libusb_init failed`

### ISSUE THREAD

**Issue by bartounet16** [linuxserver/docker-plex#310]
Hello
seems to have same issue ...a lot of people
Docker on Debian 11
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 45-plex-claim: executing... 
[cont-init.d] 45-plex-claim: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 60-plex-update: executing... 
Docker is used for versioning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.
Critical: libusb_init failed`

after the web page can be acceded but nos server seems to be runnung

![image](https://user-images.githubusercontent.com/1244020/162642295-5544da9c-2011-4e4e-8a61-93e940ee14e5.png)

_Originally posted by @bartounet16 in https://github.com/linuxserver/docker-plex/issues/304#issuecomment-1094381043_

**Comment by j0nnymoe** [comment]
Marked as invalid as haven't provided all details requested in issue. 
Also, that error does mean the server is running, just it's not claimable currently (unable to see what you've done without the compose info)

**Comment by bartounet16** [comment]
thanks for answer
My compose docker

`version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /DISK/docker/plex:/config
      - /DISK/docker/plex:/tv
      - /DISK/docker/plex:/movies
    restart: unless-stopped
`

**Comment by j0nnymoe** [comment]
ok, so you either need to use the claim token or be on the same local network as the plex server, other wise it won't let you claim it. This is a security feature of plex itself.

**Comment by j0nnymoe** [comment]
And just an FYI, the `Critical: libusb_init failed` error is only related to the Plex LiveTV/DVR, doesn't stop plex from working.

**Comment by bartounet16** [comment]
ok thank you very much.
in fact i have install Plex on docker and Lxc container in Proxmox
It is a dedicated server in datacenter.
I am connect whith Plex by VPN 
My local network is 10.0.0.0/24 and Plex server 192.168.100.0/24

So i think it is the problem
So if i understand well, i should be install a VM whith browser in the same network ?

Or use the claim token but i don't know how ?

**Comment by bartounet16** [comment]
thanks .
i have done whith a live cd in the same network !!!
![image](https://user-images.githubusercontent.com/1244020/162643821-a30772ac-9242-40ce-8ed6-49df2d733fa4.png)

thank you for advises
