### ISSUE TITLE
Windows Support to avoid SQLIte corruption

### ISSUE THREAD

**Issue by daniandco1** [linuxserver/docker-plex#311]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

hello, i guess this image is using similar technologies like in the official plex docker
https://github.com/plexinc/pms-docker

i saw a warning on the official github ([bottom ](https://github.com/plexinc/pms-docker#windows-not-recommended)of the repo) saying that windows and sqlite will cause corruption of the db after some time.

 im  wondering if there is something we can do about it to prevent it? 
many thanks :)

## Desired Behavior

windows compatible db that won't crash, with shared volume

## Current Behavior

occuording to the official plex image, the database wil corrupt because its shouldn't be shared across windows system

## Alternatives Considered

maybe mounting the /config inside the container? (tried to implement but i'm not a docker guru)

**Comment by Roxedus** [comment]
This is a technical limitation with how directories are shared from the Windows filesystem to the Linux Subsystem. It's not something we can do anything to support. Your best bet is to store the files in WSL (not trough /mnt/<diskletter>).
