### ISSUE TITLE
HDR Tone Mapping broken again

### ISSUE THREAD

**Issue by nickp85** [linuxserver/docker-plex#312]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
HDR Tone Mapping should still use hardware transcode

## Current Behavior
When HDR tone mapping is enabled, software transcode is used

## Steps to Reproduce

1. Add the /dev/dri device to the container
2. Enable HDR tone mapping
3. Play something with HDR and force it to transcode

## Environment
**OS:** Unraid 6.10rc8
**CPU architecture:** x86_64/arm32/arm64 - Intel 9900K
**How docker service was installed:** Unraid Apps menu (official repo)

## Docker logs

[plexlogs.txt](https://github.com/linuxserver/docker-plex/files/8696026/plexlogs.txt)

**Comment by nickp85** [comment]
The old scripts I've used in the past to put the right driver back into the container are not working this time around.

**Comment by nickp85** [comment]
For reference, the two scripts I've previously used to fix this issue until the container was working properly. It's been fine for the past few months after the team got it working but a recent update seems to have broken it again.

`#!/bin/bash
#description=This script updates Beignet Driver to support last Intel GPUs for Plex Container

docker exec plex bash -c "apt update && apt -y install cmake pkg-config python ocl-icd-dev libegl1-mesa-dev ocl-icd-opencl-dev libdrm-dev libxfixes-dev libxext-dev llvm-7-dev clang-7 libclang-7-dev libtinfo-dev libedit-dev zlib1g-dev build-essential git clinfo"
docker exec plex git clone --branch comet-lake https://github.com/rcombs/beignet.git
docker exec plex bash -c "mkdir /beignet/build/ && cd /beignet/build && cmake -DLLVM_INSTALL_DIR=/usr/lib/llvm-7/bin .. && make -j8 && make install"
docker exec plex rm -rf beignet
docker exec plex bash -c "apt -y remove cmake pkg-config python ocl-icd-dev libegl1-mesa-dev ocl-icd-opencl-dev libdrm-dev libxfixes-dev libxext-dev llvm-7-dev clang-7 libclang-7-dev libtinfo-dev libedit-dev zlib1g-dev build-essential git && apt -y autoremove"
docker restart plex
docker exec plex clinfo -l`


`#!/bin/bash
wget https://github.com/intel/compute-runtime/releases/download/21.50.21939/intel-gmmlib_22.0.0_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9441/intel-igc-core_1.0.9441_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9441/intel-igc-opencl_1.0.9441_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/21.50.21939/intel-opencl-icd_21.50.21939_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/21.50.21939/intel-level-zero-gpu_1.2.21939_amd64.deb
sudo dpkg -i *.deb`

**Comment by james-d-elliott** [comment]
Just looking at the repo it doesn't appear there was a change to the actual container, so potentially this is a change on the plex side.

**Comment by Ge082** [comment]
Downgrade to 21786 fixed the issue. https://github.com/intel/compute-runtime/releases/tag/21.49.21786

None of the version above 21786 worked well with HW Tone Mapping on Plex (and possibly Jellyfin / Emby).

**Comment by aptalca** [comment]
Where is that version `21.49.21786` coming from?
All I'm seeing in their dockerfile is a version released in 2020: https://github.com/plexinc/pms-docker/blob/master/Dockerfile#L8

**Comment by nickp85** [comment]
This issue is back in the latest container version
