### ISSUE TITLE
[Feature Request] Update through GUI

### ISSUE THREAD

**Issue by the-hotmann** [linuxserver/docker-plex#314]
## Desired Behavior
Updates are shown in the GUI, but are not implementable through the GUI. That I guess would be way more comfortable since it must just trigger a reboot/restart of the container. Does anyone know if the official docker container does support updates throught the GUI?

## Current Behavior
Updates are shown, but must be implemented through SSH which I not always have access to.

I know a lot of other containers that can reboot themself through the GUI (JDownloader etc etc) that would allow a way better user expirience.

**Comment by j0nnymoe** [comment]
This would need to be asked at plex, not us.
