### ISSUE TITLE
HDR HW Tone Mapping broken again

### ISSUE THREAD

**Issue by Rainzzzzzz** [linuxserver/docker-plex#318]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
HDR Tone Mapping should still use hardware transcode

## Current Behavior
When HDR tone mapping is enabled, software transcode is used

## Steps to Reproduce

1.Add the /dev/dri device to the container
2.Enable HDR tone mapping
3.Play something with HDR and force it to transcode
4

## Environment
Unraid 6.10.3
I5 11 gen
**How docker service was installed:**
Unraid app menu

**Comment by Rainzzzzzz** [comment]
Was working perfectly before that lastest update

**Comment by Rainzzzzzz** [comment]
Has something to do with that
https://github.com/intel/compute-runtime/releases/tag/21.49.21786?fbclid=IwAR0FlHaxwFPUiz6xinqdCOU12WwJ3vyjENNT7pFPAmRU1yt3w2Tv80pbMC0

**Comment by aptalca** [comment]
See here: https://github.com/linuxserver/docker-plex/issues/312

**Comment by duckyyyviewer** [comment]
Same for me until I reverted back to 1.27.1.5916-6b0e31a64-ls122

**Comment by nickp85** [comment]
Same issue, problem is back just like before. With tone mapping enabled, no HW transcode on HDR content. 9900K here. Turning off tone mapping fixes it

**Comment by Rainzzzzzz** [comment]
The only way is to revert to  1.27.1.5916-6b0e31a64-ls122 and lock it there

**Comment by ScottJWhite** [comment]
> The only way is to revert to 1.27.1.5916-6b0e31a64-ls122 and lock it there Work fine since the rollback

This worked for me! My CPU was hurting bad.

**Comment by olqs** [comment]
I have manually installed the intel compute-runtime packages: https://github.com/intel/compute-runtime/releases/tag/21.49.21786 inside the container and hw transcode with tone mapping is working again.

**Comment by aptalca** [comment]
Can you guys test this build and let us know if it works? `lspipepr/plex:amd64-1.27.2.5929-a806c5905-pkg-bbd93429-pr-319`

**Comment by patrickthescriptwhisperer** [comment]
Hey @aptalca, I too have the hw tone mapping issue which is resolved with the image `linuxserver/plex:1.27.1.5916-6b0e31a64-ls122`, allowing me to transcode or optimise 4k hdr video using hw acceleration on my intel core i7-1165G7. I tried your image `lspipepr/plex:amd64-1.27.2.5929-a806c5905-pkg-bbd93429-pr-319` out on the same file with the same optimisation settings and see that it does not fix the issue, falling back to sw encoding. If you want more details let me know.

**Comment by aptalca** [comment]
@patrickthescriptwhisperer can you repull that image and try again? I pushed an update

Thanks

**Comment by patrickthescriptwhisperer** [comment]
sorry that took a minute, just wanted to double check the cpu usage between your latest and the original image I was tied to. The latest pull of your image appears to be working well 👍 the full transcode still takes a little while so I will leave it running and I can spot check the output when it completes. Thanks for putting that together.

**Comment by patrickthescriptwhisperer** [comment]
tone mapping seemed to work well; no weird artefacts, no dimming, thanks again
