### ISSUE TITLE
Unable to import m3u playlists to plex

### ISSUE THREAD

**Issue by marius-hi** [linuxserver/docker-plex#320]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Sadly Plex doesn't provide an option to import custom m3u playlists via UI, but I figured out that there is a REST API that looks like `http://[PlexServer]:32400/playlists/upload?sectionID=[librarySectionID]&path=[PathTo.M3U]&X-Plex-Token=[Token]`. On this [reddit thread](https://www.reddit.com/r/PleX/comments/ecirqa/how_to_manually_import_an_m3u_playlist_into_plex/) is documented and proved that the method works with Plex native, but seems that it doesn't work when Plex is running in a docker container (latest version of linuxserver/plex - created 8 days ago). 

------------------------------

## Expected Behavior
Being able to successfully upload a custom m3u playlist when Plex is installed in a docker container. In the same reddit thread there is a user who [mentioned](https://www.reddit.com/r/PleX/comments/ecirqa/comment/fthkcw9/?utm_source=share&utm_medium=web2x&context=3) that faced the same issue as me. It makes me understand that this issue is only when Plex is installed inside of the docker.

## Current Behavior
The issue is that when I do a POST request of my playlist playlist1.m3u to the URL, I get the response: **500 Internal Server Error**.

What I can understand from the log provided below is that the 2 entries that are in the playlist (Song1.mp3 and Song2.mp3) are correctly identified, but for some reason Plex doesn't find the path.
I've connected to the terminal of the docker container and found that the paths are correct, inside of /media/MUSIC/ having: playlist1.m3u, Song1.mp3 and Song2.mp3. Also both mp3 files are visible in the Plex UI and can be played.

## Steps to Reproduce

1. Create a m3u playlist called playlist1.m3u and save it to /media/MUSIC/   
```
#EXTM3U
#EXTINF:1,Album - Song1
Song1.mp3
#EXTINF:2,Album - Song2
Song2.mp3
```
2. Add 2 mp3 files to /media/MUSIC/ called Song1.mp3 and Song2.mp3
3. Do a POST request to http://your_IP_address:32400/playlists/upload?sectionID=4&path=/media/MUSIC/playlist1.m3u&X-Plex-Token=-TK3...... with postman or curl ([details](https://www.reddit.com/r/PleX/comments/ecirqa/how_to_manually_import_an_m3u_playlist_into_plex/))
4. Check playlist in Plex UI to see the added new 2 songs

## Environment
**OS:** DSM on Synology NAS
**CPU architecture:** x86_64 on
**How docker service was installed:**
Using the docker compose provided in the documentation

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.2"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-1
    network_mode: host
    environment:
      - PUID=1031
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM=claim-e-claim-token
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/media:/media:ro
    restart: unless-stopped
```

## Docker logs

I checked Plex Media Server.log and could see the following:
```
Jul 26, 2022 20:13:43.938 [0x7fe6332d2b38] DEBUG - Request: [192.168.1.1:57034 (Subnet)] POST /playlists/upload?sectionID=4&path=/media/MUSIC/playlist1.m3u (3 live) #1675 Signed-in Token (my_user) (Chrome)
Jul 26, 2022 20:13:44.242 [0x7fe6332d2b38] DEBUG - [Req#1675] Added new metadata item (playlist1) with ID 19578
Jul 26, 2022 20:13:44.470 [0x7fe6332d2b38] WARN - [Req#1675] Could not find path: /media/music/Song1.mp3
Jul 26, 2022 20:13:44.470 [0x7fe6332d2b38] WARN - [Req#1675] Could not find path: /media/MUSIC/Song2.mp3
Jul 26, 2022 20:13:44.470 [0x7fe6332d2b38] WARN - [Req#1675] Could not find path: /media/MUSIC
Jul 26, 2022 20:13:44.470 [0x7fe6332d2b38] ERROR - [Req#1675] Playlist importer: Couldn't import playlist "/media/MUSIC/playlist1.m3u", deleting.
Jul 26, 2022 20:13:44.471 [0x7fe6332d2b38] DEBUG - [Req#1675] Destroying metadata item 19578 (playlist1)
Jul 26, 2022 20:13:44.606 [0x7fe633dc8b38] DEBUG - Completed: [192.168.1.1:57034] 500 POST /playlists/upload?sectionID=4&path=/media/MUSIC/playlist1.m3u (3 live) 766ms 325 bytes (pipelined: 1)
```

**Comment by marius-hi** [comment]
Up

**Comment by j0nnymoe** [comment]
This will be a Plex issue itself, not related to the container.
