### ISSUE TITLE
Unable to Playback

### ISSUE THREAD

**Issue by brandonb1987** [linuxserver/docker-plex#322]
Upgraded to the recent 1.28.0 image. Since then I am unable to do any playback whatsoever.

This is the only thing that I've changed since the issue started. I've attached the logs. Unable to roll back as it auto-updates in the boot process.

[Plex Media Server Logs_2022-08-03_00-52-32.zip](https://github.com/linuxserver/docker-plex/files/9249149/Plex.Media.Server.Logs_2022-08-03_00-52-32.zip)

Here is what I can see on the plex console 

Aug 03, 2022 00:54:53.856 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.856 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.858 [0x14f0d35afb38] Info — [Req#1d3] Sync: downloaded 0 sync list(s) with 0 sync items(s): 0 new, 0 updated, 0 deleted
Aug 03, 2022 00:54:53.865 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.865 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.878 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.879 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.883 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.883 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.896 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.896 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.900 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.900 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.914 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.914 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:53.918 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:53.918 [0x14f0d34f5b38] Error — [Req#1de/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.057 [0x14f0d358cb38] Warning — [Req#1ee] Sync: sync list 37638290 belonging to user 25531947 has died of old age, ignoring
Aug 03, 2022 00:54:54.057 [0x14f0d358cb38] Warning — [Req#1ee] Sync: sync list 44392289 belonging to user 1 has died of old age, ignoring
Aug 03, 2022 00:54:54.057 [0x14f0d358cb38] Info — [Req#1ee] Sync: downloaded 0 sync list(s) with 0 sync items(s): 0 new, 0 updated, 0 deleted
Aug 03, 2022 00:54:54.441 [0x14f0d3561b38] Error — [Req#1df] Unknown metadata type: folder
Aug 03, 2022 00:54:54.441 [0x14f0d35afb38] Warning — [Req#212] QueryParser: Invalid field 'sectionID' found, ignoring.
Aug 03, 2022 00:54:54.441 [0x14f0d35afb38] Warning — [Req#212] QueryParser: Invalid field 'contentDirectoryID' found, ignoring.
Aug 03, 2022 00:54:54.442 [0x14f0d3561b38] Warning — [Req#1df] QueryParser: Invalid field 'contentDirectoryID' found, ignoring.
Aug 03, 2022 00:54:54.474 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.474 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.479 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.479 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.496 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.496 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.501 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.501 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.518 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.518 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.523 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.523 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.540 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.540 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.545 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Cannot load libcuda.so.1

Aug 03, 2022 00:54:54.545 [0x14f0d358cb38] Error — [Req#1e0/Transcode] [FFMPEG] - Could not dynamically load CUDA

Aug 03, 2022 00:54:54.743 [0x14f0d34f5b38] Warning — [Req#24f/Transcode/FC4AD51B-127E-43E8-B222-C08A31006E64] CodecManager: EAE exited with code 13. Restarting.
Aug 03, 2022 00:54:54.743 [0x14f0d34f5b38] Info — [Req#24f/Transcode/FC4AD51B-127E-43E8-B222-C08A31006E64] CodecManager: starting EAE at "/tmp/pms-b9063273-67f9-4190-882e-6796f7ce6b2b/EasyAudioEncoder"
Aug 03, 2022 00:54:56.332 [0x14f0d34f5b38] Error — [Req#271] Unknown metadata type: folder
Aug 03, 2022 00:54:56.332 [0x14f0d34f5b38] Warning — [Req#271] QueryParser: Invalid field 'contentDirectoryID' found, ignoring.
Aug 03, 2022 00:54:58.230 [0x14f0d35afb38] Error — [Req#269] [Transcoder] [eac3_eae @ 0x1494413f7600] EAE timeout! EAE not running, or wrong folder? Could not read '/tmp/pms-b9063273-67f9-4190-882e-6796f7ce6b2b/EasyAudioEncoder/Convert to WAV (to 8ch or less)/FC4AD51B-127E-43E8-B222-C08A31006E64_357-0-0.wav'
Aug 03, 2022 00:54:58.231 [0x14f0d3561b38] Error — [Req#27a] [Transcoder] [eac3_eae @ 0x1494413f7600] error reading output
Aug 03, 2022 00:54:58.231 [0x14f0d34f5b38] Error — [Req#27c] [Transcoder] Error while decoding stream #0:1: I/O error`

**Comment by brandonb1987** [comment]
Updated both the server to 1.28.1 and apps as of this am, still an issue

**Comment by systemswizard** [comment]
I am seeing this issue as well on `Linuxserver.io version:- 1.29.2.6364-6d72b0cf6-ls144 Build-date:- 2022-11-14T22:11:11-06:00`

**Comment by Loader009** [comment]
You have most probably the same issue as I have - `/configs` is mounted with `noexec`.
That's an issue because at least the decoders happen to be there.

`/configs` is mounted with `noexec` because it is not a docker volume, but a host mount AND the path of it is itself a mount point.
E.g.: `/home/docker/config/plex` is a mount point and this is then a host mount -> `-v /home/docker/config/plex:/configs`

Please confirm if that's the case for you too - I use podman, so your issue might(!) be different.

**Comment by systemswizard** [comment]
seeing the same issue using a bind mount instead of using a volume

```
Linuxserver.io version:- 77bf89e6-ls54 Build-date:- 2022-12-12T22:49:01-06:00

Linux 6.0.0-0.deb11.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 11 Bullseye 6.0.3-1~bpo11+1 (2022-10-29) x86_64 GNU/Linux 

Docker Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by Loader009** [comment]
my workaround:

```
-v "configs/plex/Preferences.xml:/config/Library/Application Support/Plex Media Server/Preferences.xml:rw" \
-v "configs/plex/Plex Media Server/Crash Reports:/config/Library/Application Support/Plex Media Server/Crash Reports:rw" \
-v "configs/plex/Plex Media Server/Diagnostics:/config/Library/Application Support/Plex Media Server/Diagnostics:rw" \
-v "configs/plex/Plex Media Server/Logs:/config/Library/Application Support/Plex Media Server/Logs:rw" \
-v "volumes/plex/Plex Media Server/Cache:/config/Library/Application Support/Plex Media Server/Cache:rw" \
-v "volumes/plex/Plex Media Server/Media:/config/Library/Application Support/Plex Media Server/Media:rw" \
-v "volumes/plex/Plex Media Server/Metadata:/config/Library/Application Support/Plex Media Server/Metadata:rw" \
Support:rw" \
```

As you can see, I hate myself for this.
Everything in configs should be small size stuff.
It works this way, I don't know if I will put more time into a better workaround.

**Comment by systemswizard** [comment]
It is not the worst workaround though thanks for the share

**Comment by systemswizard** [comment]
I kept having issues after my last update and ended up here and it looks to be docker seeing the drive is mounted with noexec or in some cases like mine, docker is just doing it for <reason>

In my compose yml this seems to work out pretty well

```
    tmpfs:
      - "/config/Library/Application Support/Plex Media Server/Codecs:uid=1002,gid=1002,exec"
```

in theory, you can add the exec flag just like your rw statement just add it on

**Comment by Loader009** [comment]
Did that - not working for me (podman, not docker).
podman documentation: `If the HOST-DIR is a mount point, then dev, suid, and exec options are ignored by the kernel.`
That's most probably a limitation of rootless podman and would probably only apply to rootless docker (if possible) too.

**Comment by drizuid** [comment]
OP did not fill out the issue template making it impossible to diagnose or help. 
that said, we also do not test or support podman. 
finally, as stated <https://github.com/linuxserver/docker-plex/issues/322#issuecomment-1368226301> plex will not work when /config is on a drive/volume that is mounted noexec. a bind or volume will not change this. This must be corrected on the host.

**Comment by Loader009** [comment]
The actual issue is that there are binaries saved in /config, which is not a good practice at all.
