### ISSUE TITLE
Plex Not Working

### ISSUE THREAD

**Issue by EvilMonkey0** [linuxserver/docker-plex#323]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I recently updated Unraid OS and the Plex docker container. All of them I try do not connect or view my media. There are no (!) on the categories unless I stop the docker container. Each movie or tv show I click on says "something went wrong". Only started after updating. Tried BinHex, Linuxserver and the official plex docker containers...all same results.
------------------------------

## Expected Behavior

I should be able to play my media just like before the update

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**Unraid 6.10.3
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Please provide the info we request, logs help but also even screenshots of how you've deployed the container.
