### ISSUE TITLE
Setting permissions breaks  /etc/cont-init.d/99-custom-scripts

### ISSUE THREAD

**Issue by slink42** [linuxserver/docker-plex#326]
https://github.com/linuxserver/docker-plex/blob/69327b9f3a9d409bb5f916eab19859a70ca61310/root/etc/cont-init.d/40-chown-files#L25

Setting all folders in /config to be owned by a user other than root causes /etc/cont-init.d/02-tamper-check to move /config/custom-cont-init.d/ and /config/custom-services.d/ to other paths. This prevents /etc/cont-init.d/99-custom-scripts from being able to run custom scripts and services on container startup.

**Comment by crkinard** [comment]
Not sure if this is the same issue I am having but rolling a new instance of Plex is missing the /config/custom-cont-init.d/ and /config/custom-services.d/ folders.
```

root@dock[/mnt/store/_docker/plex/config]# ll
total 2
drwxr-xr-x 3  911 3 Sep 28 01:28 ./
drwxr-xr-x 3 root 3 Sep 28 00:33 ../
drwxr-xr-x 3  911 3 Sep 28 01:28 Library/
```
`Linux dock 5.10.131+truenas #1 SMP Mon Aug 8 16:39:36 UTC 2022 x86_64 GNU/Linux`

**Comment by drizuid** [comment]
op did not fill out template
