### ISSUE TITLE
Plex claim not working when server auth revoked

### ISSUE THREAD

**Issue by slink42** [linuxserver/docker-plex#328]
https://github.com/linuxserver/docker-plex/blob/36b5837ed9449529ed9cb784c2efd189a6127ac5/root/etc/cont-init.d/45-plex-claim#L3
Should also check if PlexOnlineToken="" exists in Preferences.xml and run claim again if it does

**Comment by oarriet** [comment]
I think I am getting this problem too after resetting my password according to the `data breach` email I got. 

FYI: I did reset my password and then clicked on `"Sign out connected devices after password change."`. After that I got a new `Plex Claim` and I am not able to see my server anymore.

**Comment by scottcuellar** [comment]
I have the exact same issue. 

Starting Plex Media Server.
Critical: libusb_init failed

**Comment by Spartanaco** [comment]
I had the same issue for the same reason, ended up adding the PLEX_CLAIM environment variable to have it reclaimed successfully.

The [README.md](https://github.com/linuxserver/docker-plex/tree/master#parameters
) shows how to get the claim token from plex.tv

Once you see the PlexOnlineHome, PlexOnlineMail, PlexOnlineToken, PlexOnlineUsername values set in your Preferences.xml as shown here: https://support.plex.tv/articles/204281528-why-am-i-locked-out-of-server-settings-and-how-do-i-get-in/ it should be safe to remove that environment variable and restart.

That's how I got my PlexMediaServer back online after the forced log out.

**Comment by Jafner** [comment]
I also struggled with this. Per @Spartanaco's suggestion, I took the following steps:  

1. Manually edit `/config/Library/Application Support/Plex Media Server/Preferences.xml` to remove the PlexOnlineHome, PlexOnlineMail, PlexOnlineToken, PlexOnlineUsername  
2. Get a new claim token from https://www.plex.tv/claim and pass it to the container as the `PLEX_CLAIM` container environment variable. 
3. Online the container with (in my case) `docker-compose up -d --force-recreate` 

After these steps, my logs look like this:  

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/40-chown-files
cont-init: info: /etc/cont-init.d/40-chown-files exited 0
cont-init: info: running /etc/cont-init.d/45-plex-claim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9122    0  9122    0     0   6643      0 --:--:--  0:00:01 --:--:--  6639
Server claimed successfully, navigate to http://serverip:32400/web to complete plex setup.
cont-init: info: /etc/cont-init.d/45-plex-claim exited 0
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/60-plex-update
Atempting to upgrade to: 1.28.2.6106-44a5bbd28
2022-08-25 19:03:07 URL:https://downloads.plex.tv/plex-media-server-new/1.28.2.6106-44a5bbd28/debian/plexmediaserver_1.28.2.6106-44a5bbd28_amd64.deb [84485098/84485098] -> "/tmp/plexmediaserver_1.28.2.6106-44a5bbd28_amd64.deb" [1]
(Reading database ... 10390 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_1.28.2.6106-44a5bbd28_amd64.deb ...
PlexMediaServer install: Pre-installation Validation.
PlexMediaServer install: Custom environment detected.  Skipping preinstallation validation.
Unpacking plexmediaserver (1.28.2.6106-44a5bbd28) over (1.28.1.6104-788f82488) ...
Setting up plexmediaserver (1.28.2.6106-44a5bbd28) ...
PlexMediaServer install: Custom environment detected.  Skipping postinstallation tasks. Continuing.
cont-init: info: /etc/cont-init.d/60-plex-update exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-scripts
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun plex (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Starting Plex Media Server.
Critical: libusb_init failed
```

After this I was able to log into the server (at my reverse proxy address `plex.mydomain.com`. I did not need to use http://<server-ip>:32400/web) and authenticate. All is well once again.

**Comment by TimQuelch** [comment]
This is a similar issue to https://github.com/linuxserver/docker-plex/issues/282

**Comment by slink42** [comment]
Suggested change for [docker-plex/root/etc/cont-init.d/45-plex-claim](https://github.com/linuxserver/docker-plex/blob/36b5837ed9449529ed9cb784c2efd189a6127ac5/root/etc/cont-init.d/45-plex-claim#L3)
Line 3 in [36b5837](https://github.com/linuxserver/docker-plex/commit/36b5837ed9449529ed9cb784c2efd189a6127ac5)

`if [ -z "$PLEX_CLAIM" ] || ( grep -qs "PlexOnlineToken" "/config/Library/Application Support/Plex Media Server/Preferences.xml" &&  \
    !  grep -qs 'PlexOnlineToken=""' "/config/Library/Application Support/Plex Media Server/Preferences.xml" ); then
    exit 0
fi`
