### ISSUE TITLE
https://tools.linuxserver.io/latest-plexpass.json advertising wrong version

### ISSUE THREAD

**Issue by russell** [linuxserver/docker-plex#33]
Currently it says the version is 0.9.16.3.1840-cece46d but plex is telling me that 0.9.16.4.1911 has been released.

**Comment by russell** [comment]
As just a random extra tidbit i came across this script while looking around.  It's a pure bash plex update script that is probably not too hard to incorporate into your existing image and would remove the need to host a json file https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh

**Comment by lonix** [comment]
hey @russell. Due to a  agreement with PlexDevs we have changed the behavior of latest-plexpass, as it was a open door into the paywall. it will be changed once we merge #32.

**Comment by lonix** [comment]
Closed by #32
