### ISSUE TITLE
Plex Web player showing an old version while using a custom domain on a reverse proxy

### ISSUE THREAD

**Issue by WhimsicalLlamaH** [linuxserver/docker-plex#330]
I may be a little out of my depth, but could use some help track down what's causing my Plex Web app issue.
Context:

- **Plex docker running on a standalone install** of Docker on Ubuntu 22.04.4
- using a **custom domain**
- using a **reverse proxy** (Traefik 2.8.3) also running as a Docker container, certificates are provided by LetsEncrypt, and are showing up correctly over https
- I have verified "**secure**" access to the server per the side panel
- (when I remove the custom domain under Settings | Network | Custom server access URLs, it goes into "indirect" mode)

Here's the problem:

- when I access my Plex server at app.plex.tv, it work the Plex Web | General page says Version 4.89.1
- **when I access my Plex server at plex.customdomain.com the Plex Web | General page says Version 4.84.1** and says that it won't sync settings

I'm specifically seeing the message:
" Any Plex Web settings and customization made in this Plex Web instance will not be synchronized with other Plex Web instances. This is because we have detected you have previously saved settings from a newer version of Plex Web."

I'm recreated Docker containers several times. I've taken down the reverse proxy and brought it back up.
All regular playback works just fine, but the Plex Web version on my custom domain is stuck at Version 4.84.1 for some reason.

What setting/button/config am I missing to make the custom domain show an older version of Plex Web?

**Comment by Roxedus** [comment]
Plex has bundled older versions of Plex web with the server for years, they have several articles mentioning this, [here's one](https://support.plex.tv/articles/200948256-updating-plex-web-app/).

This is not a issue, Plex is simply just telling you to stick to one or the other.

**Comment by WhimsicalLlamaH** [comment]
I had no idea! Thank you for the sanity check. I appreciate the quick reply and the link to documentation.
