### ISSUE TITLE
Add support for HOSTNAME and ADVERTISE_IP

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-plex#331]
Continuing on from https://github.com/linuxserver/docker-plex/issues/102 as this never seemed to have a solid decision.

The env var `ADVERTISE_IP` is quite useful when you're running behind a reverse proxy, as you don't need to enable remote access.

We can absolutely set this in the GUI, but one of the benefits of docker-compose and (especially) lsio images, are the env vars that can be used to setup the container settings, and easily change things without requiring the GUI. 

As an example, I have the following alongside Traefik:

`ADVERTISE_IP=http://$SERVER_IP:$PLEX_PORT,https://plex.$DOMAINNAME` which then advertises to plex.tv that my server is available at my domain, and then I don't need to set up remote access at all.

I would say that it's definitely a useful env var to have, especially if plexinc's implementation rarely changes (as per https://github.com/linuxserver/docker-plex/issues/102#issuecomment-472595940), it would also open up for greater ability for additional vars to edit things like `LAN Networks` (`LanNetworksBandwidth` in Preferences.xml) and disabling the relay (`RelayEnabled` in Preferences.xml) which can be a constant source of irritation for many, especially those who are new to the reverse proxy side of things.

**Comment by aptalca** [comment]
For an app that really requires gui access to set up, it's best to let those settings get taken care of in the gui. We only create vars for things that are needed for initial setup. Plus, see my comment on the linked issue about touching plex preferences. We don't want to do it unless absolutely necessary like for PLEX_CLAIM. The other vars you mention are definitely not required for initial setup.

If you really want to do it via an env var, you can customize the container to sed the preferences file on startup: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by modem7** [comment]
> If you really want to do it via an env var, you can customize the container to sed the preferences file on startup: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

Cheers for the link! I'll have a look!

My main thinking is less regarding initial setup as such, but migrations and continued maintenance/modifications.

But I totally understand where you're coming from, I'll have a look at the link and go on from there!

**Comment by aptalca** [comment]
This is all you need to do for reverse proxy, no remote access enabling necessary: https://github.com/linuxserver/reverse-proxy-confs/blob/master/plex.subdomain.conf.sample#L2-L6

**Comment by modem7** [comment]
> This is all you need to do for reverse proxy, no remote access enabling necessary: https://github.com/linuxserver/reverse-proxy-confs/blob/master/plex.subdomain.conf.sample#L2-L6

Aye, that's roughly what I have (Traefik equivalent), but this is kinda where I was getting at, technically if you're setting up the container with reverse proxy for the first time, changing the "Custom server access URLs" would technically be an initial setup step.

**Comment by aptalca** [comment]
It's not. Custom access urls are only used for mobile and TV clients that get the server address from plex.tv

It's not needed for reverse proxying the webgui
