### ISSUE TITLE
webgui not accessible

### ISSUE THREAD

**Issue by xenovia** [linuxserver/docker-plex#332]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. click on wegui on the plex docker
2.page open up on chrome but stay in error chrome unable to load anything
3.
4.

## Environment
**UNRAID**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

![image](https://user-images.githubusercontent.com/10589214/190099718-77833ac9-8468-4bae-a46b-c12d39f6d39a.png)

**Comment by ohthehugemanatee** [comment]
I'm having the same problem. Running on kubernetes, the installation has worked well for years. Tonight the pod restarted and it updated from 1.28.2.6151-914ddd2b3 to 1.29.0.6219-b1b4d4871, and the webgui does not respond. wget from inside the container to http://localhost:32400/ gets a 401.

I note that startup says `PlexMediaServer install: Custom environment detected.  Skipping postinstallation tasks. Continuing.`, so maybe that's related?

What further diagnostic information do you need?

**Comment by blackph0en1x** [comment]
Running the docker container I see that it is listening on port 32400 only for IPv6 protocol and not IPv4. Could this be the problem?

**Comment by drizuid** [comment]
template not filled out
