### ISSUE TITLE
Remove Intel Compute Runtime and Beignet/OpenCL from Docker image.

### ISSUE THREAD

**Issue by dagstuan** [linuxserver/docker-plex#334]
Version [1.29.1.6240 and above](https://forums.plex.tv/t/pms-1-29-1-hw-tonemapping-testing-questions-and-answers/812785) of PMS automatically installs these drivers if they are required when HW-transcoding. When this release of PMS rolls out to normal users of PMS the drivers should be removed from this Docker image.

**Comment by onedr0p** [comment]
I can confirm on my container images (rootless) that this new Beta does infact ship the required intel libs needed and that HW transcoding is still working.

https://github.com/onedr0p/containers/issues/73
