### ISSUE TITLE
Network traffic on container when not in use !!

### ISSUE THREAD

**Issue by danishjoseph** [linuxserver/docker-plex#336]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior

Noticed constant network traffic in the plex container even when the application is not used. The issue occurred before when I was transferring files using the `file-browser` docker container and it became prominent when I setup network monitoring which constantly pings Ookla server and publishes to Grafana which itself is in separate container. 

<img width="1377" alt="Screenshot 2022-10-09 at 04 29 07" src="https://user-images.githubusercontent.com/56467833/194735104-2da97788-73c7-4317-a9c6-d1e9da4ce434.png">

## Environment
**OS:**
DietPi v8.8.1
**CPU architecture:** RPi 4 Model B (armv7l)
**How docker service was installed:**

## Docker logs

```
Docker is used for versioning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.
Critical: libusb_init failed
Dolby, Dolby Digital, Dolby Digital Plus, Dolby TrueHD and the double D symbol are trademarks of Dolby Laboratories.
```

**Comment by Roxedus** [comment]
This sounds like normal Plex behavior. Anyway there's no code in our container that does this.
