### ISSUE TITLE
Plex server is not updating to latest version

### ISSUE THREAD

**Issue by halpz** [linuxserver/docker-plex#343]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Plex server is not updating to the latest version ((1.29.1.6316) when I update the stack or recreate the container (I have selected the pull image switch in Portainer)
------------------------------

## Expected Behavior

the latest Plex server should be installed when I update the container

## Current Behavior

it is staying on it's current version (1.29.0.6244)

## Steps to Reproduce

1. login to Portainer
2. navigate to plex stack, editor
3. press update the stack below the docker-compose area
4.  press 'Re-pull image and redeploy' and update
5.  Plex is still on outdated version after deployment

## Environment
**OS:** Raspberry Pi OS 
**CPU architecture:** arm64
**How docker service was installed:** using docker-compose in Portainer

## Command used to create docker container (run/create/compose/screenshot)

---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/apps/plex:/config
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/movies:/movies
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/tv:/tv
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/home-videos:/other
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/eve-videos:/eve
    restart: unless-stopped

## Docker logs

Unselect
       
[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    100
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/40-chown-files
cont-init: info: /etc/cont-init.d/40-chown-files exited 0
cont-init: info: running /etc/cont-init.d/45-plex-claim
cont-init: info: /etc/cont-init.d/45-plex-claim exited 0
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/60-plex-update
Docker is used for versioning skip update check
cont-init: info: /etc/cont-init.d/60-plex-update exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun plex (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started

**Comment by j0nnymoe** [comment]
Sounds something specific to portainer, unfortunately we don't recommend nor support using portainer for deploying our images.

**Comment by willyb321** [comment]
Having same issue except not using portainer
[plexnowork.txt](https://github.com/linuxserver/docker-plex/files/9894611/plexnowork.txt)

**Comment by aptalca** [comment]
From the log:
`Docker is used for versioning skip update check`
