### ISSUE TITLE
Unraid upgraded to 6.11.3 after which Plex docker fails to start

### ISSUE THREAD

**Issue by chughes2020** [linuxserver/docker-plex#345]
Log reports the following - any ideas ?

[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

**** Server is unclaimed, but no claim token has been set ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)

**Comment by j0nnymoe** [comment]
Closing as no response from OP.
