### ISSUE TITLE
PlexPass update appears broken?

### ISSUE THREAD

**Issue by kingofzeal** [linuxserver/docker-plex#346]
When I restart my container to try to get the latest version of Plex, I see the following output:

```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    130
User gid:    135
-------------------------------------
**** Server already claimed ****
Atempting to upgrade to: 
https://downloads.plex.tv/plex-media-server-new//debian/plexmediaserver__amd64.deb:
2022-11-18 10:45:19 ERROR 404: Not Found.
########################################################
# Upgrade attempt failed, this could be because either #
# plex update site is down, local network issues, or   #
# you were trying to get a version that simply doesn't #
# exist, check over the VERSION variable thoroughly &  #
# correct it or try again later.                       #
########################################################
```

I have a VERSION environment variable set to `latest`.

I've looked through https://github.com/linuxserver/docker-plex/blob/7076b29ba0e8fd435738af54d76b21bd495bb0ec/root/etc/s6-overlay/s6-rc.d/init-plex-update/run, but the URL it builds to get the version (as best as I can tell) should be valid and give the expected result, so I'm not sure why the version is coming up blank.

I do know this was working at least a few months ago, but not sure what has changed since then. I have ensured I have the most recent image but get the same result. Plex does otherwise work, it's just the updater that seems to be broken.

**Comment by shiggins8** [comment]
@kingofzeal I just noticed this today as well. Plex functions fine but I was checking logs this morning and noticed the failure. Also not sure when it first started happening. Did you find a resolution?

**Comment by kingofzeal** [comment]
Unfortunately I haven't been able to peek any further than what I had already posted, including to be able to get the information requested by the bot. I may be able to work on getting that next week, but I can't be sure.

**Comment by j0nnymoe** [comment]
It would be helpful if you had actually provided the info that was requested in the template, then we'd be able to help (hence why I marked this issue as invalid).

**Comment by kingofzeal** [comment]
@j0nnymoe I understand. I did not see the template when I opened the issue, but provided everything I had gathered to that point - I just have not been able to gather the template information yet. I do plan on getting it for you eventually.

At this point, the issue also isn't extremely pressing for me - as noted, Plex still works, I just see an update icon whenever I view the web dashboard (which isn't frequent), so unfortunately it gets pushed down my list of things to do when I do have available time.

**Comment by shiggins8** [comment]
@j0nnymoe I think I've isolated the issue. 

In the docker container's [init-plex-update script](https://github.com/linuxserver/docker-plex/blob/7076b29ba0e8fd435738af54d76b21bd495bb0ec/root/etc/s6-overlay/s6-rc.d/init-plex-update/run), there is a curl command run on line 101 to determine the remote version. This curl command is failing. 

Manually running the command inside the container, I see the following error: 

"curl: (6) getaddrinfo() thread failed to start"

It seems like this is an [issue](https://askubuntu.com/questions/1405417/20-04-vs-22-04-inside-docker-with-a-16-04-host-thread-start-failures) with ubuntu 22.04 inside of Docker. Running any curl command inside the container seems to fail for me, however, on my Docker host machine, it runs without any issues. 

Was the base Docker image for the Plex container recently upgraded to Jammy Jellyfish (ubuntu 22.04)? If so, that may explain the issue.

**Comment by thespad** [comment]
It's an issue with your host/docker engine, not the container per se.

https://docs.linuxserver.io/faq#jammy

**Comment by shiggins8** [comment]
@j0nnymoe @kingofzeal so I did some more research, because I was curious. This issue is related to the newer version of glibc in the Jammy base image, compared to the Focal image - this makes a syscall to clone3 which is being blocked by the default seccomp in older versions of Docker. 

On one computer running Docker version 20.10.6, I observe this issue. On a machine running version 20.10.21, I do not.

**Comment by shiggins8** [comment]
> It's an issue with your host/docker engine, not the container per se.
> 
> https://docs.linuxserver.io/faq#jammy

ahh we commented at the same time haha. You are correct. Either update the Docker engine or add the seccomp policy config. Thanks for pointing that out!
