### ISSUE TITLE
[BUG] Unable to start container

### ISSUE THREAD

**Issue by clidx** [linuxserver/docker-plex#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The container won't start as of a few days ago. The error is `Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/init": stat /init: no such file or directory: unknown.` Recreating the container or starting a temporary container with no extra parameters doesn't work either.
I don't think any big events happened just before it stopped working, definitely not a full system update or an update to docker-ce. I then tried doing a full system update which didn't help. It stopped working when I reran `docker-compose pull` and tried to recreate the container.
I have tried rebooting, restarting the docker service. I checked the volumes which seems to be a common culprit but even when making a new container with no volumes, it doesn't run.
All my other linuxserver containers run. I actually just installed jellyfin so I could get some streaming going.
Normally I use docker-compose with a whole list of volumes etc, but to simplify debugging I am just trying to create and run a container with no special parameters with vanilla docker as per below command.

### Steps To Reproduce

`nas% docker run -d --name plex_temp2 -e PUID=1000 -e PGID=1000 lscr.io/linuxserver/plex
66a906941bf41ab6a2fe411e5e934ec9cb91a3392a2963e337ce3dfc46a2c5b8
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/init": stat /init: no such file or directory: unknown.`

### Environment

```markdown
- OS: Debian 11.6
- How docker service was installed: distro's package manager from official docker repos
```

### CPU architecture

x86-64

### Docker creation

```bash
Same as steps to reproduce.
```

### Container logs

```bash
Logs are empty for container plex_temp2 in steps to reproduce.
```

**Comment by aptalca** [comment]
Try removing the image and repulling. Could be a bad download or false tag.

**Comment by clidx** [comment]
> Try removing the image and repulling. Could be a bad download or false tag.

This didn't fix it unfortunately. Still the same error.

**Comment by clidx** [comment]
> Are you running this in LXC?

No, docker is running directly on Debian.

**Comment by clidx** [comment]
I pulled the new image 1.31.0.6654-02189b09f-ls153 released yesterday and now it works. Well that was strange but hopefully it doesn't happen again.

**Comment by wtvamp** [comment]
I just ran into this today...any idea what caused the issue or how it was fixed?

**Comment by clidx** [comment]
I can't really remember, I think a new version of the image came out, I
deleted everything and set up the container again and it worked.
