### ISSUE TITLE
[BUG] HDR HW Tone Mapping seems broken

### ISSUE THREAD

**Issue by functionaldude** [linuxserver/docker-plex#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When playing back HDR videos (and forcing a transcode) software transcoding is used.

### Expected Behavior

HDR videos should be also transcoded via hardware transcoding

### Steps To Reproduce

1. Add the /dev/dri device to the container
2. Enable HDR tone mapping in settings
3. Play something with HDR and force it to transcode

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- How docker service was installed: using apt
- Running Plex 1.67.1.3665-771934d3 (latest tag)
- non-HDR videos (even 4K) work via hardware transcode
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - VERSION=latest
    volumes:
      - /home/functionaldude/docker/plex/config:/config
      - /mnt/library/tv:/tv
      - /mnt/library/movies:/movies
    devices:
     - /dev/dri:/dev/dri
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    911
User GID:    911
───────────────────────────────────────
**** Server already claimed ****
**** creating video group video9kc1 with id 109 ****
**** adding /dev/dri/renderD128 to video group video9kc1 with id 109 ****
**** permissions for /dev/dri/card0 are good ****
No update required
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
```

**Comment by functionaldude** [comment]
This is probably a regression of https://github.com/linuxserver/docker-plex/issues/325

**Comment by j0nnymoe** [comment]
This needs to be reported to Plex direct and not us.

**Comment by aptalca** [comment]
`**** permissions for /dev/dri/card0 are good ****`
That's all we do, make sure the perms for the video device are good. Everything else is controlled by plex as they ship the drivers within their package.

**Comment by functionaldude** [comment]
Is there a way to downgrade plex inside the container? I tried to specify a version via the `VERSION`  environment variable, but I get a 404 when I restart the container. It seems like plex does not let me download an older version...
