### ISSUE TITLE
AudioEncoder need execution permissions (chmod +x)

### ISSUE THREAD

**Issue by jpenninkhof** [linuxserver/docker-plex#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During transcoding, the error message below appears:
_Jobs: Exec of /config/Library/Application Support/Plex Media Server/Codecs/EasyAudioEncoder-1847-linux-x86_64/EasyAudioEncoder/EasyAudioEncoder failed. (13)_

### Expected Behavior

Just run the encoder

### Steps To Reproduce

Watch a movie that requires audio transcoding

### Environment

```markdown
- OS:Linux
- How docker service was installed: from dockerhub
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
**** Server already claimed ****
**** permissions for /dev/dri/card0 are good ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
Critical: libusb_init failed
Jobs: Exec of /config/Library/Application Support/Plex Media Server/Codecs/EasyAudioEncoder-1847-linux-x86_64/EasyAudioEncoder/EasyAudioEncoder failed. (13)
```

**Comment by drizuid** [comment]
closing this as invalid. The user isn't running in a supported manner and docker doesn't come from dockerhub. The user specified "Linux" as the OS without any info to help with troubleshooting, and provided "docker-compose" as an example of their docker compose yaml.

**Comment by jpenninkhof** [comment]
Github is starting to be more and more a bureaucracy. Easy to hide behind the fences of rules, regulations, terms and templates. However, anyone with knowledge about an operating system knows that binaries should be marked as executable on the file system. The file mentioned (EasyAudioEncoder) does not have the executable flag, so it can never be started. Any attempt of Plex to start this binary will fail, in any container, on any OS. That's why I didn't elaborate very much. Anyway, do what it with you want. I know what to do when I download the container from dockerhub, thought of letting you know as well.
