### ISSUE TITLE
Download bandwidth limiting

### ISSUE THREAD

**Issue by GreyMoth** [linuxserver/docker-plex#364]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Streaming can be limited, but the download function has unlimited bandwidth. 

Proposal: implement optional limiting. 

### Reason for change

I am able to use the entire available bandwidth of 1Gbps when downloading from a friend’s server. Considering streaming bandwidth is already a feature, it would be sensible to add a limitation for download speed as well.

**Comment by thespad** [comment]
This isn't something we can implement at a container level, you'd need to make the request to Plex themselves.

**Comment by GreyMoth** [comment]
Thanks
