### ISSUE TITLE
[FEAT] Add heallthcheck to docker compose file

### ISSUE THREAD

**Issue by Sdub76** [linuxserver/docker-plex#365]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Plex occasionally hangs with an unresponsive database without crashing entirely.  Docker supports [adding a healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck) to the dockerfile to monitor a URL (a localhost Plex URL in this case) to ensure that the web server is still responsive.

It's then possible to add a [watchdog docker container](https://hub.docker.com/r/willfarrell/autoheal) that monitors for an unhealthy container and restarts it.  It would be great to help keep the service running.  

### Reason for change

Plex hangs occasionally forcing a manual container restart that I'd like to automate

### Proposed code change

Add something like this to the DOCKERFILE

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost/web/index.html#! || exit 1

**Comment by Roxedus** [comment]
We will not be adding healthchecks to our image, as discussed here linuxserver/docker-tautulli#79
You are free to add this to your compose/run

**Comment by Tw1zT3d2four7** [comment]
> For anyone searching this in the future, I added the following to my Docker run command to get the healthcheck working... didn't realize you could do that.
> 
> `--health-cmd='curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity' --health-interval=1m00s --health-timeout=15s --health-retries=3 --health-start-period=1m00s`
> 
> Then added an "autoheal=true" label to the container, and the willfarrell/autoheal application automatically restarts plex if it goes unresponsive.

so i added the autoheal docker compose to my stack and then added the healthchecks to each container in the stack and added the label autoheal=true once i did all of this i ran docker compose up then docker ps al containers running and are healthy, but how do i check if it's working? I didn't under stand where or how you used the following :  -health-cmd='curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity' --health-interval=1m00s --health-timeout=15s --health-retries=3 --health-start-period=1m00s      I assumed it was how you  started your autoheal binary autoheal app?
