### ISSUE TITLE
[BUG] arm32v7-latest image is built for linux/amd64 architecture

### ISSUE THREAD

**Issue by deadmoto** [linuxserver/docker-plex#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upgrading to the latest image leads to ` image with reference lscr.io/linuxserver/plex:arm32v7-latest was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64` error.

### Expected Behavior

Upgrade must succeed.

### Steps To Reproduce

1. Deploy `arm32v7-1.32.4` image (last one with linux/arm/v7 arch)
2. Upgrade to `arm32v7-latest`

### Environment

```markdown
- OS: Armbian 22.08.2 Jammy
- How docker service was installed: distro's packagemanager (apt)
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose.yml:

version: "3.9"
services:
  plex:
    platform: linux/arm/v7
    image: lscr.io/linuxserver/plex:arm32v7-latest
```

command: `/docker-compose up --build plex`
```


### Container logs

```bash
docker-compose output:

[+] Running 0/1
 ⠋ Container orangepi4-lts-plex-1  Recreate                                                                                       0.1s 
Error response from daemon: image with reference lscr.io/linuxserver/plex:arm32v7-latest was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64
`docker-compose` process finished with exit code 1
```
```

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2023-07-01-armhf/
