### ISSUE TITLE
[BUG]no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by alsaadie** [linuxserver/docker-plex#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

while pulling latest image from Raspberry pi4, im getting the below error:
$ docker pull lscr.io/linuxserver/plex:latest
latest: Pulling from linuxserver/plex
no matching manifest for linux/arm/v7 in the manifest list entries
 $ docker pull linuxserver/plex:latest
latest: Pulling from linuxserver/plex
no matching manifest for linux/arm/v7 in the manifest list entries
$ docker pull linuxserver/plex:latest --platform 'linux/armv7'
latest: Pulling from linuxserver/plex
no matching manifest for linux/armv7 in the manifest list entries

### Steps To Reproduce

docker pull linuxserver/plex:latest

### Environment

```markdown
- OS:
 cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
- How docker service was installed:
https://docs.docker.com/engine/install/raspberry-pi-os/#install-using-the-repository
```

### CPU architecture

arm64

### Docker creation

```bash
docker pull linuxserver/plex:latest
```

### Container logs

```bash
Can not pull image
```

**Comment by Roxedus** [comment]
We do not offer arm V7 images.
https://www.linuxserver.io/blog/a-farewell-to-arm-hf
