### ISSUE TITLE
[BUG] amdgpu: The CS has been rejected

### ISSUE THREAD

**Issue by interkelstar** [linuxserver/docker-plex#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I'm trying to enable video transcoding on my AMD GX-215JJ it fails (black screen) and there are errors in the log.

`/data/jenkins/conan_build/1112346209/conan/.conan/data/libdrm/2.4.115-1/plex/stable/build/42eba9224a0a19c9b983c233343e5610c7362833/meson-install/share/libdrm/amdgpu.ids: No such file or directory
/data/jenkins/conan_build/1112346209/conan/.conan/data/libdrm/2.4.115-1/plex/stable/build/42eba9224a0a19c9b983c233343e5610c7362833/meson-install/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: The CS has been rejected (-22), but the context isn't robust.
amdgpu: The process will be terminated.
****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.32.5.7349-8f4248874/PLEX MEDIA SERVER/dc089b53-1bf0-4c7b-d3d1d28b-a0ec89bf.dmp
Starting Plex Media Server. . . (you can ignore the libusb_init error)
/data/jenkins/conan_build/1112346209/conan/.conan/data/libdrm/2.4.115-1/plex/stable/build/42eba9224a0a19c9b983c233343e5610c7362833/meson-install/share/libdrm/amdgpu.ids: No such file or directory
/data/jenkins/conan_build/1112346209/conan/.conan/data/libdrm/2.4.115-1/plex/stable/build/42eba9224a0a19c9b983c233343e5610c7362833/meson-install/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: The CS has been rejected (-22), but the context isn't robust.
amdgpu: The process will be terminated.`

Log dump
https://github.com/alexbelgium/hassio-addons/files/12432596/dc089b53-1bf0-4c7b-d3d1d28b-a0ec89bf.dmp.log

### Expected Behavior

Transcoding is happening and no errors in log

### Steps To Reproduce

1. Go to 'Settings - Transcoding'
2. Check Use hardware
3. Try to open HEVC mediafile with converting enabled

### Environment

```markdown
- OS: Home Assistant OS
- How docker service was installed:
Add-on https://github.com/alexbelgium/hassio-addons/tree/master/plex
```

### CPU architecture

x86-64

### Docker creation

```bash
https://github.com/alexbelgium/hassio-addons/blob/master/plex/Dockerfile
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
-----------------------------------------------------------
 Add-on: Plex NAS
 Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices
-----------------------------------------------------------
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
 Add-on version: 1.32.5.7349-8f4248874-ls180
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.8.3
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
Local Disks mounting...
[19:55:13] INFO: Mounting NAS of type 
[19:55:13] INFO: Success! NAS mounted to /mnt/NAS
[19:55:13] INFO: Execute /config/addons_autoscripts/plex-nas.sh if existing
[19:55:13] INFO: ... no script found
Database stored in /share/plex
... creating /symlink
Using existing config
**** Server already claimed ****
**** permissions for /dev/dri/card0 are good ****
**** permissions for /dev/dri/renderD128 are good ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
/data/jenkins/conan_build/1112346209/conan/.conan/data/libdrm/2.4.115-1/plex/stable/build/42eba9224a0a19c9b983c233343e5610c7362833/meson-install/share/libdrm/amdgpu.ids: No such file or directory
/data/jenkins/conan_build/1112346209/conan/.conan/data/libdrm/2.4.115-1/plex/stable/build/42eba9224a0a19c9b983c233343e5610c7362833/meson-install/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: The CS has been rejected (-22), but the context isn't robust.
amdgpu: The process will be terminated.
****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.32.5.7349-8f4248874/PLEX MEDIA SERVER/57e6da7d-3498-420b-204ea0bf-0ea0ff8a.dmp
Starting Plex Media Server. . . (you can ignore the libusb_init error)
```

**Comment by aptalca** [comment]
AMD drivers are provided and controlled by Plex
Also, you're using a 3rd party provided docker image and you should seek help from them. We only support our images.

**Comment by aptalca** [comment]
> Does the unavailability of amdgpu.ids file or amdgpu: The CS has been rejected (-22) message tell nothing?

Nothing to us. The path listed is a build environment path, from when plex built their package and bundled the drivers. You should ask on the plex forums. But keep in mind that plex just introduced amd support a couple of months ago and it only supports sdr at the moment.

**Comment by Megamannen** [comment]
It's indeed the same in this docker image.
You can get further if you mount `libdrm` from host (but it still doesn't work for me)

```yaml
    volumes:
      - /usr/share/libdrm:/data/jenkins/conan_build/1113263720/conan/.conan/data/libdrm/2.4.115-3/plex/stable/build/73ee780ba6ea3ef381da6e7f229c475bfaf477ca/meson-install/share/libdrm:ro
```
