### ISSUE TITLE
[FEAT] Automatic optimization for tv?

### ISSUE THREAD

**Issue by ZoXx** [linuxserver/docker-plex#379]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hello,

is there a way or would this actually be a feature request that newly added files are automatically optimized for the tv? I use the docker version, maybe there is a way to implement this here?

### Reason for change

Save time.

**Comment by j0nnymoe** [comment]
You would ask Plex directly for this. We just package the software.
