### ISSUE TITLE
[BUG] About "deprecate armhf" message

### ISSUE THREAD

**Issue by glensc** [linuxserver/docker-plex#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You say you have **deprecated** armhf (As announced [here](https://www.linuxserver.io/blog/a-farewell-to-arm-hf)),. but seems you really have **REMOVED** armhf support.

Typically deprecated means you can still use it. Perhaps correct the wording?

### Steps To Reproduce

```
$ docker pull linuxserver/plex
Using default tag: latest
latest: Pulling from linuxserver/plex
no matching manifest for linux/arm/v7 in the manifest list entries
```

### Environment

```markdown
- OS: Raspbian GNU/Linux 10 (buster)
- How docker service was installed:

```

### CPU architecture

armv7l

### Docker creation

```bash

```

### Container logs

```bash

```

**Comment by j0nnymoe** [comment]
You can still use older builds though we suggest you don't.

**Comment by glensc** [comment]
I guess plex itself still provides builds for arm arch, so could build docker image locally?

**Comment by j0nnymoe** [comment]
Sure if you wanted to, but our armhf baseimages are no longer supported/maintained so any bugs won't be fixed.

**Comment by glensc** [comment]
seems PMS itself doesn't provide package anymore?

- https://www.plex.tv/media-server-downloads/

<img width="469" alt="image" src="https://github.com/linuxserver/docker-plex/assets/199095/8db361f1-57eb-44e0-b095-3ac41039b0e9">

**Comment by j0nnymoe** [comment]
Armv7 is armhf.

**Comment by glensc** [comment]
So I've come up with something like this:

1. take latest linux-server/plexmediaserver armhf docker image
2. find latest. plexmediaserver package
3. install it to docker image
4. tag it locally and use that image

WARNING: Some jq and bash-foo to download if missing

<details><summary>Dockerfile</summary>

```dockerfile
# Since armhf images are no longer published:
# - https://github.com/linuxserver/docker-plex/issues/380
#
# But want to receive PMS updates:
# 1. take latest linux-server/plexmediaserver armhf docker image
# 2. find latest plexmediaserver package
# 3. install it to docker image
# 4. tag it locally and use that image
#
# Author: Elan Ruusamäe <glen@pld-linux.org> 

# syntax=docker/dockerfile:1

# Last armhf image published
FROM linuxserver/plex:1.32.4.7195-7c8f9d3b6-ls174 AS plex-base

FROM alpine AS download
RUN apk add curl jq
WORKDIR /tmp

ENV \
        PLEX_DISTRO="debian" \
        PLEX_BUILD="linux-armv7neon" \
        PLEX_DOWNLOADS="https://plex.tv/api/downloads/5.json"

RUN \
        --mount=type=cache,id=plex-cache,target=/usr/src \
        <<eot
        set -eux

        curl -sSf -X GET "$PLEX_DOWNLOADS" -o downloads.json

        jq \
                --arg distro "$PLEX_DISTRO" \
                --arg build "$PLEX_BUILD" \
                '.computer.Linux.releases[] | select (.distro==$distro and .build==$build)' \
                 > release.json < downloads.json
        url=$(jq -r '.url' < release.json)
        checksum=$(jq -r '.checksum' < release.json)
        filename=$(basename "$url")
        filepath="/usr/src/$filename"

        if [ ! -f "$filepath" ]; then
                curl -sSf -L "$url" -o "$filepath.tmp"
                echo "$checksum $filepath.tmp" | sha1sum -c
                mv "$filepath.tmp" "$filepath"
        fi

        cd /usr/src
        ls -l
        echo "$filename" > plexmediaserver-latest
eot

FROM plex-base

RUN \
        --mount=type=cache,id=apt,target=/var/cache/apt \
        --mount=type=cache,id=apt-lists,target=/var/lib/apt/lists \
        --mount=type=cache,id=plex-cache,target=/usr/src \
        <<eot
        set -xeu

        cd /usr/src
        filename=$(cat plexmediaserver-latest)
        ls -l "$filename"
        dpkg -i "$filename"
eot
```

</details>

```
root@ba32a4bac86c:/# apt info plexmediaserver
Package: plexmediaserver
Version: 1.32.6.7557-1cf77d501
Status: install ok installed
Priority: optional
Section: video
Maintainer: Plex Inc <noreply@plex.tv>
Installed-Size: 160 MB
Homepage: https://plex.tv
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Plex organizes all of your personal media so you can easily access and enjoy it.
```

**Comment by j0nnymoe** [comment]
You could just run the last latest image of our Plex container that works on armhf and just set the Version ENV to `latest` and providing you have plexpass connected, updates will get installed on container restart.

**Comment by glensc** [comment]
@j0nnymoe speaks of this script (thanks!):
- https://github.com/linuxserver/docker-plex/blob/1.32.6.7557-1cf77d501-ls189/root/etc/s6-overlay/s6-rc.d/init-plex-update/run

I prefer pre-built docker image, so re-creation wouldn't have to download and install. possibly faster startup, but definitely more predictable outcome.

**Comment by thespad** [comment]
Just be aware that at some point it's going to break because Plex will expect dependencies that don't exist in the armhf image, or are too out of date to be supported.
