### ISSUE TITLE
[FEAT] vim editor inside of container

### ISSUE THREAD

**Issue by Vortilion** [linuxserver/docker-plex#382]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Being able to use vim inside the container, or at least be able to use apt-get update and install it myself.

### Reason for change

Easier to edit Preferences.xml inside the container directly instead of having to copy it over, edit it and copy it back.

**Comment by Roxedus** [comment]
Doing commands directly inside the container is not a supported usecase. Apt is available to you, as is the [Package Install](https://github.com/linuxserver/docker-mods/tree/universal-package-install#package-install---universal-docker-mod) mod.

**Comment by Vortilion** [comment]
When I try to execute apt-get update or install I'm only getting error messages. It cant reach ubuntu archives. Internet does work though.
