### ISSUE TITLE
[BUG] Plex clients trying to connect to {containerIP}-{hash}.plex.direct

### ISSUE THREAD

**Issue by louisgrasset** [linuxserver/docker-plex#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I discovered with my Adguard that my plex clients were trying to connect to the following type of IP.

`172-24-0-25.XXXXXXXXXXXXXXXXXXXXXXXXXXX.plex.direct`

I tryied to change some configuration tweaking I saw on reddit: https://www.reddit.com/r/pihole/comments/ghr6ef/plex_server_does_strange_this_loop.

### Expected Behavior

Rely on the server IP such as `10.10.0.2.XXXXXXXXXXXXXXXXXXXXXXXXXXX.plex.direct`

### Steps To Reproduce

Not sure how to describe it.

### Environment

```markdown
- OS: Ubuntu Derver
- How docker service was installed:
Portainer with docker-compose.yml pulled from github repo.
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.9"
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: always
    ports:
      - 1900:1900
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32410:32410
      - 32411:32411
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32400:32400
      - 32469:32469
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK=022
    volumes:
      - plex:/config
      - /path/to/movies:/data/movies
      - # and so on
    devices:
      - /dev/dri:/dev/dri
    networks:
      - traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
```
```


### Container logs

```bash
User UID:    1000

User GID:    1000

───────────────────────────────────────

**** Server already claimed ****

**** permissions for /dev/dri/renderD128 are good ****

**** permissions for /dev/dri/card0 are good ****

Docker is used for versioning skip update check

[custom-init] No custom files found, skipping...

Starting Plex Media Server. . . (you can ignore the libusb_init error)

no crontab for abc

no crontab for root

[ls.io-init] done.
```

**Comment by aptalca** [comment]
That's expected behavior. The server advertises IPs and addresses 1. it discovers and 2. the user sets in the custom access URLs setting. The clients will attempt to connect to all of them and pick one that works.

**Comment by louisgrasset** [comment]
Sure, but in a docker context, is it really useful? At least, in my use case where my clients are not containers, would it be possible to tweak something? 

It's making direct connection kind of hesitating since it first try to connect to non accessible endpoints

**Comment by aptalca** [comment]
Other containers like overseer and tautulli often connect via the container IP.

In any case, that's expected Plex behavior, nothing we control in the docker image. You can report it to them.

**Comment by j0nnymoe** [comment]
Set your URLs up correctly within the network and this won't be a problem.
