### ISSUE TITLE
Cannot connect to Plex webui running in my container

### ISSUE THREAD

**Issue by adeldiah** [linuxserver/docker-plex#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I browse to the Plex server via my media server's ip I get the message "This site can't be reached".

The URL is http://serverip:32400

I get this message whether I attempt access while physically on the media server or remotely via a web browser

### Expected Behavior

To be able to connect to Plex service via webui via my media servers IP and the Plex port

### Steps To Reproduce

1. From web browser type http://serverip:32400

### Environment

```markdown
- OS: Sonoma 14.1.2
- How docker service was installed: In portainer as a stack
```

### CPU architecture

arm64

### Docker creation

```bash
version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=501
      - PGID=502
	  - VERSION=latest
      - TZ=America/Los Angeles
      - PLEX_CLAIM= #Removed
    volumes:
      - /Users/<user>/Documents/Docker/Plex/config:/config
      - /Volumes/Elements/data/media:/data/media/
    network_mode: host
    restart: "unless-stopped"
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    501
User GID:    502
───────────────────────────────────────
**** Server already claimed ****
No update required
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
Critical: libusb_init failed
```

**Comment by j0nnymoe** [comment]
Host mode doesn't work on macOS.

**Comment by adeldiah** [comment]
Thank you. So just remove the line from the yaml and re-deploy the stack?

**Comment by adeldiah** [comment]
I got it to work by mapping the ports correctly. Thank you for pointing out that host network mode is not supported.

**Comment by pebroz** [comment]
Same here, quickly reverted to version [1.32.8.7639-fb6452ebf-ls196](https://github.com/linuxserver/docker-plex/releases/tag/1.32.8.7639-fb6452ebf-ls196) to have the service working.

Host mode on Linux (Unraid). Thanks for posting the information.

**Comment by ItsJamesMurray** [comment]
Am I good to revert to [1.32.8.7639-fb6452ebf-ls196](https://github.com/linuxserver/docker-plex/releases/tag/1.32.8.7639-fb6452ebf-ls196) and then go back to latest once resolved?  Or am I better off not using host and and mapping ports?

**Comment by j0nnymoe** [comment]
There's nothing to be resolved here? OP was using macos and that doesn't allow host mode.

**Comment by adeldiah** [comment]
Resolved. Host mode not supported on MacOS.

**Comment by andrewtnas** [comment]
I'm not on macOS (running ubuntu) but having the same issue, the container is up and running with no issues in the log, but can't access the web view. Any solution?

**Comment by aptalca** [comment]
Docker desktop also doesn't support host networking

Make sure to install docker engine from the official docker repo (not Ubuntu repo)
