### ISSUE TITLE
[FEAT] Alpine based docker image

### ISSUE THREAD

**Issue by Feriman22** [linuxserver/docker-plex#386]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi,

I'd suggest to build an alpine based docker image instead of ubuntu to reduce the size of the image and may speed up the container.

Is it possible to do that, or is there any limitation?

Thanks,
Feriman

### Reason for change

Reduce image size
Speed up container

**Comment by j0nnymoe** [comment]
Not something we would look at due to Plex requiring glibc over musl and also losing features like Nvidia support.
