### ISSUE TITLE
[BUG] PUID & PGID have not worked for some time. Changing to original PLEX labels works.

### ISSUE THREAD

**Issue by MrCee** [linuxserver/docker-plex#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting the PUID and the GUID has not worked for some time, I think I actially moved away from Linuxserver.io because I couldn't delete files from the Plex interface even though:

id plex >
uid=1031(plex) gid=65536(sc-automedia)

PUID=1031
PGID= 65536

I have my media folders owned by plex:sc-automedia with permissions 775.

The values for the  labels don't really work with the code, because the code is expecting to see PLEX_UID and PLEX_GID when deleting files..

### Expected Behavior

#      - PUID=1031   # does not work as suggested on linuxserver
#      - PGID=65536  # does not work as suggested on linuxserver

### Steps To Reproduce

If we use the original Plex labels in docker commands or compose files, everything runs perfectly.
      - PLEX_UID=1031 #original PMS will work fine with folder permissions and 
      - PLEX_GID=65536 # use these working labels instead

### Environment

```markdown
- OS:Synology DSM, 
- How docker service was installed: Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - TZ=Australia/Sydney
      - VERSION=latest
#      - PUID=1031   # does not work as usggested on linuxserver
#      - PGID=65536  # does not work as suggested on linuxserver
      - PLEX_UID=1031
      - PLEX_GID=65536
      - HOSTNAME="myplex.myserver.me"
      - PLEX_CLAIM=xxx
      - SERVER_IP=xxx.xxx.xxx.xxx
      - LOCAL_NETWORK=xxx.xxx.xxx.xxx/24
      - ports="32400:32400"
    volumes:
      - /volume1/docker/plex/config:/config
      - /tmp/plex:/transcode
      - /volume1/video:/volume1/video
      - /volume1/music:/volume1/music
      - /volume1/radio:/volume1/radio
    image: plexinc/pms-docker:latest
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    restart: unless-stopped
```

### Container logs

```bash
I didn't dig through the logs because changing the labels obviously works with all the permissions I have had set for years.
```

**Comment by Roxedus** [comment]
Logs is important. post logs from a restart of the container, with PUID and PGID set.

**Comment by MrCee** [comment]
I thongs the logs would be more detailed this, not seeing where to increase verbosity.
Running on Synology Docker..

**Comment by aptalca** [comment]
Those logs are not from our image.

The compose yaml you posted above include duplicate image settings, one pointing to ours, one pointing to Plex's. Those are the settings you need to fix.

**Comment by MrCee** [comment]
Aha! Sorry I didn't see this late last night, I have removed the duplicate image settings and all is working well again....

**Comment by MrCee** [comment]
```
