### ISSUE TITLE
[BUG] Intel QSV transcoding broken in ls211

### ISSUE THREAD

**Issue by x5nder** [linuxserver/docker-plex#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgrading from ls210 to ls211 on Unraid, hardware transcoding with Intel QSV is no longer working. Plex throws an error. Downgrading to ls210 immediately fixes the issue. Also reported here: https://forums.unraid.net/topic/130080-plex-hardware-transcoding-suddenly-not-working-transcoder-crashing/

### Steps To Reproduce

Start Plex. Start playing a 4K file. Open video settings, manually select 1080p quality. Up to ls210: file gets transcoded and plays in lower quality. On ls211: Plex throws an error.

### Environment

```markdown
- OS: Unraid 6.12.8
- How docker service was installed: Unraid Community Apps
```

### CPU architecture

x86-64

### Docker creation

```bash
(default Unraid settings)
```

### Container logs

```bash
-
```

**Comment by homerr** [comment]
Is there nothing being logged by the container at all?

**Comment by HannesJo0139** [comment]
Could be an upstream issue since I just upgraded Openmediavault to v7 (Debian to v12) and also having problems getting hw accel running. Official docker image is also not working. There is also an announcement not to upgrad when sitting on Ubuntu.
[https://forums.plex.tv/t/ubuntu-24-04-hw-transcoding/873765](url)
In the other hand going back to earlier images dows not work for me.

Possibly a coincidence, possibly related.

**Comment by Rolodo** [comment]
Same for me some files don't transcode anymore.
I can provide stuff if you let me know what and how to get them.

Thanks

**Comment by factorywiz** [comment]
I have had a very similar issue with two different model Synology NAS units using QSV. Hardware accelerated transcoding works for 1080p source files but not 4K source files. 4K source files go into software transcoding immediately, the CPU maxes out, etc. If I downgrade my container to 1.40.2.8395-c67dce28e-ls218 or below - 4K files will transcode with the (hw) tag again. Only 4K files seem to be affected.

**Comment by Elwyr** [comment]
> I have had a very similar issue with two different model Synology NAS units using QSV (one Intel Celeron J3455 and one J4125). Hardware accelerated transcoding works for 1080p source files but not 4K source files. 4K source files go into software transcoding immediately, the CPU maxes out, etc. If I downgrade my container to 1.40.2.8395-c67dce28e-ls218 or below - 4K files will transcode with the (hw) tag again. Only 4K files seem to be affected.

Same experience here on a Synology 920+, downgrading to ls218 works for now, thanks.

**Comment by QuigonJohnn** [comment]
> > I have had a very similar issue with two different model Synology NAS units using QSV (one Intel Celeron J3455 and one J4125). Hardware accelerated transcoding works for 1080p source files but not 4K source files. 4K source files go into software transcoding immediately, the CPU maxes out, etc. If I downgrade my container to 1.40.2.8395-c67dce28e-ls218 or below - 4K files will transcode with the (hw) tag again. Only 4K files seem to be affected.
> 
> Same experience here on a Synology 920+, downgrading to ls218 works for now, thanks.

I'm having the same issue with 4K media on the 920+, but downgrading the container doesn't solve the problem for me.

**Comment by factorywiz** [comment]
I believe you are correct. After making this post I found that there was actually mention of a PLEX issue breaking it for certain generations of CPU/iGPU. Here is the link.

Multiple mentions of it affecting Apollo Lake and Gemini Lake iGPUs. Appears the container is fine except for the underlying Plex bug.

https://forums.plex.tv/t/hdr-tone-mapping-not-compatible-with-hw-accelerated-transcoding-anymore-ds920/880627
