### ISSUE TITLE
[FEAT] option to disable Plex Tuner Service

### ISSUE THREAD

**Issue by fixmycode** [linuxserver/docker-plex#393]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Plex runs a "Plex Tuner Service" process even when the DVR settings are not set up. Users have successfully disabled this process by various means in the past without any repercussion.

### Reason for change

Plex users have been asking for this option to be added to the app for 7 years, and would be great to stop caring about a service that we don't use. Some users have reported performance increase and less resource waste after disabling it:
- https://forums.plex.tv/t/feature-request-option-to-disable-plex-tuner-service-when-dvr-not-configured/189760
- https://forums.plex.tv/t/dvr-option-to-disable-plex-tuner-service-when-dvr-not-configured/216403

### Proposed code change

Using any of the methods mentioned on the threads above, like removing the executing permission to the service, should be sufficient, non-destructive, and easily reversible.

```bash
chmod -x "/usr/lib/plexmediaserver/Plex Tuner Service"
pkill -9 -f "Plex Tuner Service"
```

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by Roxedus** [comment]
We will not implement this, You can however [customize] the container yourself to achieve this.
