### ISSUE TITLE
[BUG] Plex Pass modal doesn't close on first run

### ISSUE THREAD

**Issue by bevel2010** [linuxserver/docker-plex#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On first run, the "How Plex Works" dialog appears. On the next screen the "Plex Pass" modal appears in front of the "Server Setup" screen and cannot be closed by clicking the 'X' close box - thereby blocking access to the "Server Setup" screen and stopping anyone from configuring their new installation

### Expected Behavior

The "Plex Pass" modal should close when clicking the 'X' close box in the top right, thereby allowing a new user to progress with server setup and start using Plex

### Steps To Reproduce

- Create a fresh install of Debian 12 (I created a Deb. 12 instance using Linode)
- Install Docker using convenience script (https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script)
- Create new directory with `docker-compose.yml` as follows:
```
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./config:/config:rw
    ports:
      - 32400:32400/tcp
    restart: unless-stopped
```
- Run `docker compose up -d`
- SSH into the instance, forwarding port 32400: `ssh -L 32400:localhost:32400 root@<instance-ip>`
- Open a web browser (Firefox 129.0 64-bit + OS X 14.6.1) in incognito mode and access Plex at [http://localhost:32400/web/](http://localhost:32400/web/)
- Log into plex (I used email)
- On "How Plex Works", click button labeled 'Got It!' at bottom of screen
- When "Plex Pass" modal appears (covering the "Server Setup" screen), click the "X" button to close the modal in the top right

Expected: the Plex Pass modal should close
Observed: the Plex Pass modal does not close

Note this was discussed on Reddit 21 days ago - https://www.reddit.com/r/PleX/comments/1e869y7/cant_close_the_plex_pass_popup_so_cant_access_plex/

### Environment

```markdown
- OS: Docker engine (Docker version 27.1.1, build 6312585) running on Debian 12 Bookworm
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./config:/config:rw
    ports:
      - 32400:32400/tcp
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

**** Server is unclaimed, but no claim token has been set ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
Critical: libusb_init failed
```

**Comment by j0nnymoe** [comment]
This is going to be unrelated to the container and a bug with plex itself.

**Comment by bevel2010** [comment]
I was able to find a related bug post on the plex forums - https://forums.plex.tv/t/dialog-window-pass-plex-not-closed/883603/6

Apologies. I will close this issue :)
