### ISSUE TITLE
[BUG] Unwatched markers don't work

### ISSUE THREAD

**Issue by hot36952** [linuxserver/docker-plex#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The server is installed on unraid and the client is installed on window10.
Every time I open the client to view unwatched markers, it sometimes works and sometimes doesn't.

Unwatched markers don't work.
![0001](https://github.com/user-attachments/assets/727c8931-2ee2-4c4f-9acc-4dbddd2bce0a)
![0002](https://github.com/user-attachments/assets/d57821c1-acd7-4d34-b165-1a5b844abd43)

Unwatched markers work.
![0003](https://github.com/user-attachments/assets/64a22772-677d-4a2b-9ff9-71c971e6c355)

### Steps To Reproduce

1.open the client.
2.view unwatched markers.
3.It works or it doesn't.

### Environment

```markdown
- OS:Unraid 6.12.10
- How docker service was installed:Unraid Community Applications
```

### CPU architecture

x86-64

### Docker creation

```bash

```
![0004](https://github.com/user-attachments/assets/3be35f77-6b53-487d-9f3b-9e92dbec9c58)

### Container logs

```bash
text  error  warn  system  array  login  

Connection to localhost (127.0.0.1) 32400 port [tcp/*] succeeded!
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 1.40.5.8854-f36c552fd-ls228
Build-date: 2024-08-14T17:32:00+00:00
───────────────────────────────────────
    
**** Server already claimed ****
**** creating video group video47w2 with id 18 ****
**** adding /dev/dri/renderD128 to video group video47w2 with id 18 ****
**** permissions for /dev/dri/card0 are good ****
Docker is used for versioning skip update check
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
[ls.io-init] done.
Critical: libusb_init failed
```

**Comment by aptalca** [comment]
That's a Plex issue, not a docker one. You should report to them.

**Comment by hot36952** [comment]
> That's a Plex issue, not a docker one. You should report to them.

Please look at the picture and description, I think it's plex's problem.

**Comment by aptalca** [comment]
That's what I said. We are not Plex. We do not develop Plex. We package Plex in a docker container. That's all. 

Any issue with Plex needs to be reported to Plex, not us
