### ISSUE TITLE
Does not update to latest plex.

### ISSUE THREAD

**Issue by calmcacil** [linuxserver/docker-plex#41]
Restarting the container does not update it to the latest version of plex. Seems to be stuck on 0.9
*** Running /etc/my_init.d/30_update_plex.sh...
Using version: 0.9.16.6.1993-5089475 from Public latest
No need to update!

However latest plex is 1.0.0.2261-a17e99e.

**Comment by sparklyballs** [comment]
image was manually updated yesterday to pick up the change.
repull the image, keeping your data intact.

**Comment by calmcacil** [comment]
Just repulled, and restarted it, still not working.

**Comment by j0nnymoe** [comment]
@calmcacil I have just done a fresh pull of plex on my unraid server, it installed Version 1.0.0.2261 for me. Did you remove the container correctly before you repulled it?

**Comment by zaggash** [comment]
To update a dockrt image:
Docker pull <image id>
Docker stop <container id>
Docker rm <container id>
Recreate container like the first time and you're good, no data loss, if you use the same config and data folder.
