### ISSUE TITLE
Update to v1.0 not detected

### ISSUE THREAD

**Issue by JacquesBurger** [linuxserver/docker-plex#42]
Update issue, seems to be stuck at v0.9.16.6.1993 and doesn't do v1.0.0.2261

The GUI does detect the updates, seems the update script doesn't for some reason.

**From the logs:**
Using version: 0.9.16.6.1993-5089475 from Public latest
No need to update!

**Seems that manually stepping through works and takes me to 1.0:**
curl -L 'https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu' -o /tmp/plexmediaserver.deb
dpkg -i /tmp/plexmediaserver.deb
rm -f /tmp/plexmediaserver.deb

**Soon as I restart it reverts back to 0.9:**
*** Running /etc/my_init.d/30_update_plex.sh...
Using version: 0.9.16.6.1993-5089475 from Public latest
Upgrading from version: 1.0.0.2261-a17e99e to version: 0.9.16.6.1993-5089475
--2016-06-28 06:52:57--  https://downloads.plex.tv/plex-media-server/0.9.16.6.1993-5089475/plexmediaserver_0.9.16.6.1993-5089475_amd64.deb

**Comment by sparklyballs** [comment]
see https://github.com/linuxserver/docker-plex/issues/41
