### ISSUE TITLE
Execute error of codecs

### ISSUE THREAD

**Issue by tronder88** [linuxserver/docker-plex#43]
Getting errors when starting to play video.

Reason: need exec acces to plex config folder. Using docker on OMV which refuses execute. 
Please move codec folder to docker image location. and rest of plex library can be as usual.

Thank you for looking into this

**Comment by j0nnymoe** [comment]
@tronder88 Could you provide with some more details please? OMV Docker Config Screenshots / run command info

**Comment by tronder88** [comment]
Just copying in a comment which describes the issue good for OMV from Plex forums: 

_If PMS is installed on OMV (OpenMediaVault) using the provided plugin, /plexmediaserver/Library/....... is not installed on the OS drive. It is placed on a non-OS data drive mounted under /media. These data drives are by default set noexec in fstab._

https://forums.plex.tv/discussion/223233/plex-not-playing-anything

My comment: This also applies to docker, since one need a config folder. On OMV the default mount option is noexec on the mountpoint in fstab. Solution is to edit fstab with remove the noexcec and change owner of folder with exec permisison. files are OMV default only read write.

The codecs in your dockerimage is located in a separate folder, and I suggest that they can be moved to image, as docker files has exec permissions in OMV. 

I did change the fstab and added exec permission, as suggested in mentioned link. All works. But it is not simply plug an play as with all other linuxserver docker images

**Comment by nicjo814** [comment]
I'm not sure I understand the issue completely. You are running Docker on OMV (with the Docker plugin or wthout?) and the codecs end up on one of the OMV data drives that are set to noexec in fstab (via the config folder)?

**Comment by zaggash** [comment]
You can run the container with no /config specified.
The data will go to the default docker folder but you will loose the ease to backup the files.

**Comment by nicjo814** [comment]
Reading the issue again I think the problem should be fixed if you use the OMV Docker plugin since it re-mounts (bind) the complete docker folder (/var/lib/docker by default or some other folder on the data drives if it's been relocated via the plugin) removing the noexec option on the mountpoint. @tronder88 could you test this?

**Comment by tronder88** [comment]
@nicjo814 : Yes you are correct. Codecs are from plex version 1 part of /config docker mountpoint.

I am using the Docker GUI in OMV. Also I prefer to have a separate configfile in case of updates etc. as library will be separate from docker. 

I did need to remove the noexec option on the drive holding the config folder. It is up an running as I type this. and is no problem for me, but for other people it could be different.
