### ISSUE TITLE
NFS setup issues.

### ISSUE THREAD

**Issue by buehler** [linuxserver/docker-plex#47]
Hey Guys

I'm using your image on my docker server (managed through docker cloud).
Yesterday I set up the image and this morning I get the following log messages:
```bash
2016-07-22T03:17:12.500184068Z Database corruption: sqlite3_statement_backend::prepare: unable to open database file for SQL: PRAGMA cache_size=4000
```

After a restart of the image, the server does not reach a stable state and I get the following error:
```bash
Error: Unable to set up server: sqlite3_statement_backend::prepare: unable to open database file for SQL: PRAGMA cache_size=4000 (N4soci10soci_errorE)
```

The setup has 1 speciality, I mount the config directory via NFS to my NAS.

Container -> Host -> NAS.

Is there any solution for this or am I doomed? :-)

Cheers
Chris

**Comment by sparklyballs** [comment]
Is this a new installation ?

**Comment by buehler** [comment]
What do you mean by new installation?
The image is freshly installed yea.

**Comment by j0nnymoe** [comment]
I believe this could be a permissions issue possibly at the NFS point.
Could you copy/paste your create/run command?

Thanks

**Comment by buehler** [comment]
Ofcourse :-)

```
docker run -d --name=plex --net=host \
                   -e PGID=100 \
                   -e PUID=1024 \
                   -e VERSION=latest \
                   -v /var/docker-mounted/svc-plex/data:/data \
                   -v /var/docker-mounted/svc-plex/config:/config
                   linuxserver/plex:latest
```

The volume `/data` is a symlink to my NAS which is NFS mounted. The whole `svc-plex` folder is on the mounted volume as well (`/mnt/nas`).

**Comment by buehler** [comment]
addition: I looked up the NFS user and group ids and thus using the `PUID` and `PGID` variables to match the nfs ones

**Comment by buehler** [comment]
Actually.. the problem fixed itself.
