### ISSUE TITLE
An update is available. Please install manually.

### ISSUE THREAD

**Issue by hyness** [linuxserver/docker-plex#49]
I am running the latest docker image.  My server is currently at version 1.0.0.2261.  My container will not update.  In the server settings, it says "An update is available. Please install manually" with a link to the deb file.  The What's New indicates the version available is 1.0.2.2413.

**Comment by sparklyballs** [comment]
log in via the webui, then restart the docker and it updates to

Version 1.0.2.2413

**Comment by hyness** [comment]
I followed your instructions, its still not fixed.  This message was in the console...

    plex_1    | *** Running /etc/my_init.d/10_dbus.sh...
    plex_1    | *** Running /etc/my_init.d/20_apt_update.sh...
    plex_1    | *** Running /etc/my_init.d/30_update_plex.sh...
    plex_1    | Target version: Version not set, Defaulting to supplied version
    plex_1    | ERROR: No version found, running installed version 1.0.0.2261-a17e99e

**Comment by sparklyballs** [comment]
set this in the run / create command

-e VERSION=latest

**Comment by hyness** [comment]
Sorry, I did add that environment variable before I created this issue, but I neglected to recreate the container.  I've now done that and it updated.  Thanks for the help.
