### ISSUE TITLE
Support plexpass

### ISSUE THREAD

**Issue by danielunderwood** [linuxserver/docker-plex#51]
Could we support plexpass? The changes could be done by passing plex credentials in a file or environment variables. [plexupdate](https://github.com/mrworf/plexupdate) could make it quite easy to do this or provide an example of how to get the plexpass download.

Doing this could also fix the download link, which I assume has been broken since the 1.0 update.

I wouldn't mind submitting a PR for this, but I would like to know if it would be fine to use plexupdate directly. I'm not sure if it would make a difference, but plexupdate seems to be licensed by GPLv2.

**Comment by mattberther** [comment]
Plexpass has been enabled for some time (https://github.com/linuxserver/docker-plex/blob/master/init/30_update_plex.sh#L15-L35). If you have your PlexOnlineToken set in Preferences.xml then setting `-e VERSION=latest` should retrieve the latest Plexpass version and `-e VERSION=public` should retrieve the latest public version.

**Comment by danielunderwood** [comment]
Oops. I saw the `VERSION` environment variable in the readme, but didn't realize that setting it to `latest` would pick up the plex pass version since the way of authenticating with the token wasn't mentioned. Should the readme be changed to be more explicit or is is fine?

**Comment by j0nnymoe** [comment]
We probably need to adjust the readme to mention the plex pass stuff but there is more info on it here: https://www.linuxserver.io/index.php/2016/04/07/changes-to-our-plex-docker-container/
