### ISSUE TITLE
Experiencing random container crashes

### ISSUE THREAD

**Issue by rjorgenson** [linuxserver/docker-plex#55]
I've noticed that my plex container will occasionally crash and restart itself. Here is the excerpt from docker logs

```
Starting Plex Media Server.
Starting dbus-daemon
Starting Avahi daemon
Found user 'avahi' (UID 104) and group 'avahi' (GID 107).
Successfully dropped root privileges.
avahi-daemon 0.6.31 starting up.
dbus_bus_get_private(): Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
WARNING: Failed to contact D-Bus daemon.
avahi-daemon 0.6.31 exiting.
6 3000 /config/Library/Application Support
8192
Aug 27 01:59:39 pms syslog-ng[120]: syslog-ng starting up; version='3.5.3'
Starting Avahi daemon
Found user 'avahi' (UID 104) and group 'avahi' (GID 107).
Successfully dropped root privileges.
avahi-daemon 0.6.31 starting up.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface ens160.IPv6 with address fe80::20c:29ff:fe85:46bc.
New relevant interface ens160.IPv6 for mDNS.
Joining mDNS multicast group on interface ens160.IPv4 with address 192.168.1.53.
New relevant interface ens160.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::20c:29ff:fe85:46bc on ens160.*.
Registering new address record for 192.168.1.53 on ens160.IPv4.
Registering HINFO record with values 'X86_64'/'LINUX'.
Server startup complete. Host name is pms.local. Local service cookie is 4113966059.
Aug 27 02:17:02 pms /USR/SBIN/CRON[1549]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Got SIGTERM, quitting.
Leaving mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Leaving mDNS multicast group on interface ens160.IPv6 with address fe80::20c:29ff:fe85:46bc.
Leaving mDNS multicast group on interface ens160.IPv4 with address 192.168.1.53.
avahi-daemon 0.6.31 exiting.
*** Shutting down runit daemon (PID 107)...
*** Killing all processes...
```

Doesn't seem to be anything related to the restart in the log that I can see. Any idea how to get more information on why this might be happening?

**Comment by rjorgenson** [comment]
Of note is that the time in the logfile for the last cron job is in the future. It restarted around 11:50PM August 26th. Date on the system is correct, not sure why the time in the container is incorrect, I logged in to the machine and it all appears to be GMT. I don't have TZ set on plex like the documentation says to do on some of your other containers, could that be the issue?

**Comment by madcatsu** [comment]
Whilst I don't have @rjorgenson 's random crashes. I would also like to have TZ config available as an environment variable for the container, otherwise Plex Server scheduled tasks will run at UTC plus scheduled start versus local timezone plus scheduled start time.

TZ support would also help diagnose correct timestamps in logs for any issues within the container.

**Comment by sparklyballs** [comment]
@madcatsu , TZ config can be added to the run/create command.
The support comes from the baseimage used for the plex container.
For the sake of clarity though, i'm adding information about it to the README.

**Comment by madcatsu** [comment]
Thanks @sparklyballs for the clarification

**Comment by CHBMB** [comment]
Closing this as no update for a while.
