### ISSUE TITLE
Consider supporting healthchecks

### ISSUE THREAD

**Issue by rossdargan** [linuxserver/docker-plex#57]
I know this image is mainly used by unraid, but I'm using v1.12 and it would be great to have healthcheck support so I can easily see if plex is running ok. Also with Swarm it could automatically restart plex for me.

Happy to do a PR with the healthcheck added.

**Comment by sparklyballs** [comment]
not sure of the runtime implications of heathcheck in the dockerfile for a host with docker < 1.12
i know that attempting to build on a host with an earlier version fails the build.

**Comment by OmgImAlexis** [comment]
Any chance this could be reopened?

**Comment by aptalca** [comment]
See here: https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863

**Comment by OmgImAlexis** [comment]
> See here: [linuxserver/docker-tautulli#79 (comment)](https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863)

Those are both well outdated.

**Comment by aptalca** [comment]
Neither our stance nor Docker's has changed since
