### ISSUE TITLE
Webinterface not starting anymore

### ISSUE THREAD

**Issue by barrystaes** [linuxserver/docker-plex#61]
I have a situation where Plex is running but the webserver is not.

I previously used Limetech Plex docker on Unraid  for a while, but wanted to use the latest plex pass version so i switched to Linuxserver Plex. Odd thing is, it ran OK for a few hours before the issue appeared.

I document it here with all specifics i can find, it may be of use to others.

The conversion was simple:
I removed the old docker, then installed this one.
Set the `config` and `media` directories, and launched it.
For a few hours the webinterface was working fine. Now a day later i find that its offline.

Browser (Chrome) says:
```
The 192.168.2.30 page isn’t working
192.168.2.30 didn’t send any data.
ERR_EMPTY_RESPONSE
```

The Linuxserver Plex docker settings in Unraid 6.1.7:
![image](https://cloud.githubusercontent.com/assets/1420588/19014477/e9ecfd32-87ed-11e6-8f2c-28c78c7e1a3d.png)
*edit: replaced screenshot, no plexpass version*

The docker log in Unraid:
```
-------------------------------------
_ _ _
| |___| (_) ___
| / __| | |/ _ \ 
| \__ \ | | (_) |
|_|___/ |_|\___/
|_|

Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing... 
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing... 
No update required
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
Starting dbus-daemon
6 3000 /config/Library/Application Support
unlimited
[services.d] done.
Starting Avahi daemon
```
Yep, that log just ends there when i reboot it. At this point the Plex server is usable via Android app (browsing and streaming) but not via a webinterface.

I once found some avahi errors via a ssh session somewhere, but right now cant find it anymore.

No symlinks involved that i am aware of, i didnt make any for sure. 

I'm going to update this issue with my findings. I do this here instead of on the Limetech forum because i use this docker, i followed all instructions available that i am aware of, and because i saw avahi errors for this docker.

**Comment by barrystaes** [comment]
First it looks like avahi-daemon is running. How do i restart it?
(reason is https://github.com/timhaak/docker-plex/issues/22 )

```
top - 18:40:23 up  4:30,  0 users,  load average: 0.00, 0.04, 0.11
Tasks:  12 total,   1 running,  11 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.0 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  6172632 total,    44412 free,   641272 used,  5486948 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  4923132 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  297 abc       35  15 1776384  60120  11008 S   0.7  1.0   0:09.45 Plex Script Hos
    1 root      20   0     192      4      0 S   0.0  0.0   0:00.02 s6-svscan
   32 root      20   0     192      4      0 S   0.0  0.0   0:00.00 s6-supervise
  260 root      20   0     192      4      0 S   0.0  0.0   0:00.00 s6-supervise
  261 root      20   0     192      4      0 S   0.0  0.0   0:00.00 s6-supervise
  262 root      20   0     192      4      0 S   0.0  0.0   0:00.00 s6-supervise
  264 avahi     20   0   44920   2876   2548 S   0.0  0.0   0:00.08 avahi-daemon
  266 abc       20   0    4504    680    604 S   0.0  0.0   0:00.00 start_pms
  268 message+  20   0   42888   3548   3140 S   0.0  0.1   0:00.00 dbus-daemon
  286 abc       20   0  457368  69264  37628 S   0.0  1.1   0:18.08 Plex Media Serv
  398 root      20   0   18236   3328   2856 S   0.0  0.1   0:00.08 bash
 1141 root      20   0   36668   3184   2684 R   0.0  0.1   0:00.00 top
```

**Comment by barrystaes** [comment]
Some more info i should add - the port forwards seem to be fine since the webinterface worked before in this very docker instance. And all other networking is working as mentioned earlyer.

And the UID and GID where checked and they comply with https://hub.docker.com/r/linuxserver/plex/

**Comment by tobbenb** [comment]
Plexpass is not a valid variable for version as far as I know. Its only latest, public or a specific version.
If that doesn't work, then try with a fresh config.

**Comment by CHBMB** [comment]
https://github.com/linuxserver/docker-plex

Version variables are here, @tobbenb is right.

**Comment by barrystaes** [comment]
Yeah sorry its `latest` but apparently i took that screenshot when i tried `plexpass` to resolve this because i read it somewhere. Its set back `latest` now, like it was before.

**Comment by tobbenb** [comment]
And what happens with a fresh config?

**Comment by barrystaes** [comment]
Ok did a fresh config: I removed that docker + image. I reinstalled it again and only set the `/config` and `/media` settings. Then started it. My Android App can browse and stream, but the webinterface still is not working.

**Comment by tobbenb** [comment]
You still used the config from the old container?

**Comment by barrystaes** [comment]
Yup. I dont want to lose my Plex watch history..

**Comment by tobbenb** [comment]
You don't loose them by trying a fresh config. This is for troubleshooting.

**Comment by CHBMB** [comment]
can you try navigating to /mnt/cache/appdata/plexmediaserver/Library/Application Support/Plex Media Server and change the name of Preferences.xml or move it somewhere.

It will reset Plex to default but not cause you to lose your library database.

**Comment by barrystaes** [comment]
Ok thats good to know. I made a `tar.gz` backup anyway so i'll try this now.

**Comment by barrystaes** [comment]
Should i also NOT use the same `/config` value then.. for a fresh config?

**Comment by tobbenb** [comment]
For testing a fresh config you need to use another folder. Just call it pmstest.
If you want to do what chbmb suggest, its the same config.

**Comment by barrystaes** [comment]
Ok i just tried with just renaming `Preferences.xml` in that `/config` folder and the webinterface is showing now! Must be something in there.

Thanks! I would never have tried this otherwise. 🎱 😄 

I wonder what might have caused that. I'll see if i can post it here (without some sensitive values if any)

**Comment by tobbenb** [comment]
Most likely a setting from that old version (limetech) that our version liked. Or a corrupt file.
Good you got it sorted.

**Comment by barrystaes** [comment]
Thanks to @tobbenb and @CHBMB.

So my take from this is when upgrading from limetech to linuxserver Plex docker, it might be wise to rename Preferences.xml.

I logged in and can confirm the watch history is still there.

**Comment by CHBMB** [comment]
I don't think it's a common issue, I know others that have migrated without problems so don't think we need to add it to the readme.

Don't post anything from preferences, it's got lots of stuff in it you don't want to publish on the internet.

**Comment by sparklyballs** [comment]
i think it's something to do with one of the tokens in the preferences.xml file, had a user some months ago with a similar issue.

**Comment by Teggles** [comment]
Hey just wanted to chime in on this. I had this happen to me and the setting I changed to cause it was to tell my server to require secure connections. I assumed this would be streaming via the plex central server, not internally for the web based management UI.

**Comment by maxbbender** [comment]
Hey, +1 for Teggles, same thing happened to me. Changed the value of secure connections backed to true and all good!

**Comment by Teggles** [comment]
Or just tell your browser to connect via HTTPS and accept the unsigned certificate.

**Comment by maxbbender** [comment]
@Teggles, this might work for a direct connection but at least for me the indirect (through plex.tv) was still broken.
