### ISSUE TITLE
Automatic updates failing

### ISSUE THREAD

**Issue by spacecakes** [linuxserver/docker-plex#63]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 
DSM 6.0
 
Version=latest
 
"Atempting to upgrade to: LATEST
stdout
08:58:39
https://downloads.plex.tv/plex-media-server/LATEST/plexmediaserver_LATEST_amd64.deb:
stdout
08:58:42
2016-10-17 08:58:39 ERROR 404: Not Found."

No

**Comment by sparklyballs** [comment]
i would check that you are using `latest` and not `LATEST`

if i use `LATEST` i get the same error you're seeing.

**Comment by zaggash** [comment]
Maybe add a UPPER to lower check in the script.
I'll check a PR in the afternnon

**Comment by spacecakes** [comment]
Well, that's embarrassing, but thank you. Worked like a charm.

**Comment by zaggash** [comment]
thx for submitting the issue :)
