### ISSUE TITLE
Crash on Startup/Setup >>'--serverUuid' should follow immediately after the equal sign

### ISSUE THREAD

**Issue by rangerdude** [linuxserver/docker-plex#71]
I did many test will different version, and values and can't get past this one step.

Look to be a equals sign in the wrong place. 

Debian host
Direct pull and setup. 
Also I am very familiar with this project.
I have had the same container for months but pulled a new one. 
---

Brought to you by linuxserver.io
We do accept donations at:
## GID/UID

User uid:    1001
## User gid:    1001

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing...
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing...
Atempting to upgrade to: 1.2.3.2914-1ff0f18
2016-10-27 22:59:12 URL:https://downloads.plex.tv/plex-media-server/1.2.3.2914-1ff0f18/plexmediaserver_1.2.3.2914-1ff0f18_amd64.deb [101351844/101351844] -> "/tmp/plexmediaserver_1.2.3.2914-1ff0f18_amd64.deb" [1](Reading database ... 10950 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_1.2.3.2914-1ff0f18_amd64.deb ...
/var/lib/dpkg/info/plexmediaserver.prerm: 13: /var/lib/dpkg/info/plexmediaserver.prerm: stop: not found
Unpacking plexmediaserver (1.2.3.2914-1ff0f18) over (1.1.4.2757-24ffd60) ...
Setting up plexmediaserver (1.2.3.2914-1ff0f18) ...
Processing triggers for systemd (229-4ubuntu10) ...
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
Starting Plex Media Server.
[services.d] done.
6 3000 /config/Library/Application Support
8192
Starting Avahi daemon
Found user 'avahi' (UID 106) and group 'avahi' (GID 107).
Successfully dropped root privileges.
avahi-daemon 0.6.32-rc starting up.
Failed to open /etc/resolv.conf: Permission denied
No service file found in /etc/avahi/services.
**\* WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
**\* WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.20.
New relevant interface eth0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for 192.168.0.20 on eth0.IPv4.
Server startup complete. Host name is omv.local. Local service cookie is 660178480.
*****\* PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.2.3.2914-1ff0f18/PLEX MEDIA SERVER/21839854-4d50-5ff5-524ff319-1ceb1362.dmp
terminate called after throwing an instance of 'std::runtime_error'
  what():  Codecs: Initialize: 'Failed to create UUID file'
Segmentation fault
Starting Plex Media Server.
6 3000 /config/Library/Application Support
8192
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --url arg             URL to upload to
  --help                show help message
  --version arg         Version of the product
terminate called after throwing an instance of 'std::runtime_error'
  what():  Codecs: Initialize: 'Failed to create UUID file'
*****\* PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.2.3.2914-1ff0f18/PLEX MEDIA SERVER/6abcaa36-4fac-5a76-4cc2ae6e-034ffdab.dmp
Segmentation fault
Starting Plex Media Server.
6 3000 /config/Library/Application Support
8192
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
  --directory arg       Directory to scan for crash reports
  --serverUuid arg      UUID of the server that crashed
  --userId arg          User that owns this product
  --platform arg        Platform string
  --url arg             URL to upload to
  --help                show help message
  --version arg         Version of the product
*****\* PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.2.3.2914-1ff0f18/PLEX MEDIA SERVER/743dc8c4-cd30-1314-478d360a-69d77e57.dmp
Segmentation fault

**Comment by mynameismevin** [comment]
I hit the same error when trying to manually set the permissions for the runtime user as well; I just did `PUID=0;PGID=0` due to a cifs permission issue.

**Comment by rangerdude** [comment]
I have found that this is not a bug but the drive was mount with noexec and plex now needs exec permissions as they have moved codecs out of the system area. Not good! Not a good idea at all.

This can be closed.

**Comment by robsmy** [comment]
Hi, I am struggling to mount with exec permissions.
Please help, my fstab entry is:
//192.168.0.71/plex /media/plex cifs  username=XXX,password=YYY,rw,exec  0  0

**Comment by CHBMB** [comment]
@robsmy What has this got to do with this issue?

**Comment by dasjestyr** [comment]
@CHBMB read ranger dudes last comment. That's what it has to do with this issue.
