### ISSUE TITLE
Unable to register plex server from docker image 

### ISSUE THREAD

**Issue by nickwinn** [linuxserver/docker-plex#73]
Tried to use your docker plex image and can't register it as a server. Upon starting up and initial connect, it takes you direct to a sign in screen. This is the incorrect behavior, it should allow you to setup the plex instance, then sign in to register it as a server. 

Logging into the plex instance only gives you the ability to view friends media, the same as signing in to plex.tv and nothing else. 

Running this on Ubuntu 14.04.4 LTS with Docker 1.12.3

docker run -d -p 32400:32400 -p 32469:32469 -v /remote:/remote --name plex linuxserver/plex

docker logs output - http://pastebin.com/4r9j6abc

**Comment by iWuzHere** [comment]
Running into the same issue

**Comment by iWuzHere** [comment]
Issue was resolved by putting my `PlexUserToken` inside Preferences.xml

**Comment by Gmentsik** [comment]
Can you explain more in detail?

**Comment by imran-iq** [comment]
Signing in with out being able to setup the plex server still creates a `Prefences.xml` file
under `<your config dir>/Library/Application Support/Plex Media Server/Prefences.xml`
Simply open that and add `PlexOnlineToken="<your token here>"` to the file and save and exit and restart the container.

See [here](https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token) on how to get your plex token

**Comment by nickwinn** [comment]
This kind of pushed me down the rabbit hole of rolling my [own Plex Docker instance][https://github.com/nickwinn/nickflix] which lead me to the solution; `disablePlexSecurity=1` as a way to register my server. Once the server is registered, I then change it to `disablePlexSecurity=0`.

**Comment by CHBMB** [comment]
Try running it as host rather than bridge.

**Comment by j0nnymoe** [comment]
Closing this issue. These errors come up as I believe users are installing plex on a remote server.
As @nickwinn pointed out, you need to disable the remote security first so that you are able to register the plex server.
