### ISSUE TITLE
Are you able to cast something to a chromecast using this image ?

### ISSUE THREAD

**Issue by gpapin** [linuxserver/docker-plex#74]
Ok so I used to have the plexmediaserver installed on a ubuntu server and all worked just fine.

Recently I change all my infrastructure to use docker and suddenly the cast feature stopped working. I spent quite some time investigating on this and I have a beginning of a solution.

I think all comes down to the fact that I have my own DNS server internally so when I'm connected to Plex I use plex.myowndomain.com. As far as I understand, when the cast is asked to play something, Plex send it a url to play this url will contain plex.myowndomain.com. The first issue here is that the Chromecast is using google DNS regardless of what the DHCP server is telling giving it...

I was able to confirm that theory by routing 8.8.8.8 and 8.8.4.4 to my DNS and it worked ! Although some times when accessing the Plex server by it's ip:port it didn't work as well...

**Right so you might says : what is docker-plex has to do with this !?**

If I'm honest I don't know... I only know that it used to work all the time when Plex was used natively.
I will continue to investigate this but if you have any suggestion, that might be useful thanks !

**Comment by CHBMB** [comment]
I use this image to cast regularly, if that helps at all..

**Comment by gpapin** [comment]
Something must be wrong with my conf then - This is good to know ! :) . I'll run more tests tonight and see if I can get it to work, if not some help will be very appreciated. Especially on where to look for mistakes and the common pitfalls.

**Comment by CHBMB** [comment]
It just worked for me, no config necessary....

**Comment by Pheoxy** [comment]
I had this issue a while ago. Do you have UPNP enabled on your router? If not check the [why isn't it working page](https://support.plex.tv/hc/en-us/articles/206225077-How-to-Use-Secure-Server-Connections) on the plex support site.

You might need to do some DNS Rebinding on router:
`rebind-domain-ok=/plex.direct/`

This fixed it for me.

**Comment by sparklyballs** [comment]
closing this, 
seems to have been covered by two replies.

**Comment by gpapin** [comment]
I do have UPNP enable on my router however I don't know how to do a DNS rebinding on it since I'm not running a DD-WRT firmware.
The only way for it to work at the moment is to create a static route on my router to forward the traffic from google's DNS to my internal DNS, however it's  not sustainable since my internal DNS rely on google's DNS to forward most request.... So it's  either getting the cast to work or the internet at the moment...

I will have a look into the official plex docker to see if there is something different and i'll let you know.

**Comment by gpapin** [comment]
So I've now moved to using the official docker image and it's doing exactly the same... I suppose The solution I'll found will also be applicable using this image so I'll let you know if and when this happens
