### ISSUE TITLE
[REQ] Update without CHMOD

### ISSUE THREAD

**Issue by Mirabis** [linuxserver/docker-plex#78]
**Provide a general summary of the issue in the Title above**

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

**If you have an issue with the project, please provide us with the following information**

**Host OS**
Ubuntu 16.10 / Docker
**Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings**
Docker-compose up -d
** Docker log output, docker log <container-name> **

```
plex_1     | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
plex_1     | *** Running /etc/my_init.d/10_add_user_abc.sh...
```

** Mention if you're using symlinks on any of the volume mounts. **
Volume mounts to /opt/data/plex (in VM)

**If you have a suggestion or fix for the project, please provide us with the following information**

Please add a option to skip the chmod process, it takes over 15 minutes on a large library... and i'm already using NVME disks....

** What you think your suggestion brings to the project, or fixes with the project**
Adds to the user experience.

**If it's a fix, would it be better suited as a Pull request to the repo ?**

Possibly

**Comment by aptalca** [comment]
It should only take a long time if you change ownership of the files later on. And it should be a one time thing. On my install, where the files are already owned by the same user, it takes a split second.

Do you have another script running that changes ownership of those files on a regular basis? Are you using the uid and gid of your unraid user in the envrionment variables?

**Comment by Mirabis** [comment]
I'm using PUID & GUID = 0, which corresponds to my Root user running docker being 0.

It has always done the chown for me... not sure why...

**Comment by aptalca** [comment]
id root gives you info only on the root user
I'm assuming you're doing `sudo -i` in ubuntu to switch to the root user. Don't do that. Log into ubuntu with the regular user account (I'm pretty sure ubuntu requires setting up a regular user/admin account) then run `id` and use the uid and gid of that user
We don't recommend running our docker containers as root

On my ubuntu vm, the user is called ubuntu and here's what I get with `id`:
`uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),27(sudo),44(video),46(plugdev),107(input)`

so I use PUID=1000 and PGID=1000
all plex files are owned by ubuntu:ubuntu

**Comment by Mirabis** [comment]
When setting up the vm there was a user called 'davey', which had been removed once root was enabled. The only user now is root (against best practices....) 

I login directly into root, instead of sudo'ing

**Comment by sparklyballs** [comment]
i'm going to close this one, it's not recommended to run as root.
