### ISSUE TITLE
ARM build for Raspberry Pi

### ISSUE THREAD

**Issue by RomkeVdMeulen** [linuxserver/docker-plex#82]
Thank you so much for providing this image! I'd love to be able to run this on my RPi at home. Is there an ARM build of this image anywhere? If not, are there any plans for that? Anything I can do to help, please let me know.

**Comment by CHBMB** [comment]
https://hub.docker.com/r/lsioarmhf/plex/

**Comment by RomkeVdMeulen** [comment]
Nice! Thanks for the pointer.

**Comment by CHBMB** [comment]
No problem.
