### ISSUE TITLE
unable to  exec run

### ISSUE THREAD

**Issue by chuckleb** [linuxserver/docker-plex#84]
After updating to the latest CentOS 7.3 and all patches, I get a new error. This was working fine in the previous version of Docker, but with 1.10.3 (latest stock), it breaks on startup with this:

s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise avahi: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise plex: warning: unable to spawn ./run - waiting 10 seconds

This may be related to this error:
https://github.com/just-containers/s6-overlay/issues/158

**Comment by chuckleb** [comment]
running the docker with a -v /run is a temporary workaround for this.

`docker run -d --net=host -e VERSION=latest -e PUID=0 -e PGID=0 -e TZ=America/Chicago -v /mnt/plex:/config -v /mnt/video:/data  -v /run linuxserver/plex`

**Comment by sparklyballs** [comment]
follow the install instructions for docker on centos 

https://docs.docker.com/engine/installation/linux/centos/

**Comment by chuckleb** [comment]
I have the latest docker installed from the CentOS repo, which is locked at 1.10.3. There is a bug in which oci-systemd-hook sets /run as a tempfs filesystem. To get around it, you need to map /run over it or renaming the script I think. I do know that passing in the -v /run as I suggest allows the container to run, and this may be helpful for others to know when they run into this again.

Not sure how you'd like to fix this other than update the docs? But others will probably run into this as well.

**Comment by sparklyballs** [comment]
the version from the docker installation instructions on the page i linked works on centos 7

the yum version direct from centos does not.
