### ISSUE TITLE
Container crashes ater ~ 1 week

### ISSUE THREAD

**Issue by powerriegel** [linuxserver/docker-plex#90]
I run your docker iomage for plex media server on Debian Jessy. The server runs 24/7 without interruption. 

I noticed that the container crashes or is shut down ~ once a week. How can I find out why? 

I noticed a few lines in the logs but don't know if they are the reason:

```
No service file found in /etc/avahi/services.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.42.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface bond0.IPv4 with address 192.168.170.11
```

I start my container with 
`docker start plex`

Image is created with

```
docker create \
--name=plex \
--net=host \
-e VERSION=latest \
-e PUID=111 -e PGID=222 \
-e TZ=Europe/Berlin \
-v /var/lib/plexmediaserver/:/config \
-v /home/username/Music:/data/music_user \
-v /home/username2/Music:/data/music_user2 \
-v "/home/username/Shared/Lightroom Export":/data/pictures \
-v /home/username/Movies:/data/movies \
linuxserver/plex
```

Config file is from a previous, locally installed version of Plex. I'm a Plex Pass owner.

**Comment by aptalca** [comment]
Those are avahi related error messages and they are harmless because avahi is a separate service and plex runs even without it (I get them sometimes too)

You may have to look at the plex server logs to see what might cause it to crash. Perhaps a plugin?

**Comment by powerriegel** [comment]
No plugins installed. How do I look at the correct logs (after plex is restarted).

**Comment by aptalca** [comment]
https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files

**Comment by j0nnymoe** [comment]
Checking in to see if this is still an issue? If not, I will close this issue.

**Comment by j0nnymoe** [comment]
If this issue happens again, Please reopen the issue.

**Comment by powerriegel** [comment]
The issue did not happen since last update.
