### ISSUE TITLE
Multiple Plex Servers

### ISSUE THREAD

**Issue by Codgedodger** [linuxserver/docker-plex#91]
I know this has been asked before but I need help with a walk through. I was given a set of IPs when I got my server setup. I'd like to have multiple Plex servers running on my server. I already have a plain one installed and running just fine. I'd like to have the other Plex server run though Docker on a different IP the company gave me.

They gave me these IPs.
198.xxx.xx.232/29

My server IP now has 198.xxx.xx.234
Could someone help me with walking me through with another docker for my Plex servers? I'd be willing to donate via Paypal at this point.

**Comment by j0nnymoe** [comment]
Hi, Not sure if this is still an issue or not but this might give you some useful information: http://blog.programster.org/docker-run-with-same-host-same-port/ other than that I'm not really sure what else to suggest. I'm gonna close this ticket for now but if you find out how to do with, It would be interesting to know :smile:
