### ISSUE TITLE
Container shutdown freezing

### ISSUE THREAD

**Issue by najmead** [linuxserver/docker-plex#92]
Trying to shutdown (or restart) this container is hanging.  When I check the logs (ie, docker logs -f plex), it appears to be stuck on the following step;

[s6-finish] syncing disks.

Just checked, and I'm not sure if this is isolated to plex since I've got a similar issue with some other lsio containers.

**Comment by j0nnymoe** [comment]
Please can you provide some more information such as host os / logs otherwise its like trying to find a needle in a haystack.

Thanks

**Comment by CHBMB** [comment]
Please Fill in this otherwise I'm going to close the issue.



[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	














##  Thanks, team linuxserver.io

**Comment by najmead** [comment]
FYI, the host is debian stretch.  But you can close this issue... I don't know what the step "syncing disks" is doing, but I'm guessing it is syncing buffered data to the hard drive.  And I suspect this was conflicting with another task I was running (outside the container).  When the external task completed, the container completed it's shutdown.
