### ISSUE TITLE
Latest version appears to have a broken auto update

### ISSUE THREAD

**Issue by thybag** [linuxserver/docker-plex#93]
Hello,

Noticed with the latest release that restarting my plex container no longer appears to update the sever.

A quick check of the logs suggests it may be having trouble reading the $REMOTE_VERSION

```
Atempting to upgrade to:
https://downloads.plex.tv/plex-media-server/%20/plexmediaserver_%20_amd64.deb:
2017-02-02 18:32:34 ERROR 404: Not Found.
```

Haven't had a chance to properly read through the plex update script yet to debug any further, but was wondering if others were having the same issue (or if i've just manged to get my container in to a weird state)

In case it helps:

Host O/S: Ubuntu
Using: -VERSION=latest
Am a plexpass user

Have been using an old version of the container without issues for a while now & only recently updated. Previously updating the server stuff worked as expected.

EDIT:

Tiny bit more debugging, may be somthing on plex's end has changed
`https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=<snip>` appears to return blank for me

**Comment by sparklyballs** [comment]
there appears to be an issue with the plex download site in general for the ubuntu images.
this is obviously something beyond our control, and as such i'm closing this issue.

**Comment by shuaiscott** [comment]
Had the same issue. Its fixed by updating the following env var or pulling down the latest docker image that has the change:

PLEX_INSTALL="https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu" \
