### ISSUE TITLE
Logs from Docker are inaccessible

### ISSUE THREAD

**Issue by sunshinekitty** [linuxserver/docker-plex#94]
When trying to access the logs for this container using `docker logs <container-id>` the following error is produced:
```
"logs" command is supported only for "json-file" and "journald" logging drivers (got: syslog)
```

Rockstor 3.8.16-1

**Comment by tobbenb** [comment]
This is a Rockstor issue, so you will have to make them fix it.

**Comment by aptalca** [comment]
When you create the container, you can use the option `--log-driver=json-file` and for that container it will switch logging to the old method and `docker logs` will retrieve them. Not sure if it will cause any rockstor related issues, though.
