### ISSUE TITLE
Plex Startup Loop 

### ISSUE THREAD

**Issue by Ashtonian** [linuxserver/docker-plex#96]
I setup plex on a media library and everything seems fine, shortly after it updates to latest and fetches all the metadata it crashes and just repeats the following in the logs. 
 ```
;2017-04-01T01:08:06.514699177Z Starting Plex Media Server.
J2017-04-01T01:08:06.542001764Z 6 3000 /config/Library/Application Support
$2017-04-01T01:08:06.542040024Z 8192
;2017-04-01T01:08:09.768303552Z Starting Plex Media Server.
J2017-04-01T01:08:09.796615906Z 6 3000 /config/Library/Application Support
$2017-04-01T01:08:09.796650185Z 8192
;2017-04-01T01:08:13.021842939Z Starting Plex Media Server.
J2017-04-01T01:08:13.036341442Z 6 3000 /config/Library/Application Support
$2017-04-01T01:08:13.036372631Z 8192
;2017-04-01T01:08:16.261960505Z Starting Plex Media Server.
J2017-04-01T01:08:16.276077042Z 6 3000 /config/Library/Application Support
$2017-04-01T01:08:16.276119886Z 8192
;2017-04-01T01:08:19.501346794Z Starting Plex Media Server.
J2017-04-01T01:08:19.529055749Z 6 3000 /config/Library/Application Support
$2017-04-01T01:08:19.529095411Z 8192
;2017-04-01T01:08:22.754229524Z Starting Plex Media Server.
J2017-04-01T01:08:22.781426270Z 6 3000 /config/Library/Application Support
$2017-04-01T01:08:22.781482921Z 8192
```

Ubuntu Latest 

```
docker create 
--name=plex 
--net=host 
--restart=always 
-e VERSION=latest 
-v /media/Lutece:/data/lutece 
-v /media/Atlas/Plex:/config 
-e PGID=0 
-e PUID=0 
linuxserver/plex
``` 
Lutece is a MergerFS mount point and Atlas is a drive in that FS. any ideas on increasing the log verbosity ? I'll be opening an issue on the plex boards as well.

**Comment by j0nnymoe** [comment]
This could be happening due to a number of reasons, running the container as root but also /config needs to be on a local FS mount without going through mergerfs.

**Comment by lonix** [comment]
Due to how the base image is build it does not really work with root. (Unless @sparklyballs changed something)

**Comment by Ashtonian** [comment]
The config is pathed directly to a local drive. 

It was working for at least the last 6 months with that configuration. But I can correct that and try again. Just for clarification the proper way would be to create plex only user give it r/w to the config folder and read access to the media folders?

**Comment by Ashtonian** [comment]
I went into the docker image and found the following in the server log just after trying to a cert. 

```
Apr 04, 2017 15:18:40.442 [0x7fa7405bd840] ERROR - Error: Unable to set up server: bind: Cannot assign requested address (N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE)
```

**Comment by Ashtonian** [comment]
Fixed it by disabling ipv6 support manually on the docker image. It looks like plex has problems binding to an ipv6 port? probably because the box wasn't setup for ipv6. 

used `docker exec -it /bin/bash` to get into the image and then navigated to `/config/Library/Application Support/ Plex Media Server/` and changed `EnableIPv6="1"` to `EnableIPv6="0"` in the Preferences.xml file. 


Got that from: 
https://www.burgundywall.com/post/cant-start-plex-in-docker-container 
https://forums.plex.tv/discussion/51427/plex-media-server-for-debian/p31

**Comment by tnwhitwell** [comment]
@Ashtonian I just saw exactly the same on my box - also resolved with ```EnableIPv6="0"```

**Comment by sparklyballs** [comment]
i'm going to close this as seems related to IPV6 issues.
