### ISSUE TITLE
Server not available (marked offline) to clients

### ISSUE THREAD

**Issue by usharf** [linuxserver/docker-plex#97]
On macOS, I have the following configuration and able to claim server with my account (PlexPass). I can use the browser on the local machine to access the server, but not with any clients (i.e. iOS). The server is listed, but marked offline all the time.

```bash
  plex:
    image: linuxserver/plex
    container_name: plex
    # network_mode: host
    #   does not work ib macOS currently
    #   https://github.com/docker/compose/issues/3800
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    volumes:
      - ~/.server-io/plex/config:/config
      - ~/.server-io/plex/transcode:/transcode
      ........
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/XXXX
      - VERSION=latest
```

**Comment by CHBMB** [comment]
You opened your port on the firewall?

**Comment by j0nnymoe** [comment]
I believe you need to define more ports in bridge mode:
```
-p 32400:32400/tcp \
-p 3005:3005/tcp \
-p 8324:8324/tcp \
-p 32469:32469/tcp \
-p 1900:1900/udp \
-p 32410:32410/udp \
-p 32412:32412/udp \
-p 32413:32413/udp \
-p 32414:32414/udp \
```

**Comment by usharf** [comment]
Hi, thanks. Yes, I saw that on macOS I would need to and I already did. I found since that I would also need to add "customConnections" with my hosts ip in order to be able to find the server, whic seems to work.

10x
