### ISSUE TITLE
Upgrade on first run rather than on restart

### ISSUE THREAD

**Issue by patsissons** [linuxserver/docker-plex#98]
Every now and then plex locks up (due to some bug i can't quite figure out, but unrelated to this issue none the less). To resolve this lock up, I need to restart the container. The problem is that I don't really want to restart and also upgrade, just quickly restart.

I am curious what the lsio thoughts are on transitioning upgrades to first run of the container (possibly through the existence of a file, which would be deleted upon upgrade completion). This would result in a much more deterministic container rather than a container that evolves over time. The new method of upgrading would be to simply redeploy the container (essentially, `pull`, `stop`, `rm`, `run`) to force an upgrade. Additionally, re-creating the upgrade file could also force an upgrade on restart.

Obviously this is not much of a critical issue, but perhaps worth discussing?

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
If you're referring to the ubuntu package updates, our images haven't used that method in a very long time. We now do weekly refreshes of the containers (for which you would have to do pull, stop, rm, run as you described).

As for the plex application update, it should only do that if there is an update

**Comment by patsissons** [comment]
that's my point.

* container runs without restart for several weeks
* container locks up
* restart to fix lock up
* container upgrades plex but a plex upgrade is not desired.

**Comment by sparklyballs** [comment]
well don't use the VERSION variable and it won't try to update

**Comment by patsissons** [comment]
well i do want it to upgrade, just not on restart only after I create a new container. I guess maybe what I am asking is if it's possible to upgrade to `VERSION` (or latest) plex when the container is created and run for the first time?

**Comment by aptalca** [comment]
Well, that's just it. If you don't set the version variable, it won't update on restart. And when you want it to upgrade, pull the image and recreate the container, and it will have the latest version as of the Friday before (latest image refresh)

**Comment by aptalca** [comment]
You can also set the version to a specific version and have it pull that, that way, you control when it updates and to which version

**Comment by patsissons** [comment]
how often do you guys publish new images? if it is reasonably often then this sounds completely reasonable.

**Comment by aptalca** [comment]
Every Friday night

**Comment by patsissons** [comment]
oh perfect. I will remove the `VERSION` env var then. Thanks for clarifying.
