### ISSUE TITLE
Plextras Support

### ISSUE THREAD

**Issue by JoeStratton** [linuxserver/docker-plex#99]
This isn't an issue, more of an inqiry. Would it be possible to apply this to the container?
https://github.com/andrewiankidd/Plextras.js

Its a great script to modify the web client slightly, but I am thinking it would have to be integrated into the docker container itself. Rather than having to apply it to just my browser/PMP.

I don't see this as something you guys would add, so more looking to see if there's a workaround. Am I wrong?

Thanks!

unRAID

**Comment by lonix** [comment]
There used to be a way to Run custom scripts at the end of the container startup. this feature seems to have disappeared. @sparklyballs is there a plan for this to return?

**Comment by sparklyballs** [comment]
no plans on bringing that back...

but if REALLY REALLY wanted to add stuff to a container, just mount a file into /etc/cont-init.d

ie... `-v <some-local-location>/95.bullshit-script:/etc/cont-init.d/bullshit-script`

**Comment by lonix** [comment]
I Could agree to that, I would prefer that User does that rather than including it into the base container.
